### ISSUE TITLE
Crash upon a Disconnect

### ISSUE THREAD

**Issue by VoidJoined** [coop-deluxe/sm64coopdx#101]
**Describe the bug**
When disconnecting from a lobby sm64coopdx.exe crashes.

**To Reproduce**
1. Open 'sm64coopdx'
2. Click on 'Join'
3. Click on 'Public Lobbies'
4. Click on 'any lobby'
5. Pause with Plus or Spacebar when ingame
6. Enter Options with the R button or Shift
7. Click on 'Disconnect'
8. Click on 'Yes'
9. See error

**Expected behavior**
Getting send back to the main menu.

**Screenshots**

![Screenshot 2024-03-21 224701](https://github.com/coop-deluxe/sm64coopdx/assets/164636763/d8e0528b-f5be-45f5-a641-15a85187703f)

![Screenshot 2024-03-21 230017](https://github.com/coop-deluxe/sm64coopdx/assets/164636763/56827051-da93-4be0-af38-f0f6d1b3e7c3)

![Screenshot 2024-03-22 170951](https://github.com/coop-deluxe/sm64coopdx/assets/164636763/45896052-b968-40e5-9000-c8a9db266e1a)

![Screenshot 2024-03-22 184149](https://github.com/coop-deluxe/sm64coopdx/assets/164636763/244dc967-7050-4970-9529-2a060b1e2633)

![Screenshot 2024-03-23 084244](https://github.com/coop-deluxe/sm64coopdx/assets/164636763/1046555b-a5c4-4d5f-8780-9b2bca157e3e)

![Screenshot 2024-03-23 135229](https://github.com/coop-deluxe/sm64coopdx/assets/164636763/d1d86ff2-c0ea-48c1-aa5c-1e6e05bf576e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 64-bit operating system

**Additional context**
Using the most recent version of sm64coopdx (v0.2)

Same error happens consistently when: 
- you are the host and you press 'stop hosting'
- when you attempt to enter a lobby but couldn't join
- when you press cancel while you are joining the lobby

(seems to occur when the host closes the lobby, unsure due to not being able to test on my own)
(same error happened while just playing, doesn't make as clear of a pattern as the other issues)

Issue Occurs when using the DirectX Driver, with OpenGL this issue doesn't happen however it has it's own issue with the screen being obscured with green lines unless you enter fullscreen. The recommended fix for that issue has been to use DirectX instead.

- Multiple attempts were made to make a new exe with the patcher.
- GeForce experience has been updated to the Newest Nvidia Studio Driver as of now (Version 551.86).
- Laptop has been diagnosed for memory problems.
- Attempts have been made to clean up corrupted files using System File Checker.

I would really appreciate if i could get some help with this.

Thank you for reading!

**Comment by uuphoria2** [comment]
This doesnt happen to me at all

**Comment by Agent-11** [comment]
Yeah this is a problem with DirectX

**Comment by Flower35** [comment]
Hello. The game crashes because it tries to call NULL pointer at `reset_window_title();` in `network_shutdown()`.

So basically it crashes any time you shutdown any game from main menu (as a host, as a client, or being disconnected from any server).

The issue with the **DirectX** build is that two of the fields in `GfxWindowManagerAPI` were left uninitialized (I assume by mistake):

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/gfx/gfx_dxgi.cpp#L733

Two entries are missing at the end of the **structure initializer**:
```c
    gfx_dxgi_set_window_title,
    gfx_dxgi_reset_window_title
};
```

This is unfortunatelly not caught as a warning during compilation, because according to the **C** standard:

> *All members that are not initialized explicitly are empty-initialized.*

**Comment by Agent-11** [comment]
OH. This is my mistake.

**Comment by Agent-11** [comment]
Also you have been a great help with solving bugs, I thank you for putting these detailed reports together. If you want, I can invite to our Discord server as a token of my gratitude.

**Comment by Flower35** [comment]
Sounds good, although idk how much I can help besides fixing bugs every now and then... 😄

My Discord handle is the same as my GitHub nickname.

**Comment by frog8412** [comment]
i have the same problem, how do i fix this?
