### ISSUE TITLE
Suggestion: custom keybinds API for lua mods

### ISSUE THREAD

**Issue by tulpenkiste** [coop-deluxe/sm64coopdx#102]
I've been playing coopdx for a while and I've thought of an idea that would make utilising certain mods and their features more convenient.

The idea is an API where mod developers can "register" a custom keybind, along with a function it should run once the input has been received and a default bind.

An example where this could be used is in the Character Select mod, where instead of typing in a command, you could press a button and have the menu appear/disappear whenever you want.

If added, these keybinds should probably receive their own submenu in the Controls settings along with a way to organise the settings by mod (similar to what was suggested in the "Tag your mods" suggestion in issue #69)

**Comment by AgentXLP** [comment]
Mods are capable of making their own binds listening to `gControllers[0].buttonPressed`
