### ISSUE TITLE
Suggestion: Maybe some type of utility made via visual studio or use VB Basic (for https://mods.sm64coopdx.com)

### ISSUE THREAD

**Issue by uuphoria2** [coop-deluxe/sm64coopdx#105]
Suggestion: Maybe some utility GUI created via Visual Studio for mod making which could have shortcuts like opening Visual Studio Code, Or linking to the proper guides for Lua documentation maybe

Suggestion 2: Preset Lua mods. such as test chat commands (/testoutput) results in the chat output saying: Test

Section of mods.sm64coopdx.com this could go in: https://mods.sm64coopdx.com/mods/categories/resources.13/

**Comment by Agent-11** [comment]
This isn't a suggestion for the game.

**Comment by uuphoria2** [comment]
> This isn't a suggestion for the game.

You can close this as completed now I was just being an idiot for no reason
