### ISSUE TITLE
Game crash after exiting C-Up mode and disabling Free Camera mode

### ISSUE THREAD

**Issue by Flower35** [coop-deluxe/sm64coopdx#106]
### Steps to reproduce the behavior

1. Start a new game (or enter a new level)
2. Check the following options in the "Camera" options menu:
    - [x] Free Camera
    - [x] Free Camera C-Up
3. Leave the second option unchecked:
    - [ ] Analog Camera
4. Back in the game, enter the first person mode while using the "Free Camera" mode
    - this might be a bit tricky, for me it works when I quickly press the "C-Right" and "C-Up" binds (keyboard or gamepad)
5. Exit the "C-Up" mode (press any of the "C" keys / move the camera)
6. Go to the "Camera" options menu again, and uncheck the first option:
    - [ ] Free Camera
7. The game will suddenly crash

---

### Expected behavior

The game should switch from the Free Camera ("newcam") mode back to the original camera mode.

---

### Desktop specs

 - OS: Windows 10, 64-bit
 - Renderer: OpenGL
 - Version: latest (0.2.3)

---

### Additional context

As for the technical details, the crash happens in the `set_camera_mode()` function:

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/game/camera.c#L2999

The game "wants" to return back to the "C-Up" camera mode, even though the player already left it.

`set_camera_mode(c, -1)` is invoked from `mode_c_up_camera()`.

`c->mode` and `gLakituState.mode` are both set to `0x06 = CAMERA_MODE_C_UP`.

`sModeInfo.lastMode` is however wrongly set to `0x12 = CAMERA_MODE_NEWCAM`.

The "newcam" entry in `CameraTransition sModeTransitions[]` is set to `NULL`, because it was never expected to be invoked in that context (Free Camera uses spearate module, not related to the original Mario64 camera).

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/game/camera.c#L497

---

**Comment by Flower35** [comment]
I have tried to trace how Camera State changes with "Free Cam + C-Up" mode, but it really gets messy... 😅
```
--------------------------------

enter new level, "Free Camera" Disabled

    init_camera(c) => newcam_toggle(false)

        newcam_active        = 0 = FALSE
        gLakituState.mode    = 0x10 = CAMERA_MODE_FREE_ROAM
        gLakituState.defMode = 0x10 = CAMERA_MODE_FREE_ROAM
        newcam_saved_mode    = 0xFFFF
        newcam_saved_defmode = 0xFFFF

enter "C-Up" camera, "Free Camera" Disabled

    act_first_person() => set_camera_mode(c, 0x06 = CAMERA_MODE_C_UP)

        gLakituState.mode = 0x06 = CAMERA_MODE_C_UP
        c->mode           = 0x06 = CAMERA_MODE_C_UP

leave "C-Up" camera, "Free Camera" Disabled

    act_first_person() => set_camera_mode(c, 0xFFFFFFFF)

        gLakituState.mode = 0x10 = CAMERA_MODE_FREE_ROAM
        c->mode           = 0x10 = CAMERA_MODE_FREE_ROAM

--------------------------------

enter new level, "Free Camera" Enabled

    init_camera(c) => newcam_toggle(true)

        newcam_active        = 1 = TRUE
        gLakituState.mode    = 0x12 = CAMERA_MODE_NEWCAM
        gLakituState.defMode = 0x12 = CAMERA_MODE_NEWCAM
        newcam_saved_mode    = 0x0010 = CAMERA_MODE_FREE_ROAM
        newcam_saved_defmode = 0x0010 = CAMERA_MODE_FREE_ROAM

enter "C-Up" camera, "Free Camera" Enabled

    newcam_loop() => newcam_rotate_button() => newcam_toggle(true)

        does nothing

    act_first_person() => set_camera_mode(c, 0x06 = CAMERA_MODE_C_UP) => newcam_toggle(false)

        newcam_active        = 0 = FALSE
        gLakituState.mode    = 0x10 = CAMERA_MODE_FREE_ROAM
        gLakituState.defMode = 0x10 = CAMERA_MODE_FREE_ROAM
        newcam_saved_mode    = 0xFFFF
        newcam_saved_defmode = 0xFFFF

    (...)

        gLakituState.mode = 0x06 = CAMERA_MODE_C_UP
        c->mode           = 0x06 = CAMERA_MODE_C_UP

leave "C-Up" camera, "Free Camera" Enabled

    exit_c_up() => newcam_toggle(true)

        newcam_active        = 1 = TRUE
        gLakituState.mode    = 0x12 = CAMERA_MODE_NEWCAM
        gLakituState.defMode = 0x12 = CAMERA_MODE_NEWCAM
        newcam_saved_mode    = 0x0010 = CAMERA_MODE_FREE_ROAM
        newcam_saved_defmode = 0x0006 = CAMERA_MODE_C_UP

    (...)

        gLakituState.defMode = 0x10 = CAMERA_MODE_FREE_ROAM
        c->mode              = 0x12 = CAMERA_MODE_NEWCAM

    act_first_person() => set_camera_mode(c, 0xFFFFFFFF)

        gLakituState.mode = 0x12 = CAMERA_MODE_NEWCAM

Main Menu, Disable "Free Camera" option, game crashes

--------------------------------
```

**Comment by Agent-11** [comment]
This whole feature is awfully buggy and I regret even adding it. It has been removed for the next major version.
