### ISSUE TITLE
"No Lobbies were found"

### ISSUE THREAD

**Issue by Lucariothehorrorguy** [coop-deluxe/sm64coopdx#112]
Okay so i've tried to join a Private Lobby. I put the right password and somehow it says there are "No Lobbies Found"

**Comment by Agent-11** [comment]
Make sure you have the right password and compatibility mode before jumping to making an issue.

**Comment by uuphoria2** [comment]
Check the password spelling That can also stop you from joining if the password has specific spellings like you could type "test" and it wont work cuz the real password is  for example "teST"
