### ISSUE TITLE
Screen with green filter

### ISSUE THREAD

**Issue by Oika64** [coop-deluxe/sm64coopdx#114]
When compiling the game in OpenGL the game puts this kind of green filter on the screen, I haven't seen anyone else have this problem and I updated my drivers to make sure that wasn't the problem.
![image](https://github.com/coop-deluxe/sm64coopdx/assets/164689226/a966c640-2361-4328-8bd6-7799744ff157)

**Comment by uuphoria2** [comment]
Compile with DirectX

**Comment by Oika64** [comment]
> Compile with DirectX

what happens is...
the game crashes constantly with DirectX

![image](https://github.com/coop-deluxe/sm64coopdx/assets/164689226/20c55e32-fb40-49b5-bc81-26f96ca9e1e0)

**Comment by Flower35** [comment]
> > Compile with DirectX
> 
> what happens is... the game crashes constantly with DirectX
> 

The cause of this crash is known ( https://github.com/coop-deluxe/sm64coopdx/issues/101 ) and I expect it to be patched in the next game update.

A hotfix can be issued by changing the bytes in `sm64coopdx.exe` file with a free hex editor (like "HxD"):
- `set_window_title`
  - file offset: `(Hex) 212E50`
  - change byte `48` to `C3`
- `reset_window_title`
  - file offset: `(Hex) 212E60`
  - change byte `48` to `C3`

---

As for the green lines, looks like the problem happens with "Intel HD Graphics" (integrated GPUs) and malfunctioning "OpenGL" drivers, but I cannot reproduce it on my end.

**Comment by Oika64** [comment]
> > > Compile with DirectX
> > 
> > 
> > what happens is... the game crashes constantly with DirectX
> 
> The cause of this crash is known ( #101 ) and I expect it to be patched in the next game update.
> 
> A hotfix can be issued by changing the bytes in `sm64coopdx.exe` file with a free hex editor (like "HxD"):
> 
> * `set_window_title`
>   
>   * file offset: `(Hex) 212E50`
>   * change byte `48` to `C3`
> * `reset_window_title`
>   
>   * file offset: `(Hex) 212E60`
>   * change byte `48` to `C3`
> 
> As for the green lines, looks like the problem happens with "Intel HD Graphics" (integrated GPUs) and malfunctioning "OpenGL" drivers, but I cannot reproduce it on my end.

Thank you very much, I went to the official Intel website and downloaded the drivers (Intel® Processor Graphics from 7th to 10th Generation - Windows*) to do a clean installation so the game compiled in OpenGL worked for me.

![image](https://github.com/coop-deluxe/sm64coopdx/assets/164689226/d702027d-3d53-421e-b15c-ad90a6f9df3f)
