### ISSUE TITLE
Lost Connection after update to 0.2 

### ISSUE THREAD

**Issue by AlexBasura** [coop-deluxe/sm64coopdx#115]
i was playing with my pal and the game kick me from his server

now the game dont works with CoopNet i can play local but the other stuff like multiplayer no works 

![imagen](https://github.com/coop-deluxe/coopdx-patcher/assets/134896436/3c2e501a-db5e-4dae-b895-765c7f677e84)

**Comment by AlexBasura** [comment]
> i was playing with my pal and the game kick me from his server
> 
> now the game dont works with CoopNet i can play local but the other stuff like multiplayer no works
> 
> ![imagen](https://private-user-images.githubusercontent.com/134896436/318235762-3c2e501a-db5e-4dae-b895-765c7f677e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDI1MTEsIm5iZiI6MTcxMTk0MjIxMSwicGF0aCI6Ii8xMzQ4OTY0MzYvMzE4MjM1NzYyLTNjMmU1MDFhLWRiNWUtNGRhZS1iODk1LTc2NWM3ZjY3N2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMzMwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzVlNzNkNzZiNzMyMTAyNGEyZWEwOWI1NWFkMjI1NzAzODExMTMwNmFlODQxZTUwZDA4ZWU1NGIyZjk0ZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yF-65cPmClxxvE5tnu1Gr9hGJuEFYn-rk0NZqUpVpXM)

btw i tried to disable windows defender, recompile, my internet works fine, and i am not banned

**Comment by uuphoria2** [comment]
> > i was playing with my pal and the game kick me from his server
> > now the game dont works with CoopNet i can play local but the other stuff like multiplayer no works
> > ![imagen](https://private-user-images.githubusercontent.com/134896436/318235762-3c2e501a-db5e-4dae-b895-765c7f677e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDI1MTEsIm5iZiI6MTcxMTk0MjIxMSwicGF0aCI6Ii8xMzQ4OTY0MzYvMzE4MjM1NzYyLTNjMmU1MDFhLWRiNWUtNGRhZS1iODk1LTc2NWM3ZjY3N2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMzMwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzVlNzNkNzZiNzMyMTAyNGEyZWEwOWI1NWFkMjI1NzAzODExMTMwNmFlODQxZTUwZDA4ZWU1NGIyZjk0ZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yF-65cPmClxxvE5tnu1Gr9hGJuEFYn-rk0NZqUpVpXM)
> 
> btw i tried to disable windows defender, recompile, my internet works fine, and i am not banned

I dont have this issue right now Try playing again like maybe coopnet servers could've been down

**Comment by AlexBasura** [comment]
> > > i was playing with my pal and the game kick me from his server
> > > now the game dont works with CoopNet i can play local but the other stuff like multiplayer no works
> > > ![imagen](https://private-user-images.githubusercontent.com/134896436/318235762-3c2e501a-db5e-4dae-b895-765c7f677e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDI1MTEsIm5iZiI6MTcxMTk0MjIxMSwicGF0aCI6Ii8xMzQ4OTY0MzYvMzE4MjM1NzYyLTNjMmU1MDFhLWRiNWUtNGRhZS1iODk1LTc2NWM3ZjY3N2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMzMwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzVlNzNkNzZiNzMyMTAyNGEyZWEwOWI1NWFkMjI1NzAzODExMTMwNmFlODQxZTUwZDA4ZWU1NGIyZjk0ZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yF-65cPmClxxvE5tnu1Gr9hGJuEFYn-rk0NZqUpVpXM)
> > 
> > 
> > btw i tried to disable windows defender, recompile, my internet works fine, and i am not banned
> 
> I dont have this issue right now Try playing again like maybe coopnet servers could've been down

your idea dont work but ty to response :D

**Comment by AlexBasura** [comment]
k i was trying to repair the game and i can join to ONE server
but i enter to the castle door and i got this

![imagen](https://github.com/coop-deluxe/sm64coopdx/assets/134896436/0a83decf-1894-4a42-9ee6-33d1687132c0)

**Comment by AlexBasura** [comment]
> k i was trying to repair the game and i can join to ONE server but i enter to the castle door and i got this
> 
> ![imagen](https://private-user-images.githubusercontent.com/134896436/319018300-0a83decf-1894-4a42-9ee6-33d1687132c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTM5MzIsIm5iZiI6MTcxMjExMzYzMiwicGF0aCI6Ii8xMzQ4OTY0MzYvMzE5MDE4MzAwLTBhODNkZWNmLTE4OTQtNGE0Mi05ZWU2LTMzZDE2ODcxMzJjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwMzA3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjk2NmE0NmU2MWY2MDAxNjY4MzIwMDYzYjRhZjIxYjE4NzNiM2UxYjA1MzU4NmIzM2I2OWQzNDY4MDdjYWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CS1JMG1LZuZbPnc6IRSsK3T6B3szwzWA7FueshdMWR0)

and the game still dont work

**Comment by Flower35** [comment]
> k i was trying to repair the game and i can join to ONE server but i enter to the castle door and i got this
> 

Hi, looks like you are somehow losing the connection to "CoopNet" while you are changing the level (if that crash did not happen, you would see a suitable pop-up message like **`"Lost connection to CoopNet!"`**).

The crash itself was already reported and will be patched in the next update ( https://github.com/coop-deluxe/sm64coopdx/issues/98 ).

---

You can also check if the connection to "CoopNet" is not blocked (by firewall or something else) using the **Windows Command Line**:
```
> curl --verbose net.coop64.us:34197 & pause
```

*Example output:*
```
*   Trying 157.230.236.16:34197...
* Connected to net.coop64.us (157.230.236.16) port 34197
> GET / HTTP/1.1
> Host: net.coop64.us:34197
> User-Agent: curl/8.4.0
> Accept: */*
>
* Received HTTP/0.9 when not allowed
* Closing connection
curl: (1) Received HTTP/0.9 when not allowed
Press any key to continue . . .
```

Or, pasting **`net.coop64.us:34197`** into the address bar of your web browser, you should get:

```
ERR_INVALID_HTTP_RESPONSE
```

which means the game server is at least reachable, instead the error code would be:

```
ERR_CONNECTION_TIMED_OUT
```

**Comment by AlexBasura** [comment]
> > k i was trying to repair the game and i can join to ONE server but i enter to the castle door and i got this
> 
> Hi, looks like you are somehow losing the connection to "CoopNet" while you are changing the level (if that crash did not happen, you would see a suitable pop-up message like **`"Lost connection to CoopNet!"`**).
> 
> The crash itself was already reported and will be patched in the next update ( #98 ).
> 
> You can also check if the connection to "CoopNet" is not blocked (by firewall or something else) using the **Windows Command Line**:
> 
> ```
> > curl --verbose net.coop64.us:34197 & pause
> ```
> 
> _Example output:_
> 
> ```
> *   Trying 157.230.236.16:34197...
> * Connected to net.coop64.us (157.230.236.16) port 34197
> > GET / HTTP/1.1
> > Host: net.coop64.us:34197
> > User-Agent: curl/8.4.0
> > Accept: */*
> >
> * Received HTTP/0.9 when not allowed
> * Closing connection
> curl: (1) Received HTTP/0.9 when not allowed
> Press any key to continue . . .
> ```
> 
> Or, pasting **`net.coop64.us:34197`** into the address bar of your web browser, you should get:
> 
> ```
> ERR_INVALID_HTTP_RESPONSE
> ```
> 
> which means the game server is at least reachable, instead the error code would be:
> 
> ```
> ERR_CONNECTION_TIMED_OUT
> ```

i got the 2nd 
![imagen](https://github.com/coop-deluxe/sm64coopdx/assets/134896436/b6cecfd7-6083-4f7f-8cec-0ec1e1420f4e)

**Comment by AlexBasura** [comment]
> > > k i was trying to repair the game and i can join to ONE server but i enter to the castle door and i got this
> > 
> > 
> > Hi, looks like you are somehow losing the connection to "CoopNet" while you are changing the level (if that crash did not happen, you would see a suitable pop-up message like **`"Lost connection to CoopNet!"`**).
> > The crash itself was already reported and will be patched in the next update ( #98 ).
> > You can also check if the connection to "CoopNet" is not blocked (by firewall or something else) using the **Windows Command Line**:
> > ```
> > > curl --verbose net.coop64.us:34197 & pause
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Example output:_
> > ```
> > *   Trying 157.230.236.16:34197...
> > * Connected to net.coop64.us (157.230.236.16) port 34197
> > > GET / HTTP/1.1
> > > Host: net.coop64.us:34197
> > > User-Agent: curl/8.4.0
> > > Accept: */*
> > >
> > * Received HTTP/0.9 when not allowed
> > * Closing connection
> > curl: (1) Received HTTP/0.9 when not allowed
> > Press any key to continue . . .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or, pasting **`net.coop64.us:34197`** into the address bar of your web browser, you should get:
> > ```
> > ERR_INVALID_HTTP_RESPONSE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which means the game server is at least reachable, instead the error code would be:
> > ```
> > ERR_CONNECTION_TIMED_OUT
> > ```
> 
> i got the 2nd ![imagen](https://private-user-images.githubusercontent.com/134896436/319388311-b6cecfd7-6083-4f7f-8cec-0ec1e1420f4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODYyNjMsIm5iZiI6MTcxMjE4NTk2MywicGF0aCI6Ii8xMzQ4OTY0MzYvMzE5Mzg4MzExLWI2Y2VjZmQ3LTYwODMtNGY3Zi04Y2VjLTBlYzFlMTQyMGY0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMzEyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjcwMDVhZWY0ZTc1YmExODM4NTQ0NjI1MThkNzUxY2QyMGMxOGMwMjc0YTc5NTU1OTQ3ZDVlN2NhMWU0OTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VD3V3tKsp_mZEzgAQWZMIowIxQJug4UvBctdav_cj9g)

HTTP Request timeout

**Comment by AlexBasura** [comment]
k idk how but i compile the game using the cmd and now it works maybe the installer for me is broken idk but straight to the point the game works btw ty guys for response :DD
![imagen](https://github.com/coop-deluxe/sm64coopdx/assets/134896436/385613c4-c780-4db7-9c32-9bd04f2dc768)

**Comment by AlexBasura** [comment]
k dont take much prority about this error but my game again is dead 
i got this error when i was playing flood expanded and i got crash i restart the game and i got this
![imagen](https://github.com/coop-deluxe/sm64coopdx/assets/134896436/2eb8cb3c-60da-4589-8d17-01bc62e683c9)

**Comment by Agent-11** [comment]
CoopNet servers have been confirmed to have problems keeping up with the amount of players on them. We are working to host more servers to relieve stress on the servers.
However, if you did anything bannable then you may also be banned.

**Comment by AlexBasura** [comment]
> CoopNet servers have been confirmed to have problems keeping up with the amount of players on them. We are working to host more servers to relieve stress on the servers. However, if you did anything bannable then you may also be banned.

for some mods i have permission to host but for some reasons i host that mods in private servers
btw thanks for response

**Comment by AlexBasura** [comment]
some idea to make the game works again at least for one month or week

**Comment by AgentXLP** [comment]
CoopNet servers have been upgraded.
