### ISSUE TITLE
Will sm64coopdx have Android support?

### ISSUE THREAD

**Issue by realzoeygreen** [coop-deluxe/sm64coopdx#117]
I asked the question privately from Agent X and he didn't help, this is a genuine question I'm interested in because this is the best version of coop so far. I love the work the whole coopdx team did I just don't like how Agent X handled my question so I'm asking here on Github to get a better answer

**And Agent X if your reading this, I'm not mad I know you don't like me but I just wanna say great work you and your team did, the game compiles so fast and it's super easy to setup, exactly as advertised on the website. I hope this project grows and becomes successful. I wish you good luck even if you don't exactly like me at all.**

**Comment by eros71-dev** [comment]
We don't really have any plans to port the game to Android so far, there's still a lot to fix and polish currently, and it's not really a priority, nor we have anyone with enough experience to make a proper, fully functional port for Android. I hope that answers your question for now :)

If we ever get the chance to work on one, we'll most likely announce it everywhere suitable.

**Comment by realzoeygreen** [comment]
> We don't really have any plans to port the game to Android so far, there's still a lot to fix and polish currently, and it's not really a priority, nor we have anyone with enough experience to make a proper, fully functional port for Android. I hope that answers your question for now :)
> 
> If we ever get the chance to work on one, we'll most likely announce it everywhere suitable.

Thank you so much for the answer and I understand, Hopefully things get polished and fixed and the team grows and get experience with Android development, I wish all of you the best of luck and I love coopdx

**Comment by eros71-dev** [comment]
Please keep in mind that the android port by robertkirkman is not developed by us, and we don't know exactly how compatible or performant it is, so we can't recommend it as of right now. 

Although you're free to use it, if you want, of course, but we won't be able to give people support for it.
