### ISSUE TITLE
GCN Controller C-stick Y axis Stuck inverted

### ISSUE THREAD

**Issue by DefaultMiserable** [coop-deluxe/sm64coopdx#119]
I use a gamecube controller with an adapter, and normally I use a third party controller emulation program with co-op. But, SM64DX will not recognize the program as a controller, and it will actually let me use the GCN controller by itself without the program, which would be a good thing. But, for some reason the camera controls are stuck inverted on the Y axis. Not even turning on and off the setting does anything. The X axis works perfectly fine. Also works normally with xbox controller.

Mayflash GCN Controller Adapter
First party GCN controller
Windows 10
Running latest version of game

**Comment by Agent-11** [comment]
I see, well I would use the controller emulation program for the time being because the update is probably going to take a while.
