### ISSUE TITLE
Problems with DirectX (11?)

### ISSUE THREAD

**Issue by ER1CKS** [coop-deluxe/sm64coopdx#120]
There are two issues with DirectX that do not happen with OpenGL

one, the tab feature on the chat that mentions players, can only mention one player, and not everyone

the second, sm64coopdx crashes when leaving your hosted game, rehosting, disconnecting from someone elses, all crashes

**Comment by Paradox9955** [comment]
The second one is known. Not sure what the first one is exactly...

**Comment by Agent-11** [comment]
Weird
