### ISSUE TITLE
`mod_storage_load` returns empty string

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#122]
I'm assuming this bug only exists on macOS. It happens for both arm and intel.

`mod_storage_load` seems to be returning an empty string, and I can't seem to figure out why. It seems to be removing all the data on the return line, as logging the return value right before it returns the loaded string gives out the right return value. The number and bool loads are broken because of this as well, since they use `mod_storage_load`, which is broken. That also tells me that the problem isn't in the autogen code, since in the c++ file it's also broken. Saving data works perfectly fine.

**Comment by Isaac0-dev** [comment]
i fixed that in the next update. it was because it was trying to push freed memory to Lua
