### ISSUE TITLE
issue patching roms

### ISSUE THREAD

**Issue by emmoishere** [coop-deluxe/sm64coopdx#123]
was not sure if this was the right place to put it but whenever i try and open roms, i get this error and it boots me out of the patcher. can anybody help me?

![image](https://github.com/coop-deluxe/sm64coopdx/assets/160978041/4d5d511e-05d8-4eab-9ec6-cda581d03e5b)

**Comment by Paradox9955** [comment]
Access to the path is denied. Try removing the special characters and the spaces from the ROM (I'm not sure if the patcher allows that. I know msys2 doesn't.)

**Comment by emmoishere** [comment]
> Access to the path is denied. Try removing the special characters and the spaces from the ROM (I'm not sure if the patcher allows that. I know msys2 doesn't.)

still gives the error for some reason. what is msys2?

**Comment by Agent-11** [comment]
You should post this on the coopdx-patcher GitHub issues page instead.

**Comment by emmoishere** [comment]
Just checked my email today, I did not know that was a thing. My apologies!
