### ISSUE TITLE
[suggestion] Hook for Object vs Object / Player vs Object

### ISSUE THREAD

**Issue by Hex4dec** [coop-deluxe/sm64coopdx#125]
I'm creating a mod that requires these hooks, and it seems like there doesn't exist any. (I've also tried looking through interact hooks, they're too inconsistent)

**Comment by Hex4dec** [comment]
I'm pretty sure the best place to hook into is `interact_unknown_08` in `interaction.c`? I'm not entirely sure.

**Comment by Hex4dec** [comment]
I'm not exactly sure how I missed this, but I could just add a hook to `attack_object`, and `bounce_back_from_attack`. The previous function was for object vs player.

**Comment by Agent-11** [comment]
The next update is being developed on a private repo. I'm not sure how I would handle transferring your PR to there. Can I just copy your code and commit you as a co-author?

**Comment by Hex4dec** [comment]
Sure! Be careful with changing the `attack_object` signature, though.

**Comment by Agent-11** [comment]
Alright
