### ISSUE TITLE
[Feature Request] More save-slots and the ability to name them.

### ISSUE THREAD

**Issue by BackThrowTheBaguetteBrawler** [coop-deluxe/sm64coopdx#129]
I feel like having more save slots would make it easier to manage multiple playthroughs of various different romhacks and labeling them would allow people to see which save pertains to which playthrough.

**Comment by Agent-11** [comment]
Adding to the next update

**Comment by JohnTravolski** [comment]
I don't know how many slots were available at the time the original request was made, but I'm enjoying quite a few different rom hacks right now and I would appreciate more than 4 total slots.

Also, is there an easy way to back up / export and import different save files? If you don't want to add more slots, maybe it would be good to make it easy to switch some save files in and out.
