### ISSUE TITLE
Headless server does not compile with current codebase and does not attach to port

### ISSUE THREAD

**Issue by sappykun** [coop-deluxe/sm64coopdx#131]
**Describe the bug**

1. On the current version of the repo (`30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4` at the time of writing), the application does not compile with `HEADLESS=1` without modifying the source code. Modifications I used: [patch.txt](https://github.com/coop-deluxe/sm64coopdx/files/15182699/patch.txt)
2. When compiled with said modifications, the server does not seem to attach to a port and is not joinable. The program processes textures and actors, and writes to the configuration file, but does not go any further according to the console output.

**To Reproduce**

1. Follow the instructions in the README for downloading dependencies and cloning the repo.
2. When compiling the software, prepend `HEADLESS=1`  to your `make` command.
3. You will run into the following compilation error:
```
src/pc/crash_handler.c:745:45: error: 'gDjuiRoot' undeclared (first use in this function)
  745 |         if (id == (s64)gPcDebug.tags[14]) { gDjuiRoot = NULL; }
      |                                             ^~~~~~~~~
```

To resolve this, add `#include "pc/djui/djui.h"` to the top of the file.

4. Compile again. This, time, the error will be:

```
/usr/bin/ld: build/us_pc/src/pc/lua/smlua_hooks.o: in function `lua_profiler_start_counter':
/home/sm64/sm64coopdx/src/pc/lua/smlua_hooks.c:36: undefined reference to `SDL_GetPerformanceFrequency'
/usr/bin/ld: /home/sm64/sm64coopdx/src/pc/lua/smlua_hooks.c:37: undefined reference to `SDL_GetPerformanceCounter'
/usr/bin/ld: build/us_pc/src/pc/lua/smlua_hooks.o: in function `lua_profiler_stop_counter':
/home/sm64/sm64coopdx/src/pc/lua/smlua_hooks.c:47: undefined reference to `SDL_GetPerformanceFrequency'
/usr/bin/ld: /home/sm64/sm64coopdx/src/pc/lua/smlua_hooks.c:48: undefined reference to `SDL_GetPerformanceCounter'
```
To "fix" this (get it to compile), apply the supplied patch file (or wrap anything referencing the lua profiler in `src/pc/lua/smlua_hooks.c` with `#ifndef WAPI_DUMMY` blocks).

5. Compile again. The application will build successfully.
6. Run the application with `--server 7777`. You will get console output regarding processing game data, but the server then hangs. The server never attaches to a port as shown by `lsof -i`, and it is not possible to connect to it.

**Expected behavior**

For the server to attach to a port and be accessible. I was able to build the server successfully with previous versions of sm64ex-coop.
I have verified that the chosen port is open and accessible on my server.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04.4 LTS, Windows

**Additional context**

This occurs when compiling the program on both Ubuntu 22.04.4 and Windows. On Windows, I am unable to connect to the server via locahost, and it doesn't seem to attach to a port there either.

**Comment by Agent-11** [comment]
This will be fixed in the next update, thank you 👍

**Comment by Isaac0-dev** [comment]
this has been fixed for a while on our private dev repo
