### ISSUE TITLE
4:3 with RESOLUTION_DJUI jank

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#133]
When rendering hud elements using screenWidth, the value's are wrong for both 0 and `djui_hud_get_screen_width`

The former, the value being wrong for 0, I do know the cause of. In `djui_hud_position_translate`, you can see:

```
if (sResolution == RESOLUTION_DJUI) {
      djui_gfx_position_translate(x, y);
} else {
    *x = gfx_dimensions_rect_from_left_edge(0) + *x;
    *y = SCREEN_HEIGHT - *y;
}
```
Notice how only the djui resolution uses a different function. The lower line works fine, because `gfx_dimensions_rect_from_left_edge` returns the correct value when using 4:3.  Head into that gfx position translate function, and add `#include "src/game/hud.c"` into the include directory, the reason being is that on line 154:

`*x = GFX_DIMENSIONS_FROM_LEFT_EDGE(0) + *x * ((f32)SCREEN_HEIGHT / (f32)windowHeight) * djui_gfx_get_scale();`

This is using `GFX_DIMENSIONS_FROM_LEFT_EDGE`, not `gfx_dimensions_rect_from_left_edge`.  So by replacing that, the left side is fixed, and renders as intended.

For the right, I'm yet to find the cause. What I do know is the problem is from `djui_hud_get_screen_width` getting the right edge from `gfx_dimensions_rect_from_right_edge`, however from testing this is not returning the right value. Also, see how this is only called if the resolution isn't set to n64 (I haven't tested it on other font resolutions that arent djui). The exact place I believe it to be failing is `SCREEN_WIDTH - v` in the `gfx_dimensions_rect_from_right_edge` function, `SCREEN_WIDTH` and `GFX_DIMENSIONS_RECT_FROM_RIGHT_EDGE` are only 2 digits apart from my testing (`GFX_DIMENSIONS_RECT_FROM_RIGHT_EDGE` being 352, and `SCREEN_WIDTH` being 350), which I don't believe is correct. I haven't come up with a solution for this case, however I have a feeling it's a bit more involved.

A workaround for the time being is for modders simply use `RESOLUTION_N64`.

(Forgot to mention this isn't exclusive to dx, it's for both coop and dx)

**Comment by Agent-11** [comment]
Part of me just wants to remove Forced 4:3 and either reprogram it or just not bother with it again.

**Comment by AgentXLP** [comment]
Handled in the merger update
