### ISSUE TITLE
Issue compiling sm64coopdx on Linux, missing curl.h

### ISSUE THREAD

**Issue by Vinnyboiler** [coop-deluxe/sm64coopdx#134]
**Describe the bug**
I am unable to build sm64coopdx in Linux as I am getting this error:
`src/pc/update_checker.c:6:10: fatal error: curl/curl.h: No such file or directory
    6 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1405: build/us_pc/src/pc/update_checker.o] Error 1
`

**To Reproduce**
1. git clone https://github.com/coop-deluxe/sm64coopdx.git
2. cd sm64coopdx
3. sudo apt install build-essential git python3 libglew-dev libsdl2-dev libz-dev

**Expected behavior**
I was expecting to compile sm64coopdx for Linux

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64 
 - Browser Firefox

**Comment by AgentXLP** [comment]
Install libcurl: `sudo apt install libcurl4-openssl-dev`

**Comment by Vinnyboiler** [comment]
Thank You. I was able to resolve my issue.
