### ISSUE TITLE
determine_interaction return value doesn't feel right when bouncing on enemies

### ISSUE THREAD

**Issue by Fripouney** [coop-deluxe/sm64coopdx#135]
## Description :
When creating my mod I needed to detect when a player attacks an enemy. The `determine_interaction` function returns 0 when Mario doesn't do any action when interacting with the enemy.
However, the function also returns 0 when Mario bounces on the enemy to kill it, which feels weird and makes it harder to detect this type of interaction.

## Expected behaviour : 
`determine_interaction` maybe shouldn't return 0 when bouncing on an enemy

EDIT : After more testing, the correct return value for this function when bouncing on an enemy should probably be 64.
This would allow bitwise operations like `determine_interaction() & INT_HIT_FROM_ABOVE`, or `determine_interaction & INT_ANY_ATTACK` to work properly and return the values they should in this case.

**Comment by Hex4dec** [comment]
Yes, this is a known bug, use my patch at #126

**Comment by AgentXLP** [comment]
I guess this should be resolved now then.
