### ISSUE TITLE
[Feature Request] Allow you to import mods someone else is hosting

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#137]
Say, someone is hosting with MarioHunt, and you've been playing it, and you'd like to download that mod. Instead of going in the modding site and finding the mod, you could import the mod, since it already has been downloaded off the other client. Mods would be required to put a tag in in order for this feature to work, in order to prevent people from using this for unreleased mods. 

A unfortunately pretty big problem with this idea is someone could edit a mod, and when you import that mod, the mod will say, give them admin powers in any server you host (muting players, and other not so good stuff).

**Comment by AgentXLP** [comment]
I don't think this one is possible without a lot of effort. When a mod is imported I'm fairly certain it refreshes every mod that's loaded. Since the mods are being executed as it's refreshed, I imagine something very funky would happen, maybe a crash, or some kind of corruption.
