### ISSUE TITLE
Mods with hex codes don’t get sorted alphabetically 

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#139]
Technically, they do, however not to what you would expect. Mods with a backslash as the first character currently sit at the last spot they can possibly be in. A fix would be to strip the hex from the string when doing sorting, that way it can be sorted as expected.

**Comment by AgentXLP** [comment]
I see

**Comment by AgentXLP** [comment]
Sorry, meant to close this as solved, will be adding this to v1.1
