### ISSUE TITLE
Romhack Camera

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#141]
Simply add romhack camera (romhack camera is basically vanillia camera but doesnt get stuck on objects and almost always has 8 directional camera movement)

**Comment by AgentXLP** [comment]
Rom hack camera is already existent and in rom hacks.

**Comment by TheMan6900** [comment]
This would be toggleable camera mode (like freecam c-up is)

**Comment by TheMan6900** [comment]
read the post again,  meant to say something completely different.

**Comment by AgentXLP** [comment]
I see now
