### ISSUE TITLE
I Cant connect Coopnet servers

### ISSUE THREAD

**Issue by AlexBasura** [coop-deluxe/sm64coopdx#144]
**Describe the bug**
I cant join to coopnet servers

**To Reproduce**
1. Go to 'Any server'
2. Wait the game crashes 
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 26100 insider preview
 - Browser Firefox
 - Version 0.2

**Additional context**
My coopnet connection no works so i try to connect Via cmd but i got the error Revc (56) 
The connection was reset btw i tried with firefox and other browsers

![image](https://github.com/coop-deluxe/sm64coopdx/assets/134896436/133d49df-2498-4880-a1fb-57b42b6664d5)

**Comment by dave41413** [comment]
did you fix this?
