### ISSUE TITLE
`mod_storage_save` wiping save file

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#147]
I have not found a minimally reproducible example, and I do not understand why this happens. I have found a reproducible example however, although it's pretty convoluted. I've uploaded a video showcasing the bug.

https://github.com/coop-deluxe/sm64coopdx/assets/86802223/e67924a6-1ac9-4b7f-aeab-a44f34d91669

(pardon crappy video quality, had to compress it to 10 megabytes)

Ignore the crash, that's actually the mod doing it's job, and looking at the logs, it's doing what it's meant to. Just before the crash is when the save file was wiped.

Here is a portion of the save files, before and after

Before:
<img width="515" alt="Screenshot 2024-05-27 at 11 15 27 AM" src="https://github.com/coop-deluxe/sm64coopdx/assets/86802223/cedf20b9-415f-44e0-9623-fac2ab491b5f">

After:
<img width="515" alt="Screenshot 2024-05-27 at 11 15 30 AM" src="https://github.com/coop-deluxe/sm64coopdx/assets/86802223/9d6fcc52-d86d-460d-a85e-690d0fd34c31">

In the mod I'm using here, I'm saving a lot of stuff in 1 frame. I'm saving exactly 11 keys all in the span of a single frame (this is responsible for saving stats), maybe that's related to it?

Weirdly, it only happens with tournaments on, which only affects 2 things for this thing, 1. the text is changed to `Tournament Leaderboards in x` instead of `Voting in x`, and 2, more importantly, it saves to this key `stats_global_totalTournamentPoints`. Simply creating a mod saving and loading into that key doesn't really accomplish anything however.

This bug does NOT occur with the older ex-coop's saving method, so as a workaround I've copied the `mod_storage_save` code from there to DX.

**Comment by AgentXLP** [comment]
?!
