### ISSUE TITLE
Compatibility toggle can't be selected with controller

### ISSUE THREAD

**Issue by kermeow** [coop-deluxe/sm64coopdx#148]
**Describe the bug**
In the Join menu, using a controller skips over the sm64ex-coop Compatibility toggle going straight from Direct Connection to the Back button. The same applies if you use the arrow keys.
Really minor issue, really annoying when I'm on a laptop.

**To Reproduce**
1. Connect a controller (or use the arrow keys)
2. Select Join
3. Go down 2 times
4. Go down again, checkbox is skipped

**Expected behavior**
The checkbox should be the next thing selected after Direct Connection.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/46307433/28a3c023-6234-40d2-8c2e-5340a9a6b4ff)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/46307433/8e0dd13a-def4-40ca-97d3-7d129f40c972)

**Additional context**
This only happens in the Join menu.

**Comment by AgentXLP** [comment]
Coop compatibility will be removed next update.
