### ISSUE TITLE
I can't download it.

### ISSUE THREAD

**Issue by kingthememer** [coop-deluxe/sm64coopdx#15]
I'm not sure if this is very common or not, but the patcher doesn't seem to work for me.

I downloaded it like usual, dragged in my copy of SM64, and it seemed to be working fine for the most part but I kept getting a ton of failed download messages. I thought it was just a WiFi issue (ive been usin my moms mobile data for like 2 years 💀) so I left it running in the background.

I came back after like an hour, but only a couple DLL files had actually downloaded.
I was tryna download this in my D drive but someone suggested to use my C drive instead, which sounded fine, but when I dragged in my rom, I got an error message saying that the patcher was some kind of virus (not one of those colored box messages where you can just say "run anyway" it was like a full window).

 - OS: Windows 10
 - Browser: Opera GX
 - Version: the patcher link in the readme, idk the version

**Comment by kingthememer** [comment]
also i know its probably a false positive but some people might think its a real virus and they might shittalk coop dx

**Comment by SonicDarkYT** [comment]
It is a false positive, you'll have to wait some days because we need some time to organize stuff and figure out the issue, thanks for reporting it!

**Comment by kingthememer** [comment]
np

**Comment by Agent-11** [comment]
Fixed in the next version
