### ISSUE TITLE
Piranha Plant's Hitbox Is Completely Inaccurate to Every Other Version of the Game

### ISSUE THREAD

**Issue by sher-b** [coop-deluxe/sm64coopdx#150]
To put it simply, piranha plant hitboxes are just inaccurate to what it's meant to be. In Excoop/Coopdx, the hitbox is much smaller in comparison to the sm64-ex fork, alongside these versions:
N64
Emulator
sm64-port-master
sm64-ex

**How to Replicate**
There really isn't much you need to do to reproduce this. Open up EXCoop/CoopDX and create a vanilla server. Collect enough stars to enter Whomp's Fortress and walk to the piranha plant near the grey stairs. Using the bricks in the ground, attempt to kill the piranha plant from two bricks away. It will not work. 

Then open up any other version of SM64 and follow the same steps as before. You will bounce on the piranha plant from two bricks away if you follow it correctly. 

What's meant to happen is pretty clear from the replication steps. You're meant to easily kill the piranha plant from much further than you normally can in both coop versions. There really isn't much to this.

**Visual Proof**
Here are some screenshots taken on the first frame of impact to better exemplify what I mean:

These are screenshots taken on N64, Emulator, and PC Port respectively.
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171748633/33d8e1b6-e64b-46bc-9d9c-3776f0f1fa0e)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171748633/392f63f8-aa27-46fe-b485-10479fc3e2c7)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171748633/82cb929d-5b29-4e14-8d1b-7e8aaefacd3a)

And this is a screenshot from EXCoop and CoopDX respectively.
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171748633/56dad75e-a10d-45b4-84af-07b165853663)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171748633/b30cfd0f-49cd-4779-8977-56cd1d62ebb0)

Videos will be attached to show proper gameplay if it wasn't already obvious. Emulator and EXCoop will be attached in the same video as this was what was provided on the discord server.

**The order of videos goes as follows: N64, PC Port, EXCoop/Emulator, CoopDX**

https://github.com/coop-deluxe/sm64coopdx/assets/171748633/edba33ab-067f-4edb-8991-70cb7e3681be
https://github.com/coop-deluxe/sm64coopdx/assets/171748633/debcb80f-ebc9-46ad-9592-f9f8dc5c3b7a
https://github.com/coop-deluxe/sm64coopdx/assets/171748633/170d4ca9-9f33-4e63-af2f-7d7414c999c4
https://github.com/coop-deluxe/sm64coopdx/assets/171748633/5e1e35f5-5c00-4bbb-8197-88fcf4e04349

**Why This Should Be Fixed Rather Than Ignored**
Although this may not seem like an issue, romhacks (especially ones ported to coop) do rely on the original properties of the piranha plant to make certain parts possible. Some examples are:

King Boo's Revenge X
Super Mario 74 Extreme Extraordinary Extravaganza Empurpled Eellogofusciouhipoppokunurious Edition

It may seem harmless on a surface casual level, but dive into the different ways to play SM64 and the differences slowly start to creep up. It's also the one attribute that is somehow different from every other version tested.  There is no reason why this bug should stay in the game because it alters the experience for other players and can sometimes ruin them entirely.

I genuinely hope it will be fixed in the upcoming merge with both coop versions, since both coop verisons have had this problem and it has never been addressed until now.

**Comment by AgentXLP** [comment]
I'm sorry to say this but, I feel like you're making a way bigger deal out of this than it actually is...
Of course we are going to fix it when the time comes, but it's low priority as of now. There are larger things that need to be added or fixed, but I will try to look into this when I can. Here is an explanation from a developer about it though:
> That's probably due to the way dj synchronized a lot of sm64 behaviors, it's always updating the closest Mario, sometimes discarding the distance that would have otherwise been recorded by `oDistanceToMario`.
This is the same thing that happened to many other objects, some have been fixed but others still have the bug, such as the fish, birds, butterflies and probably more.

**Comment by sher-b** [comment]
im glad its at least acknowledged
