### ISSUE TITLE
[Feature Request] `HOOK_ON_INIT`

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#151]
This hook would be called when the mod is initialized. The closest thing we have to this is `HOOK_JOINED_GAME`, however that's not called on the server. This would be great for communicating with other mods apis without using `HOOK_ON_LEVEL_INIT` with a "has this been done already" variable.

**Comment by Isaac0-dev** [comment]
`HOOK_ON_PLAYER_CONNECTED` is called for the host as well, serving as `HOOK_JOINED_GAME` for the host.
but you only need to do this if you need to wait until **all** mods are loaded, or for the network is loaded.
you can still run code in the Lua script without any hooks, all code run during that time is _during_ mod initialization. and if you need it to be directly after, add your code to the end of your mod, in the lowest alphabetically ordered file.
```lua
local function on_all_mods_loaded(m)
    if m and m.playerIndex ~= 0 then return end
    -- all mods are loaded!
end
if network_is_server() then
    hook_event(HOOK_ON_PLAYER_CONNECTED, on_all_mods_loaded)
else
    hook_event(HOOK_JOINED_GAME, on_all_mods_loaded)
end
```

**Comment by EmeraldLoc** [comment]
I had not realized this, this is def more clean than using `HOOK_ON_LEVEL_INIT`, thanks a lot!

I'll close this then, since this does accomplish the goal I was asking for, ty!

**Comment by AgentXLP** [comment]
thanks Isaac!

**Comment by AgentXLP** [comment]
I will be taking this code and never crediting you for this breakthrough.

**Comment by AgentXLP** [comment]
*evil laugh*

**Comment by Isaac0-dev** [comment]
> I will be taking this code and never crediting you for this breakthrough.

lol go ahead

**Comment by AgentXLP** [comment]
nah I'm kidding, this is really useful though! If I use this in a mod I'll likely put "Special thanks to Isaac" at the bottom of the description.
