### ISSUE TITLE
DX Toad Model Bug

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#152]
Hello! So I wanted to report an oddity I saw with the DX Toad Model. I was working on some custom stages, and when I booted some of them up with Toad, his head was all white, which isn't normal. I've captured some screenshots so I can show you evidence.

Here, the Ex toad model loads just fine:
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171458695/42b9d5b2-4385-4b14-a745-3a7f0d5ea938)

Here, the glitched DX Toad model loads into the level:
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171458695/f609cb7c-93cd-4054-8e28-d451145f7c9a)

Also for some reason, if there are two toads in the level, one of the toads will remain glitched, while the other one will show up just fine.
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171458695/1b09f6e5-d5f0-4746-aff3-fc4c20864593) 

This was a very weird bug for me so I wanted to report it here. I love the DX Toad Model and I don't think it should necessarily be removed.

**Comment by FluffaMario** [comment]
I'm thinking this has something to do with transparency, I might need to change Toad's cap to be alpha clipped instead of translucent like I had originally planned for it since there's no way to blend two player colors on one texture yet...

**Comment by Bear64DX** [comment]
Oh, okay. Thank you for acknowledging this report. I really appreciate it 👍
