### ISSUE TITLE
Hex Code Issue

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#154]
I've found out that hex codes can screw up the mod list on a server. I'm pretty sure this happens because the game is trying to load a hex code with other mods on? I'm not entirely sure what causes it, but here's an example I made by loading a ton of mods (and a mod that has a hex code)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171458695/21dfacaa-1661-4bd7-acf6-64ec13fd52f7)

**Comment by dave41413** [comment]
This happens to me too

**Comment by AgentXLP** [comment]
Moral of the story, don't put hex codes in your mod name I guess
