### ISSUE TITLE
readme error(?)

### ISSUE THREAD

**Issue by FallBackITA27** [coop-deluxe/sm64coopdx#155]
the readme says to clone the ex coop version for arm macos.

**Comment by AgentXLP** [comment]
The README is outdated, there is now a [Wiki](https://github.com/coop-deluxe/sm64coopdx/wiki). When sm64coopdx v1.0 releases, the README will be updated to remove compilation instructions.

**Comment by FallBackITA27** [comment]
I would add a warning then - in the past days several people I know have been having issues compiling the game due to this not being signaled anywhere.
