### ISSUE TITLE
HEADLESS=1 flag fails compilation

### ISSUE THREAD

**Issue by FallBackITA27** [coop-deluxe/sm64coopdx#156]
**Describe the bug**
Read title

**To Reproduce**
run `make HEADLESS=1`

**Desktop:**
 - OS: Fedora Linux 40
 - Version: Latest Main Branch

make fails with the following log
```
src/pc/crash_handler.c: In function 'crash_handler_init':
src/pc/crash_handler.c:745:45: error: 'gDjuiRoot' undeclared (first use in this function)
  745 |         if (id == (s64)gPcDebug.tags[14]) { gDjuiRoot = NULL; }
      |                                             ^~~~~~~~~
src/pc/crash_handler.c:745:45: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:1406: build/us_pc/src/pc/crash_handler.o] Error 1
make: *** Waiting for unfinished jobs....
```

This makes absolutely no sense, as
```C
#ifndef OSX_BUILD
        if (id == (s64)gPcDebug.tags[14]) { gDjuiRoot = NULL; }
#endif
```
The line is wrapped by another preproc flag, which defaults to 0.
I took a look at the makefile but sadly I don't code in C and couldn't make much of it.

**Comment by AgentXLP** [comment]
Fixed in sm64coopdx v1.0
You can just remove that line BTW, it was a debug thing with DJUI
