### ISSUE TITLE
Oddities with OMM Rebirth

### ISSUE THREAD

**Issue by EmilyEmmi** [coop-deluxe/sm64coopdx#16]
**Describe the bug**
Several issues occur when using OMM Rebirth 1.2. From what I've found:
- The HUD does not render at all, even if enabled (this includes the "You Got A Star!" text)
- Unknown script errors occur while talking to an NPC or reading a sign

**To Reproduce**
1. Enable OMM Rebirth 1.2
2. Enables "Odyssey" or "Vanishing" for the HUD (does not do anything)
3. Read a sign. Script error appears.
4. Collect a star in "Odyssey" mode. No text shows up.

**Expected behavior**
The HUD displays, and the script error does not occur.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/77174187/0794d5be-fe1c-453e-bf50-43835b6b01a1)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/77174187/7655fee8-b1ca-415f-8b7d-a911748510b5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v36.1

**Additional context**
I think the HUD bug actually relates to HOOK_ON_HUD_RENDER_BEHIND, because /omm and /stars work as intended, and I haven't had any issues with other mods that use the HUD. Perhaps the script error bug is also related, but I'm not really sure.

**Comment by Agent-11** [comment]
I will be asking Peachy for the uncompiled OMM mod so I can fix this.

**Comment by PeachyPeachSM64** [comment]
@EmilyEmmi 
Issue has been identified and a silent fix has been pushed (no version change).
Please download omm-coop.zip again to get the up-to-date version: https://github.com/PeachyPeachSM64/sm64ex-omm/raw/coop/omm-coop.zip
