### ISSUE TITLE
Unban request

### ISSUE THREAD

**Issue by ImaLionlol** [coop-deluxe/sm64coopdx#160]
Hello! Well, so as the title says, I would like to get another chance to play this amazing game. I knlw I made a mistake and I shouldnt said that word but I promise to change and never do something similar again. I apologize for what I done. Sorry is this isnt the correct place to make this, if not, pls message me. And If I dont get unbanned, I will accept my consecuences for my actions.

**Comment by SMG964** [comment]
unban me

**Comment by SMG964** [comment]
im no longer underaged
