### ISSUE TITLE
I was killing a server after making folder mod changes and then coop died for no reason

### ISSUE THREAD

**Issue by Bloxxel64** [coop-deluxe/sm64coopdx#161]
**Describe the bug**
I moved some things from a lua file to the main file as it was a folder mod,
deleted the empty file
exited the server to rehost so coop would stfu about missing files
crash

**To Reproduce**
i have no idea

**Expected behavior**
not...crash?

**Screenshots**
the mod was enabled when i closed the server
![Screenshot at 2024-07-01 22-44-31](https://github.com/coop-deluxe/sm64coopdx/assets/70494679/3c76fdd9-56a3-4a4d-9da0-e421d1b7cbf8)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser firefox
 - Version 1.0 :sob:

**Comment by AgentXLP** [comment]
Seems unrelated, when you delete a mod file you need to restart or refresh since the game only counts the files and keeps track of them in those events.

**Comment by Bloxxel64** [comment]
![Screenshot at 2024-07-03 18-15-12](https://github.com/coop-deluxe/sm64coopdx/assets/70494679/45447323-1826-4b8f-bf2b-825b87d84aa4)

update, happened again, so it really is unrelated

**Comment by AgentXLP** [comment]
People keep having this problem but I can't seem to ever reproduce it, can you send me your `sm64config.txt` file on Discord?
