### ISSUE TITLE
Can't open/compile macOS sm64coopdx

### ISSUE THREAD

**Issue by smallrobuxman** [coop-deluxe/sm64coopdx#165]
im on sonoma 14.5 and see this whenever i try opening sm64coopdx
![image](https://github.com/coop-deluxe/sm64coopdx/assets/80533565/ccafe61f-2568-4a2a-8962-8a5eae580162)

**Comment by AgentXLP** [comment]
@EmeraldLoc uh oh

**Comment by EmeraldLoc** [comment]
This is probably cause I'm on a beta version of macOS, so it was compiled for that version... I'll see what I can do, may have to create a vm to compile it properly.

**Comment by AgentXLP** [comment]
That's a lot of effort, I commend you

**Comment by EmeraldLoc** [comment]
[sm64coopdx.dmg.zip](https://github.com/user-attachments/files/16073073/sm64coopdx.dmg.zip)

This does not contain any mods since i had to get the filesize below 45, can you see if this works for you?

**Comment by smallrobuxman** [comment]
well this time theres no compatibility issue, but i get this error: 
![image](https://github.com/coop-deluxe/sm64coopdx/assets/80533565/1d1741b1-7dc0-4344-a3b5-ea72ea0f115f)

**Comment by EmeraldLoc** [comment]
Alr, good to know. I'll have to do the VM strat then.

**Comment by EmeraldLoc** [comment]
[sm64coopdx_test.dmg.zip](https://github.com/user-attachments/files/16075171/sm64coopdx_test.dmg.zip)

Reran with slightly different make configuration, didn't get any linking warnings during compilation, so this may just work.

**Comment by smallrobuxman** [comment]
I got the same error

**Comment by EmeraldLoc** [comment]
It'll probably be a while before I get the VM set up, so in the meantime, you can compile the dev branch of DX to build, however you will have to manually move the mods, palettes, dynos, and lang folders into the Resources folder, I still have to get that worked out.

**Comment by smallrobuxman** [comment]
Alright, ill try doing that one tomorrow

**Comment by EmeraldLoc** [comment]
Seems like the error is an oversight. To fix it temporarily, you can get hombrew and run `brew install glew sdl2`, in the meantime I'll be editing the makefile, or whatever else I need to edit, to pack these files in.

**Comment by supahfox** [comment]
Does sm64coopdx store copyrighted assets in .app or in another folder? I would share my build in the meantime

**Comment by AgentXLP** [comment]
It doesn't have copyrighted assets

**Comment by EmeraldLoc** [comment]
Alr, I believe I got it worked out. The problem was glew and sdl2 weren't packed with the executable. Once I did this, I just had to change where the exec was looking for the libs, and now each lib is packed. Once again, this doesn't contain any mods to get it below the 25 mb limit. Lmk if this works :D

[sm64coopdx.dmg.zip](https://github.com/user-attachments/files/16092026/sm64coopdx.dmg.zip)

**Comment by AbnormalPoof** [comment]
Can confirm it functions!
![Screenshot 2024-07-04 at 12 06 38 PM](https://github.com/coop-deluxe/sm64coopdx/assets/86753001/0d2bac06-9a53-4cad-9f59-d9b067c20246)

**Comment by EmeraldLoc** [comment]
Awesome! Did you run it with glew and sdl2 uninstalled from brew? It should still launch without those deps installed.

**Comment by AbnormalPoof** [comment]
Initially, no, but I just removed glew and sdl2 from brew and it still seems to run!
![Screenshot 2024-07-04 at 12 24 27 PM](https://github.com/coop-deluxe/sm64coopdx/assets/86753001/90058fb8-b982-48db-b92d-3d312360a963)
![Screenshot 2024-07-04 at 12 24 38 PM](https://github.com/coop-deluxe/sm64coopdx/assets/86753001/7419344e-68b3-4ca4-897a-610399e8374e)

**Comment by EmeraldLoc** [comment]
Awesome! Will send these changes to Agent X so he can get them on the dev branch, ty for testing!

**Comment by Maghni09** [comment]
for my case it says the file is damaged move to trash, can anyone help with that?

**Comment by EmeraldLoc** [comment]
Yea, we're still getting the build updated. In the meantime, you can compile the repo manually, or use the dmg file I gave above, although note that doesn't come with any mods.

**Comment by Maghni09** [comment]
i know it seems a stupid a question but i dont know how to compile on mac i only did it once with a tutorial, can you please send a good tutuorial to compile it, that would be very helpful. thank you
also to note i have a mac m1 max is it fine or should it be intel?

**Comment by EmeraldLoc** [comment]
Nah it's fine. Yea the m1 max will be great for this!

So, firstly, [download the build with macos fixed here](https://github.com/EmeraldLoc/sm64coopdx/archive/refs/heads/main.zip). Next thing is go into your downloads folder, and unzip `sm64coopdx-main`. Next, open up the terminal, and, assuming you haven't renamed any file, run `cd ~/Downloads/sm64coopdx-main`. Now, if you don't have homebrew installed, install it [here](https://brew.sh/). Next, run:

`brew install make mingw-w64 gcc sdl2 pkg-config glew glfw3 libusb audiofile coreutils`

With these packages installed, you should be good to go! So, get your SM64 Rom, rename it to `baserom.us.z64`, and drag it into the `sm64coopdx-main` folder in your Downloads folder. With that done, head back into your terminal, and run `gmake OSX_BUILD=1 -j`. Once that finished, open up finder, head to `sm64coopdx-main`, open up the build folder, then us_pc folder, and the .app should be there!
