### ISSUE TITLE
My coop hates coopnet, how ironic.

### ISSUE THREAD

**Issue by Bloxxel64** [coop-deluxe/sm64coopdx#167]
**Describe the bug**
I have no idea why, but whenever I try to host with coopnet, the game opens the server with Direct Connect, for no reason.

I just had it happen, on a vanilla lobby.

![Screenshot at 2024-07-03 17-47-47](https://github.com/coop-deluxe/sm64coopdx/assets/70494679/13878375-c69b-47e7-8c5c-51c9a1f630f9)
Server Settings on the main menu.

![Screenshot at 2024-07-03 17-47-59](https://github.com/coop-deluxe/sm64coopdx/assets/70494679/69c8e470-02bb-4f9d-8c9c-7c11f5968170)
Server settings after hosting.

I'm going to see if gbd provides any insight, but i doubt it.

**To Reproduce**
Hell if i know.

**Expected behavior**
The game would host on coopnet.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Firefox
 - Version 1.0

**Comment by AgentXLP** [comment]
Set your max players higher than 1

**Comment by Bloxxel64** [comment]
ouuugh that fixed it im a funcking dumbass

**Comment by AgentXLP** [comment]
its ok
