### ISSUE TITLE
Star Revenge 5 causes consistent crash with scrolling textures

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#169]
Don't know if this is a problem with the mod or, however the game shouldn't really crash because of it. Here's what lldb gave me:

<img width="569" alt="Screenshot 2024-07-03 at 9 37 29 PM" src="https://github.com/coop-deluxe/sm64coopdx/assets/86802223/056a159a-7462-4cdc-abab-4a6fd10e0ae9">

I don't get anywhere in the hack, the game crashes instantly.

**Comment by Bear64DX** [comment]
I'm starting to wonder if this applies to other romhacks as well. I've tested a ton, and some of them actually crash. I think it's due to these textures, since I don't remember the hacks breaking on the spot w/ 0.2.
