### ISSUE TITLE
Crash when loading some mods with a manual compile

### ISSUE THREAD

**Issue by somario360** [coop-deluxe/sm64coopdx#17]
**Describe the bug**
When attempting to run mods such as Gun Mod DX and Character Select on a manual compiled build (using the make command in MSYS2 MINGW64), the game will crash. I have attached a screenshot of the crash screen after loading Gun Mod DX.

**To Reproduce**
1. Go to 'Host'
2. Click on 'Mods & Gamemodes'
3. Select '.Gun Mod DX' or 'Character Select'
4. Click 'Host'
5. The crash will then occur.

**Expected behavior**
The mod loading without any issue.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/22121742/7c7e534b-c11f-4278-8a48-05edda987181)

**Desktop:**
 - OS: Windows 10 Version 10.0.19045 Build 19045
 - Version: commit [c6bda49](https://github.com/coop-deluxe/sm64coopdx/commit/c6bda4917c11fa4a03b47519b100a8b1ad0062bc) (latest at the time of reporting)

**Additional context**
This crash does not happen when using the coopdx-patcher, but I am using a manual compile due to making personal changes for my friend group. This crash still happens without any changes made however.

**Comment by Agent-11** [comment]
Fixed in the next version. This has to do with DynOS compression I believe.
