### ISSUE TITLE
Green Stars is "deprecated"

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#170]
So for some reason, when loading up the SM64: The Green Stars hack, you get these script warnings:
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171458695/25b40dac-8e99-4159-99bd-7d2e20482f7e)
Afaik, the game still functions properly, but the script warnings still appear. This might not be the highest priority of issues to fix, but I'd just like to get this out here.

**Comment by AgentXLP** [comment]
Thats not necessarily the game's fault.
Also, I'm making those warnings only show up once in the patch update.

**Comment by Isaac0-dev** [comment]
> Thats not necessarily the game's fault. Also, I'm making those warnings only show up once in the patch update.

thats the game's fault.

**Comment by AgentXLP** [comment]
Game isn't the one with the outdated code practice Isaac

**Comment by Isaac0-dev** [comment]
we should be focusing on mod compatibility, dx has changed things to make many many mods "deprecated".
furthermore, green stars is a popular mod, and this update has deprecated a bunch of popular mods
its dx's fault
