### ISSUE TITLE
Mario in the Dreamscape crashes on C2

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#171]
For some reason, entering C2 (Beach Oasis) in Mario in the Dreamscape crashes the game. I'm reporting it here because I believe this might be an issue with DX 1.0. This does not happen on older builds of DX.
![image](https://github.com/coop-deluxe/sm64coopdx/assets/171458695/c3c675e5-8f83-46e0-87ef-9b3d3c7fe8cd)

**Comment by AgentXLP** [comment]
Same issue as #169
