### ISSUE TITLE
Hosting does not listen on IPv6

### ISSUE THREAD

**Issue by RoddyDev** [coop-deluxe/sm64coopdx#172]
**Describe the bug**
Hosting servers using Direct Connection only listens on IPv4, making hosting private servers impossible for those on ISP's that does IPv4 CGNAT.

**To Reproduce**
1. On Main Menu, click on "Host"
2. Set "Network System" to "Direct Connection"
3. Start Hosting

**Expected behavior**
Hosting should listen to both IPv4 and IPv6, or making the user choose which protocol to use on the hosting menu, defaulting to dual-stack IPv4+IPv6

**Screenshots**
![listen](https://github.com/coop-deluxe/sm64coopdx/assets/45442056/5c4b5882-e7ab-442c-b2c2-f91983a43a97)

**Comment by dave41413** [comment]
I don't know if C can host on both UDP and TCP or IPv4 and IPv6

**Comment by theclashingfritz** [comment]
It is possible to support both IPv4 and IPv6 for hosting, We wouldn't support using TCP for doing so however as it would require a complete rework of the networking system.

**Comment by PaperVb64** [comment]
there's a fork with IPv6 support, try that out in the meantime. [https://github.com/theclashingfritz/sm64coopdx/tree/ipv6-hosting](https://github.com/theclashingfritz/sm64coopdx/tree/ipv6-hosting)
