### ISSUE TITLE
Server closed - Failed to connect to player "unknown" 

### ISSUE THREAD

**Issue by LuxDaWolf** [coop-deluxe/sm64coopdx#174]
Hi, my friend and i are trying to play together, we have the same version (1.0 or v37), same mario rom and everything, we even have the same NAT type. I dont understand whats happening.
![imagen_2024-07-04_232438287](https://github.com/coop-deluxe/sm64coopdx/assets/174748714/44459b0a-17bc-4781-a081-a26fce5b132a)
![imagen_2024-07-04_232510475](https://github.com/coop-deluxe/sm64coopdx/assets/174748714/c6746dcb-ed9c-4fdc-b8c9-d1ce5849ecdf)

**Comment by AgentXLP** [comment]
This is likely an issue with CoopNet itself, I was seeing if I could pitch and help with the servers.
