### ISSUE TITLE
Add hook to render after playerlist

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#175]
Currently, there's no hook, or any way, to render on top of the playerlist. Having a way to do this would allow modders to replace/edit the playerlist, which would come in handy for certain mods.

**Comment by AgentXLP** [comment]
@Isaac0-dev should we add it?

**Comment by Isaac0-dev** [comment]
mods just need to be able to:
- detect whether the button was pressed to trigger the player list
- disable the playerlist without disabling the above
