### ISSUE TITLE
CoopNet rules make you go to public lobbies when you host from upgrading to 0.7 to 1.0

### ISSUE THREAD

**Issue by dave41413** [coop-deluxe/sm64coopdx#177]
**Describe the bug**
CoopNet rules make you go to public lobbies when you host from upgrading to 0.7 to 1.0

**To Reproduce**
1. Upgrade from 0.7 to 1.0
2. Click on Host
3. Host a server
4. Coopnet Rules
5. Public Lobbies

**Expected behavior**
Coopnet rules then hosting

**Screenshots**

https://github.com/coop-deluxe/sm64coopdx/assets/162748837/6a024d89-e1bf-4251-9ba0-9e4903b217fe

(sorry for the horrible quality)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [..edge]
 - Version [coopdx 1.0]
idk wht else

**Comment by AgentXLP** [comment]
Fixed in the patch
