### ISSUE TITLE
Adding a mod then skipping it in Mods crashes the game

### ISSUE THREAD

**Issue by dave41413** [coop-deluxe/sm64coopdx#178]
**Describe the bug**

**To Reproduce**
1. Import mod
2. Skip mod by page (accidentally)
3. Freeze

**Expected behavior**
Game would load the page

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/162748837/b1d25ecc-2b7d-4497-b415-69812e81e0cd)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. edge]
 - Version [e.g. 1.0]

**Additional context**
I think this is fixed in the patch version?

**Comment by AgentXLP** [comment]
This isn't fixed in the patch actually, thank you for finding this
