### ISSUE TITLE
Disconnection after 2 min

### ISSUE THREAD

**Issue by GreatNateDev** [coop-deluxe/sm64coopdx#179]
**Describe the bug**
Title says it all
**To Reproduce**
1. Go to any server besides public ones 
2. Click on host
3. have a friend join
4. both players disconnect in less then 2 min with the error lost connection to coop servers

**Expected behavior**
not to disconnect

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: SteamOS for host and Windows 10 for friend
 - port forwarded? no we are playing via lan with the friend in question joining via the steamdecks local IP
 - Version 1.0

**Additional context**
This is our first time playing

**Comment by dave41413** [comment]
I'll try to reproduce this

**Comment by dave41413** [comment]
I can't reproduce this, it might be something with connection/internet

**Comment by dave41413** [comment]
Or the steam deck not working with local idk

**Comment by GreatNateDev** [comment]
it seems to be the windows 10 laptop which is odd because is mainly linux that gives me problems my desktop running ubuntu 24.04 and steam deck work fine but on the laptop both clients always get disconnected from coopnet honestly though it might just be the laptop its like 6 years old or something now and it runs for like 40min off charger lol
