### ISSUE TITLE
More Main Menu Stages

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#183]
I was thinking there could be some more stages for the Main Menu. Most of these are just areas of stages but I think they could be cool. These include:
- SSL (The Pyramid)
- LLL (The Volcano)
- SL (The Igloo)
- TOTWC
- VCUTM
- COTMC
- THI (Inside the cave)
- WDW (The town)
- DDD (The Sub)
- BITFS
- BITS

**Comment by Bear64DX** [comment]
> Not sure if we're going to add more levels, the main menu is already pretty janky as it is and adding more levels will probably break it more

I see. I just like the elements that are used in the Main Menu, so I thought it'd just be cool if I suggested something like this.

**Comment by AgentXLP** [comment]
Maybe in a future update we can add more levels, I just don't wanna risk causing more bugs.

**Comment by Isaac0-dev** [comment]
yeah this is a fair point, I stand by it. It's not very likely that there
would be any bugs, but better safe than sorry.
imo yeah it'd be fine to look into more levels later though
