### ISSUE TITLE
Custom menu background level/Positions

### ISSUE THREAD

**Issue by Flamarix** [coop-deluxe/sm64coopdx#187]
Basically, allow mods/players to :
- Make custom levels able to be displayed in the menu
- Allow custom positions on existing levels

How could it work ?
- Mod author need to have a file in it's mod which would set the positions/Orientation of mario in the menu screen
- The player could have an option to do it, either during gameplay (a menu button "Save coordinates", which would save both positions and orientation at once), or somes kind of freecam mode allowing them to set it.

As for which music the stage play...
- use the stage's music
- mod author need to specify it
- menu option to choose

It's purely cosmetic, but it would be a pretty neat feature in my opinion, let me know if you want more informations. (I would recommend messaging me on discord, flamarix)

Anyways, thanks for reading all of this, you're doing an amazing job on the game!

**Comment by dave41413** [comment]
You mean the menu at the start? Yeah that's a pretty good idea,.

**Comment by Flamarix** [comment]
Yep, I'm talking about that one.

**Comment by AgentXLP** [comment]
Sorry but storing saved coordinates (which can't be done through mods since they only run when you host) is not something I have interest in implementing, especially with how held together by duct tape the menu already is.
