### ISSUE TITLE
Third Issue with Compilation

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#193]
When trying to compile, 10 errors having to do with  compiling src/pc/djui/djui_panel_mod_menu.c show up
Expected to FINALLY COMPILE THIS

![Screen Shot 2024-07-10 at 11 26 38 AM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/e2c3d2df-0c3b-48da-87c1-705310c2f00e)

 - OS: Macos
 - Browser Chrome
 - Version 10.15.7
On intel and used Intel mac tutorial and this is the third error I've experienced.

**Comment by EmeraldLoc** [comment]
This was fixed in the dev repo. Copy that file from the dev repo to this one.

**Comment by ThePlayerRolo** [comment]
ok

**Comment by EmeraldLoc** [comment]
Must be a old compiler thing, make it this:

```
case MOD_MENU_ELEMENT_MAX: {
    break;
}
```

**Comment by EmeraldLoc** [comment]
The c file, replace `case MOD_MENU_ELEMENT_MAX:` with the stuff I gave, that should fix that.

**Comment by ThePlayerRolo** [comment]
New errors: 
![Screen Shot 2024-07-10 at 11 41 47 AM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/417a8bb5-da08-46aa-ac22-b14304a46aaf)
