### ISSUE TITLE
DJUI Compliation Issues.

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#194]
THe DJUI Mod Panel menu.c has compilation issues as in errors.

EXPECTED A COMPLETE COMPLIATION (I'm getting sick and tired of sending these out.)

![Screen Shot 2024-07-10 at 11 41 47 AM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/a865c40d-68c2-4b36-be83-05df5357b937)
 - OS: MacOS
 - Browser Chrome
 - Version 10.15.7
Intel Mac.

**Comment by AgentXLP** [comment]
Fixed in the dev branch, just use that if you want to compile please
If I'm wrong then I'll reopen this issue

**Comment by ThePlayerRolo** [comment]
I've tried using one part of it, I'll try compiling the full dev version tho.

**Comment by ThePlayerRolo** [comment]
so um those errors didn't appear but one in smlua_hooks.c appeared about case MOD_MENU_ELEMENT_MAX: being empty and I added a break; inside of it. is that ok?

**Comment by AgentXLP** [comment]
yeah

**Comment by ThePlayerRolo** [comment]
also um when it finished compiling it compiled into a macos 14.0 version. I'm on macos 10.15.7. what do I do?

**Comment by ThePlayerRolo** [comment]
oh wait I just needed to show application contents.

**Comment by ThePlayerRolo** [comment]
and click the executable

**Comment by ThePlayerRolo** [comment]
THANKS FOR EVERYTHING!
