### ISSUE TITLE
Not connecting Properly I think?

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#196]
Not properly connecting I think

Expected to fully join propelly

Os: Macos
Version 10.15.7
Browser: Chrome

**Additional context**
Compiled On an Intel Mac using the dev branch.

**Comment by ThePlayerRolo** [comment]
how it looks
![Uploading Screen Shot 2024-07-10 at 3.51.42 PM.png…]()

**Comment by AgentXLP** [comment]
You can only connect to lobbies on the same dev branch, just in case

**Comment by ThePlayerRolo** [comment]
um but when I do a private lobby with one of my friends who doesn't use the dev build it works?

**Comment by ThePlayerRolo** [comment]
when I host it

**Comment by AgentXLP** [comment]
It may work sometimes but I changed the `NetworkPlayer` struct so expect crashes with people on v1.0
Also, you are likely on an old commit since I bumped versions in a newer commit.

**Comment by ThePlayerRolo** [comment]
is there anyway to update the dev build on Macos Catlina?

**Comment by EmeraldLoc** [comment]
recompile

**Comment by ThePlayerRolo** [comment]
and also make it so public lobbies on dev build and main build to join properly?
