### ISSUE TITLE
Compiling Main Repository On MacOSX ends with  ld: library not found for -latomic clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#197]
as in title

Expected to Compile this version for better multiplayer connections.
![Screen Shot 2024-07-10 at 8 39 34 PM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/c20eb891-c502-4b3c-b351-b75162a8acf1)

OS: MACOS
VERSION: 10.15.7
BROWSER CHROME

Intel mac, already compiled dev version but want main version for proper public lobbie support

**Comment by EmeraldLoc** [comment]
In dev this is fixed. YOu can copy over the dev makefile into this one if you need it, otherwise wait for the patch to be released.

**Comment by AgentXLP** [comment]
You're opening tons of issues and I'm getting lots of notifications. Please just make **one** macOS compilations issue instead of making an issue for each individual problem.

**Comment by ThePlayerRolo** [comment]
ok
