### ISSUE TITLE
Game does not create executable file

### ISSUE THREAD

**Issue by WookisSRL** [coop-deluxe/sm64coopdx#20]
the patcher/compiler does not ask for a rom after the first time, and it creates the sm64coopdx folder without an executable in it.

**Comment by RocketPropelledGamer** [comment]
This is a known issue and there are a few ways people have managed to get around it while the problem persists.

1. Temporarily turn off Windows Defender/make an exclusion for the folder the patcher is in. Defender could be giving a false positive on the executable.
2. Run the patcher on a different drive.
3. Make your own executable by downloading the relevant patch file for your install of Windows, getting Floating IPS, patching the file onto your ROM, renaming your ROM to "sm64coopdx.exe" and putting it in the sm64coopdx folder w/ all the DLLs and resources.

Patch files:
sm64coopdx.com/download/sm64coopdx_Windows_32-bit.bps
sm64coopdx.com/download/sm64coopdx_Windows_64-bit.bps

**Comment by kingthememer** [comment]
> 3. Make your own executable by downloading the relevant patch file for your install of Windows, getting [Floating IPS](https://github.com/Alcaro/Flips), patching the file onto your ROM, saving your patched ROM as "sm64coopdx.exe" (make sure it's sm64coopdx.exe, not sm64coopdx.exe.z64, you _may_ have to change your folder settings to see the file extension if it's saved as a z64) and putting it in the sm64coopdx folder w/ all the DLLs and resources.

this is REALLY useful information ngl
this should be somewhere on the main page honestly

**Comment by Agent-11** [comment]
Fixed in the next version.
