### ISSUE TITLE
Online play issue

### ISSUE THREAD

**Issue by QingDonnieYoshi** [coop-deluxe/sm64coopdx#200]
Hey hope all is well. So some friends of mine are coming across an issue where whenever my friends would join my server not only does the server closes up the game itself crashes and closes. Is there a way to fix it?

**Comment by QingDonnieYoshi** [comment]
So update, one is able to join but now whenever I pause it the game crashes

**Comment by QingDonnieYoshi** [comment]
OK so I found the actual issue. It was Many Coop Skins mod that was causing the crashes.

**Comment by AgentXLP** [comment]
Please close issues when you solve them.
