### ISSUE TITLE
loading rom isn't working

### ISSUE THREAD

**Issue by beatrixwashere** [coop-deluxe/sm64coopdx#203]
**Describe the bug**
the executable and rom both work, but i can't load the rom, since dragging it into the window hasn't worked, and there's no file explorer popup to do so either. i also tried passing in the rom path as an argument, but still no luck.

**To Reproduce**
1. open the executable
2. try dragging in the rom

**Expected behavior**
i expected the game to start loading, or at least some kind of visual representation of the game actually loading.

**Screenshots**
not much i can do here sorry

**Desktop (please complete the following information):**
 - OS: debian 12 (on a chromebook, which is probably the main issue); i also tried downloading the windows version and running it through wine but nothing changed
 - Browser: chrome
 - Version: v1.0

**Additional context**
either i'm stupid or this just doesn't work for me

**Comment by Isaac0-dev** [comment]
go to which ever of these directories that exists, and paste your rom into the folder and call it `baserom.us.z64`:
- `~/.local/share/sm64ex-coop`
- `~/.local/share/sm64coopdx`

**Comment by beatrixwashere** [comment]
meant to say something about this earlier but i tried this and it worked, tysm!

**Comment by DeciduousArcher** [comment]
Doing this seems to do nothing for me, it still shows me this image every time I try to drop the file.

![Image](https://github.com/user-attachments/assets/373c001d-d7c5-4edb-a720-275d21faa304)
