### ISSUE TITLE
the billboarding does not turn off automatically

### ISSUE THREAD

**Issue by Sntiagosos** [coop-deluxe/sm64coopdx#204]
**Describe the bug**
so.... when i use and dynOS whit 3D trees for example it looks horrible cause the tree is still following the camera even if is 3D soo im asking if you can make an manually option for disable billboards or just tell me how i fix it

**To Reproduce**
1. turn on the dynOS whit the 3D stuff
2. go to game and you will see it

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox

**Additional context**
oh and the coins work fine for some reason, but the 1up mushroms the trees and everything else have the bug

**Comment by AgentXLP** [comment]
Was this an issue in sm64ex-coop?

**Comment by Sntiagosos** [comment]
> Was this an issue in sm64ex-coop?

nope.

**Comment by AgentXLP** [comment]
Hmm.

**Comment by Sntiagosos** [comment]
oh and just in case im using Vanilla 96

**Comment by AgentXLP** [comment]
Can you send the DynOS pack?

**Comment by Aruru-Heat** [comment]
> Can you send the DynOS pack?
Here, there's two repos, one for the models, and another for the textures:

https://github.com/Render96/ModelPack/releases/tag/3.2
https://github.com/pokeheadroom/RENDER96-HD-TEXTURE-PACK/releases/tag/1.2.1

I thought that maybe, a .lua mod could be made, but I really lack the knowledge or if it's possible.
