### ISSUE TITLE
Lua console output cuts off paths early

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#207]
It would be cool if the script warnings told you what file and line is deprecated. It just tells you what function is deprecated, which isn't that useful because you basically have to dig your way through code just to find where the function is. Currently from what I see, the script warnings don't tell you what file or line is deprecated, so having a way to view that would be neat. (also im not exactly a coder so maybe im wrong lol)

**Comment by AgentXLP** [comment]
You used to but changes were made to how paths work and as a result there's an annoying 3 dot cut off now. I'll try and fix this when I get the chance.
