### ISSUE TITLE
Possible TMP Anticheat

### ISSUE THREAD

**Issue by Bear64DX** [coop-deluxe/sm64coopdx#210]
Was thinking there could be something you could put in mods, called `-- tmp: off`. This would make it so the folder wouldn't be stored in the tmp folder (rip mod cache).

**Comment by AgentXLP** [comment]
Put [WIP] (WIP) in the mod name

**Comment by Bear64DX** [comment]
> Put [WIP] or (WIP) in the mod name

GENIUS
