### ISSUE TITLE
(Modding Issues) My h and c files for models for mods  won't compile into .bins

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#211]
Whenever I export an armature  in blender through fast64 for mods and then open the game to compile the files into .bins, it just doesn't.

Expected to compile the h and c files into .bin for modding

OS: MacOs
Browser: Chrome
Version 10.15.7
Intel mac, posted this also on the fourms to try to get you guys to see this. Also I open Sm64coopdx using the unix excutable bc the application itself is 14.0 or later but I can still open the exctuable itself.

**Comment by ThePlayerRolo** [comment]
Figured out what i was doing wrong

**Comment by LividJava** [comment]
Hey, Having this issue as well. Can you tell me what you did to fix it?

**Comment by ThePlayerRolo** [comment]
> Hey, Having this issue as well. Can you tell me what you did to fix it?

um this was so long ago I kinda forgot.

You can ask in coop central though, they can help: https://discord.gg/TJVKHS4

**Comment by LividJava** [comment]
For those who come after, fast64 blender add-on wasn't compatible with the DYNOS, i had to downgrade from blender 5.0 to 4.2 and download Fast64-Gart and export it through there
