### ISSUE TITLE
Ukrainian language

### ISSUE THREAD

**Issue by EkafReN** [coop-deluxe/sm64coopdx#222]
I made itLhttps://drive.google.com/file/d/1TXdmeBGY3wbRD_6k-KZtySyiASXBdQU_/view?usp=sharing

**Comment by EkafReN** [comment]
> I made itLhttps://drive.google.com/file/d/1TXdmeBGY3wbRD_6k-KZtySyiASXBdQU_/view?usp=sharing

**Comment by dave41413** [comment]
For that to work they would have to add ukrainian font
im pretty sreure

**Comment by dave41413** [comment]
Nvm i actually works 🍡
