### ISSUE TITLE
OpenGL Fatal Error, program does not launch with 16x Anti-Aliasing

### ISSUE THREAD

**Issue by FakeSalamander** [coop-deluxe/sm64coopdx#225]
**Describe the bug**
When the program is launched, rather than any window opening, the following error message is given instead:
```
Fatal Error

OpenGL 2.1+ is required.
Reported version: 0.0
```

**To Reproduce**
1. Go to sm64coopdx folder
2. Launch `sm64coopdx` executable
3. See error.

**Expected behavior**
The program launches without any error message.

**Desktop (please complete the following information):**
 - OS: CachyOS
- sm64coopdx version: 1.0.1
- OpenGL version: 4.6

**Additional context**
I have OpenGL 4.6 installed, so I'm unsure as to why the program detected "0.0" instead.

**Comment by AgentXLP** [comment]
I got this same thing before, try backing up your configfile somewhere else and see if launching the game with fresh settings works

**Comment by FakeSalamander** [comment]
That fixed it! Thank you very much. I did some testing, and it seems **Anti-Aliasing** is the culprit. Anything up to 8x works fine, but setting AA to 16x is what causes this error.

**Comment by AgentXLP** [comment]
Fixed on my machine, although I'm not at my computer so I can't push the commit atm. Thank you for reporting this.

**Comment by vsTerminus** [comment]
This is still affecting me. Turning Anti-Aliasing to x16 throws the OpenGL error and the game refuses to load.

Changing `msaa 16` to `msaa 8` in `sm64config.txt` lets the game load again.

Gentoo Linux, compiled today on `main` branch. (Most recent commit is from Saturday Jan 11)

**Comment by yobson1** [comment]
Same problem, also fixed by changing it to 8 in the config file to get it to launch again.
