### ISSUE TITLE
Allow mods to add navigation in the Mod Menu

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#230]
Didn't quite know what to call it. Pretty much want mods to be able to create buttons that take you to a new list of options, with a back button placed automatically. Would be handy for mods with a lot of settings

**Comment by Blockyyy** [comment]
thats already a feature..

**Comment by EmeraldLoc** [comment]
I know about the initial page, however from there is there a method to create more pages of settings? I haven’t found a way to do this, so if this does exist, how do you do this?

**Comment by Blockyyy** [comment]
ah i see, i don't think theres a way to do that other than have too many settings before it goes to another page

**Comment by AgentXLP** [comment]
Yeah it just wraps to the next page, I will probably add `hook_mod_menu_label` next update so you can have text labels to improve how your menu looks.
