### ISSUE TITLE
sf2/soundfont support

### ISSUE THREAD

**Issue by insertnameuserhere** [coop-deluxe/sm64coopdx#231]
[soundfont - wikipedia](https://en.wikipedia.org/wiki/SoundFont)

and yes this needs midi support as well to even implement sf2/soundfonts into the game

**Comment by Isaac0-dev** [comment]
...whats the issue?

**Comment by insertnameuserhere** [comment]
yes

**Comment by frog8412** [comment]
> i need soundfonts & midi formats in the game (in order 2 have it work implement midi & sf2 formats to the game)

i would love midis with sfs like sf2 or sfz but the game uses m64 sequence files, and only with the sm64 soundbanks
