### ISSUE TITLE
What is this new update?

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#232]
Update Screenshot:
![Screen Shot 2024-07-20 at 12 53 55 PM](https://github.com/user-attachments/assets/c06ade91-83cb-4f6f-aa40-cef3aa9bfb6c)

- OS: Macos
 - Browser Chrome
 - Version 10.15.7

Intel Mac

**Comment by AgentXLP** [comment]
The server is currently under maintenance, there isn't an update

**Comment by ThePlayerRolo** [comment]
oh ok is that why the mod fourms are updating?

**Comment by AgentXLP** [comment]
Yes

**Comment by yoyeet961** [comment]
I love the <!DOCTYPE html> update
