### ISSUE TITLE
[No-Issue]Question about emscripten/js port?

### ISSUE THREAD

**Issue by futurepr0n** [coop-deluxe/sm64coopdx#237]
Has anyone attempted one? Is there any chance it being possible to develop? Couldn't find a developer discord, only a general players one. Was hoping to connect with some devs to chat

**Comment by MlopsFunny** [comment]
Dont say that again.

**Comment by futurepr0n** [comment]
Any particular reason why it's a sensitive topic? Sorry couldn't find any readme or faq about it. Is this only intended ever for these 3 platforms then no iOS, android etc

**Comment by Paradox9955** [comment]
The development team don't plan on making an emscripten port. So if someone wanted that, they would have to do it themselves. Also, I wouldn't call it a sensitive topic. I remember someone asking AgentX for help on making it themselves, and he helped them out, and seems like they were successful, it just didn't have mod or networking support

**Comment by futurepr0n** [comment]
I've come across the emscripten/js single player port but it has a wasm file that contains pretty much I guess the rom. This project I think would be significantly different to rewrite for it, but I thought it would be neat if at least you could have a client that could connect to one of the native platforms server/hosted games. I'm not asking the devs to do it, but would be a neat port idea to try my hand at. Nice to know some of the devs have shared and some ppl have pursued - maybe if I have something that i need help with I'll be able to seek them out here then. Thx
