### ISSUE TITLE
Options/Camera/Invert X option doesn't function properly in most situations

### ISSUE THREAD

**Issue by Mariosonicman91** [coop-deluxe/sm64coopdx#241]
Options/Camera/Invert X option only applies to Lakitu Rom Hack camera.

Rom Hack camera is the 45-degree angle with low interpretation compared to base sm64 (at least, I'm pretty sure.)
And it only works with the lakitu camera, and sometimes, it doesn't work at all!

1. Host a Game with no Rom Hacks enabled
2. Head to Options/Camera and enable "Invert X"
3. Try to adjust the camera horizontally
4. Find that it is still panning the same way.

What is supposed to happen is that panning is supposed to head the opposite direction of the direction it heads when the option is disabled.

Context:
 - OS: Windows 11 Enterprise
 - Version: 10.0.22000 Build 22000
 - Controller: Officially Licensed Nintendo Pro Controller

Additional Context:
I assume this also applies the invert Y, but I haven't tested it.

**Comment by AgentXLP** [comment]
The invert settings are for free cam
