### ISSUE TITLE
Controller does not work on Debian 12

### ISSUE THREAD

**Issue by Vulpovile** [coop-deluxe/sm64coopdx#242]
**Describe the bug**
Controllers do not work on Debian 12

**To Reproduce**
1. Plug in a controller
2. It does not work

**Expected behavior**
The controller should work

**Desktop (please complete the following information):**
 - OS: Debian 12

**Comment by robertkirkman** [comment]
SDL2 could be described as a kind of "driver" that gives the game compatibility with controllers especially recently manufactured controllers. Currently the app uses the system's SDL2 library and the SDL2 that Debian 12 usually has is a little bit older not really way too old but just a bit old, have you tried compiling a new build of SDL2 and testing the app with it, just to check whether that helps?

I understand that is really difficult and not easy for new users to do, but I'm making something that will help you test the game with a newer SDL2 version much more easily, it will just take a while to make.

**Comment by AgentXLP** [comment]
Yeah this isn't necessarily an issue with the game, feel free to keep talking in this issue though but I will close it
