### ISSUE TITLE
m.wallKickTimer in LUA doesn't seem to function properly

### ISSUE THREAD

**Issue by Mariosonicman91** [coop-deluxe/sm64coopdx#243]
I can't wallkick in a bonk state after setting m.wallKickTimer to 5

1. Use extended-moveset.lua sm64ex coop
2. Attempt to wall kick out of a hard bonk
3. See in code it sets m.wallKickTimer to 5
4. Cannot wall kick (unless frame perfect which still isn't the expected behavior)

You are supposed to be able to press A to wall kick in the allotted frames.

Context:

- OS: Windows 11 Enterprise
- Version: 10.0.22000 Build 22000
- Controller: Officially Licensed Nintendo Pro Controller

Am I using it incorrectly?

Don't burn me on using an old sm64ex coop mod it works just fine and uses the exact variable.

**Comment by AgentXLP** [comment]
m.wallKickTimer isn't a real field, it's a state extras field made by Extended Moveset, which means this is an issue with Extended Moveset.

**Comment by AgentXLP** [comment]
^ That above is a lie! I made a mistake while searching for the field to see if it existed since I didn't remember. My apologies.

**Comment by Mariosonicman91** [comment]
I knew it was too general sounding too be made by the mod. Thank you! Happy patching!

**Comment by AgentXLP** [comment]
I think this might be another case of doing something differently now than before and blaming it's non functionality on the 1.0 update.
If you can, please verify your code did indeed function properly before 1.0, I can't find anything that changed about the wallkick timer

**Comment by Mariosonicman91** [comment]
Okay

**Comment by AgentXLP** [comment]
How'd it go?

**Comment by Mariosonicman91** [comment]
Oh my gosh I totally forgot I'll get on it rn 💀

**Comment by Mariosonicman91** [comment]
I've been having some puter problems and got logged outta my github account sorry for replying so darn late.
One quick thing, how does one download sm64 ex coop? Not seein' any releases
