### ISSUE TITLE
Input lag on Windows Steam Deck

### ISSUE THREAD

**Issue by Papyrusty** [coop-deluxe/sm64coopdx#244]
I installed Windows 11 on my steam deck, and when I play Mario 64 Coop Deluxe, there's about a second of input lag when I'm playing, and I have no idea how to fix this. I've used both OpenGL, and DirectX, and the issue persists.

**Comment by frog8412** [comment]
why do you install windows 11 on your steam deck you could just use the normal linux version

**Comment by AgentXLP** [comment]
> why do you install windows 11 on your steam deck you could just use the normal linux version

I agree. There's not really much I can do about that, I've noticed the Steam Deck occasionally has problems with input lag (especially with Xbox controllers) so this is likely a case of that, especially knowing you installed an OS that wasn't designed to run on the device.
