### ISSUE TITLE
Not seeing an .exe file

### ISSUE THREAD

**Issue by SuperHackerManz64** [coop-deluxe/sm64coopdx#248]
I have deleted, redownloaded, downloaded different versions, and every time there is nothing executable. I know how to install after that point and have sm64 installed but i dont see anything titled "sm64-coop.exe" or whatever. I also have no idea if this is still active or if anyone will check this. But please help, comment if you need any more information too.

**Comment by EmeraldLoc** [comment]
Are you heading [here](https://github.com/coop-deluxe/sm64coopdx/releases/tag/v1.0.1), downloading the windows build, extracting the zip, and finding the .exe file? I was able to find it fine.

**Comment by SuperHackerManz64** [comment]
oh my god thank you, i think i might have downloaded like the code version or something? i should be able to get it working now though. Surprised this is still active also
