### ISSUE TITLE
Mods that come with the game are unenableable (is that even a word)

### ISSUE THREAD

**Issue by zacnmac** [coop-deluxe/sm64coopdx#25]
After making the game with the patcher, the Arena, Gun Mod, and Day and Night cycle are all restricted from turning on, even if I turn off all my mods and my rom hack (assuming I have a rom hack enabled)

1. Patch your rom with the game.
2. Open the game.
3. "Oh boy, I'm really looking forward to that gun mod!"
4. "what"
![image](https://github.com/coop-deluxe/sm64coopdx/assets/143913996/75a400aa-4385-4ce7-92af-7857a2d845ef)

 - Windows 11
 - Microsoft Edge
 - v0.1.1

I hope there's not a simple solution to this and it turns out I'm just stupid lol

**Comment by FluffaMario** [comment]
You need to turn of ex-coop compatibility to use coopdx-intended mods.

**Comment by zacnmac** [comment]
THERE WAS AN SIMPLE SOLUTION AND IM JUST STUPID NOOOOOOOOOOOOO (thank you)
![agony4](https://github.com/coop-deluxe/sm64coopdx/assets/143913996/5acd02ec-ea65-41c0-b496-d94474a9427c)
