### ISSUE TITLE
Xbox/Playstation Controller Support

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#250]
Have controller related stuff (keybinds) display with its actual controller button instead of the n64 (and the extra ones).
Would also be cool if other mods could take advantage of this too (ei api maybe).

**Comment by AgentXLP** [comment]
Xbox controllers already are fully supported. PlayStation and other brand controllers just don't have their own icons which is an issue I don't particularly have interest in doing anything about for the time being.
