### ISSUE TITLE
Ping/Desync Checker

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#251]
This would basically just check if someones ping is about lets say 300-500, and if they were, than it would try resyncing them.

**Comment by frog8412** [comment]
automatic reconnect to coopnet would be awesome too where the reconnect time raises the more it fails to connect and eventually stopping after a lot of tries

**Comment by AgentXLP** [comment]
> This would basically just check if someones ping is about lets say 300-500, and if they were, than it would try resyncing them.

How do you figure you 'resync' someone?

**Comment by TheMan6900** [comment]
Maybe by stopping any kinda online signals like player movement, and interactions, though itd probably also have to disable packets from being sent which might break certain mods so.

**Comment by AgentXLP** [comment]
Yeahhh some mods and the vanilla game itself would risk breaking in spots with that.
As a rule of thumb, I recommend only opening issues for things you would actively benefit from being added or fixed, like a bug with gameplay or a new smlua function.
