### ISSUE TITLE
Gamecube Controller won't show up on Linux

### ISSUE THREAD

**Issue by dldropper** [coop-deluxe/sm64coopdx#252]
what the title says, i am using a mayflash gamecube to usb adapter but it won't show up. works fine in dolphin, though.

OS: Endeavour OS

**Comment by AgentXLP** [comment]
Mayflash controllers just don't work well with SDL2 I guess. Not really much we can do about it as of now.

**Comment by Hri7566** [comment]
they worked fine on the original sm64ex-coop repo

**Comment by Hri7566** [comment]
there is a controller driver here: https://github.com/ToadKing/wii-u-gc-adapter
