### ISSUE TITLE
Display is green and Text almost impossible to read

### ISSUE THREAD

**Issue by ShadowVR2** [coop-deluxe/sm64coopdx#255]
Tried to access the emulator for the first time, but I'm stuck with the screen being green and distorted. Can barely read the text if at all. Game is still technically playable, or at least I can navigate the menus but the inability to read most text makes it difficult.

1. Go to extracted contents of 'sm64coopdx_v1.0.1_Windows_OpenGL'
2. Click on 'sm64coopdx'

**Expected behavior**
Game display to look normal.

![Screenshot 2024-07-30 114915](https://github.com/user-attachments/assets/857d985b-53d2-4422-ae85-f8966a05a754)
![Screenshot 2024-07-30 115212](https://github.com/user-attachments/assets/08c131fa-2256-4cfc-8be5-4a21ce9a3deb)

**Desktop (please complete the following information):**
 - OS: 
Edition	Windows 11 Home
Version	23H2
Installed on	‎3/‎8/‎2023
OS build	22631.3958
Experience	Windows Feature Experience Pack 1000.22700.1026.0
 - Browser: Opera GX

Being run on a Nitro AN515-55 Laptop that's a bit banged up (accidental dropping; still functions just fine if occasionally freezing, forgetting how to connect to wifi, etc). Unless laptops come with graphic cards upon purchase, I can safely assume I don't have one.

**Comment by EmeraldLoc** [comment]
Download the direct version instead.
