### ISSUE TITLE
It crashes when opened

### ISSUE THREAD

**Issue by Slimyiscool** [coop-deluxe/sm64coopdx#26]
**Describe the bug**
I run the program and it crashes i tried to give it admin and still did not work.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/146485896/e738fa6f-f444-433b-aad7-6161847f9386)

**Desktop**
 - OS: Windows 7
 - Browser Firefox

**Comment by Agent-11** [comment]
This is an issue with coopdx-patcher so it should technically go on the other repo, make sure you have a stable internet connection for it.

**Comment by Slimyiscool** [comment]
> This is an issue with coopdx-patcher so it should technically go on the other repo, make sure you have a stable internet connection for it.

I have good internet
do you know how fix it
