### ISSUE TITLE
Chatbox API

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#260]
This would let an ui element/or thing, have you type inside of it instead of having you, have to type a command, followed by text, within the chat menu, to put text inside of it.

**Comment by john123903** [comment]
Do you mean like minecraft when you type a command, and suggestions thinks of something you have been looking for, and you press TAB to go to the command?

**Comment by TheMan6900** [comment]
think of it something like this.

https://github.com/user-attachments/assets/aa6db8f7-e291-438e-9186-9679e582850a

**Comment by john123903** [comment]
ohhh i get it now. i dont know if the team can implement this, but nice idea though

**Comment by AgentXLP** [comment]
The HUD rendering version of DJUI is more primitive and unfortunately you can't render DJUI menu elements with it.
