### ISSUE TITLE
Why it does need Discord authorization?

### ISSUE THREAD

**Issue by M0REKZ** [coop-deluxe/sm64coopdx#261]
Hi, i have this question that i put on the title

Why it does need Discord authorization?

<img width="437" alt="screeen" src="https://github.com/user-attachments/assets/eb25c891-6120-42f6-ab60-9c8ce7bc115f">

**Comment by Paradox9955** [comment]
It's so you can send player invites, it can also useful when making mods where only you can do certain actions

**Comment by Paradox9955** [comment]
Also, it doesn't "need" it, you can click cancel to make it go away. Or you can compile manually and disable the discord sdk to stop it completely

**Comment by PaperVb64** [comment]
it's for the RPC (Rich Presence Client, AKA the thing that shows up on your profile when your listening to music or playing a game).
