### ISSUE TITLE
[Suggestion] Automatically reconnect to CoopNet

### ISSUE THREAD

**Issue by frog8412** [coop-deluxe/sm64coopdx#263]
So, I think having an automated reconnection will be useful, because it's frustrating when you're AFK and lose connection to CoopNet without realizing it.

In the lobby list, the game will reconnect after 3, 5, 10, 15, 30, 60 seconds and then ask the player whether they want to try again.
While hosting a lobby, it will reconnect in the same way that it does in the lobbies list: when it connects, it rehosts the lobby using the same settings.

**Comment by AgentXLP** [comment]
#272

**Comment by frog8412** [comment]
> #272

not really, this reconnects to CoopNet when you get Lost Connection/Could not connect to CoopNet

**Comment by AgentXLP** [comment]
I meant more that I was trying to merge the two issues together

**Comment by frog8412** [comment]
a, mb
