### ISSUE TITLE
bring back sex in minecraft mod

### ISSUE THREAD

**Issue by PaperVb64** [coop-deluxe/sm64coopdx#265]
Thanks to the older (pre 1.x versions) are basically unobtainable now, it'd be cool if you guys brought back the mod in some form, either a page on the mods site or the discord server or something.

**Comment by eros71-dev** [comment]
Oh RPG sent it as well, nice

**Comment by robertkirkman** [comment]
Please don't put this back in the game it's not appropriate for younger players

**Comment by Isaac0-dev** [comment]
it was agreed that this won't happen as one of the conditions of merging ex-coop and coopdx teams. 
i don't really care if it's uploaded in other places, just not built in
