### ISSUE TITLE
A way to straight up remove water from a level, via lua

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#267]
would once again benefit modes.

**Comment by Mechstreme** [comment]
```lua
-- sets any water/toxic gas levels to the floor lower limit (Y position -11100 by default) once the current area is synced

local minHeight = gLevelValues.floorLowerLimit
local i = 0

local function on_sync_valid()
    if get_water_level(0) <= minHeight then return end -- area has no water levels; cancel function

    i = 0
    repeat
        djui_chat_message_create("i: " .. i)
        set_water_level(i, minHeight, true)
        i = i + 1
    until get_water_level(i) <= minHeight
end

hook_event(HOOK_ON_SYNC_VALID, on_sync_valid)
```

this script can be used as a way to "remove" water by moving it to the bottom of the level, though this does affect toxic gas as well

**Comment by TheMan6900** [comment]
would look nicer to just removing the water, rather than moving it under the level, where you can jarringly see it under the map, when looking outta of oob.

**Comment by SonicandTailsCD** [comment]
> ```lua
> -- sets any water/toxic gas levels to the floor lower limit (Y position -11100 by default) once the current area is synced
> 
> local minHeight = gLevelValues.floorLowerLimit
> local i = 0
> 
> local function on_sync_valid()
>     if get_water_level(0) <= minHeight then return end -- area has no water levels; cancel function
> 
>     i = 0
>     repeat
>         djui_chat_message_create("i: " .. i)
>         set_water_level(i, minHeight, true)
>         i = i + 1
>     until get_water_level(i) <= minHeight
> end
> 
> hook_event(HOOK_ON_SYNC_VALID, on_sync_valid)
> ```
> 
> this script can be used as a way to "remove" water by moving it to the bottom of the level, though this does affect toxic gas as well

This isn't a good idea, as the water will still be rendered and will place more load on the GPU. The script is good - but not for old PCs.

> But Sonic, that isn't a problem with modern PCs.

True, but you know there are so many gamers (that includes me!) insist on using their old PCs. :/
(Sorry if this isn't relevant - I'm just trying to help! ^-^)

**Comment by AgentXLP** [comment]
There's not really a way to entirely get rid of the water that I know of, but you can move it very far down until you either can barely see it or can't see it at all anymore.
