### ISSUE TITLE
libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GoanimateFan** [coop-deluxe/sm64coopdx#268]
whenever i open the game it gives this error:

libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by Bloxxel64** [comment]
you need to give us actual info about your os so we can even help... isnt there a template for bug reports?

**Comment by GoanimateFan** [comment]
i'm running ubuntu

**Comment by GoanimateFan** [comment]
latest version

**Comment by robertkirkman** [comment]
It is probably a duplicate of #158

**Comment by GoanimateFan** [comment]
oh

**Comment by GoanimateFan** [comment]
and i dont have libSDL2-2.0.so.0
so idk how to fix that

**Comment by GoanimateFan** [comment]
> ```shell
> sudo apt install libsdl2-2.0-0
> ```

thanks for the command now its fixed!
