### ISSUE TITLE
Chat API

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#269]
This would simply let you edit the chat, just like you can with the playerlist next update

**Comment by AgentXLP** [comment]
In what ways?

**Comment by TheMan6900** [comment]
The chat menu itself, the font/text, the message prompt, name inboxes, basically, basically everything about the chat menu/system editable

**Comment by AgentXLP** [comment]
Not entirely sold on this, why would you need to change the chatbox like this?

**Comment by TheMan6900** [comment]
Would be cool seeing custom made chat menus, also would be nice for shrinking stuff like chat titles.

**Comment by AgentXLP** [comment]
Ehh, unless someone else wants to add API functionality to customize the chatbox in these ways, I think I'll be closing this issue
