### ISSUE TITLE
bettercam_pan_level is unable to be configurable via ingame menu

### ISSUE THREAD

**Issue by GabrielSomething** [coop-deluxe/sm64coopdx#27]
Self-explanatory, the slider doesn't even appears on the "Camera" options.
and i had to change the parameter from 100 to 0 via the sm64config.txt from the appdata folder.

I dont know if it doesn't appears due to a menu oversight, or it wasn't even added in the menu and got forgotten.

**Comment by Agent-11** [comment]
I had to sacrifice an option to fit every camera option on one page with 1024x768, I'm trying to keep the menus fine for smaller resolutions, I should just make the camera menu paginated as that would be a much better solution.

**Comment by GabrielSomething** [comment]
> I had to sacrifice an option to fit every camera option on one page with 1024x768, I'm trying to keep the menus fine for smaller resolutions, I should just make the camera menu paginated as that would be a much better solution.

thank you mister agent x
god i really hope there's a discord for coop deluxe if im interested on trying to do mods   in this,,,,

**Comment by Agent-11** [comment]
There is, but we plan on keeping it small and reserved by not making it public and instead relying on cool people that are already there to invite more cool people.

**Comment by GabrielSomething** [comment]
understandable, have a nice christmas eve

**Comment by Agent-11** [comment]
You too :>
