### ISSUE TITLE
Lua engine crash (likely memory corruption, possibly custom voices?)

### ISSUE THREAD

**Issue by Angel12125** [coop-deluxe/sm64coopdx#281]
**Describe the bug**
A complete crash (sorta) i could still exit by hitting the x so it didint break anything
exuse my bad grammer as well as lack of info it just sorta appeared

**To Reproduce**
1. i was running around the main yard
2. i checked to see discord and chatted a bit
3. i went back to the game

**Screenshots**
![image](https://github.com/user-attachments/assets/baa4cfa5-116e-4861-84b1-606585de5e14)

**Desktop (please complete the following information):**

(its the basic version and the mods are in the screen shot)

**Additional context**
i was running around the main yard (before going into the castle) when this appeared i was waiting for my frends

hopefully i gave you enough to work with i ant good at sending issues

**Comment by AgentXLP** [comment]
Fixed in dev

**Comment by Isaac0-dev** [comment]
the fact that it was crashing the Lua engine is a massive concern. what was causing the crash @AgentXLP

**Comment by AgentXLP** [comment]
Unsure but there were clips referenced in [CS] Extra Characters that didn't exist which caused one issue and there was also another where playing an audio sample/stream that was loaded with a filename that doesn't exist causes an audio_sanity_check crash, you can also try playing nil in the sample or stream functions possibly.

**Comment by Isaac0-dev** [comment]
the stack trace suggests that the crash is internally in Lua's engine which is most likely to be memory corruption. 
The `audio_sanity_check` crash is concerning and should be fixed but I doubt it's related tbh

**Comment by Angel12125** [comment]
well i am glad its getting fixed 
great work hope we can see eachother again lol
