### ISSUE TITLE
Can't enable anti-aliasing

### ISSUE THREAD

**Issue by SltcYann** [coop-deluxe/sm64coopdx#282]
**Describe the bug**
(ONLY WHEN I DO MY OWN BUILD OF THE GAME)
When i enable anti-aliasing, after i restart the game, it goes back to "Off"
I checked the save file and it does say "msaa 8" but when i relaunch the game it goes back to "msaa 0"

**To Reproduce**
1. Clone the "dev" branch of coopdx
2. Merge the dev branch with the deluxe-soundbank branch
3. Build the game with "make -j TEXTURE_FIX=1 HANDHELD=1"
4. Try to enable anti-aliasing

**Expected behavior**
It should toggle anti-aliasing after i restart the game

**Desktop (please complete the following information):**
 - OS: SteamOS 3.5
 - Browser: Firefox
 - Version: 1.0.1 (dev + deluxe-soundbank build)

**Additional context**
When i try to enable AA on the pre-built version found on the release page, it works.

**Comment by AgentXLP** [comment]
Fixed
