### ISSUE TITLE
Running print() doesn't do anything, and running game thru console doesn't pipe Lua errors and output

### ISSUE THREAD

**Issue by expected-ingot** [coop-deluxe/sm64coopdx#29]
**Describe the bug**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/64779013/d283c59d-f2a4-41d3-ac6d-5f4747ce3fe9)
Hello. When I use the print() command in my code, nothing gets written to the console. Running `./sm64coopdx.exe` also doesn't pipe the Lua error and output to the console.
![image](https://github.com/coop-deluxe/sm64coopdx/assets/64779013/4a0be8a0-4189-4cdb-ab77-9e3e9cd948e4)

Here is an image of the sm64coopdx console: 
![image](https://github.com/coop-deluxe/sm64coopdx/assets/64779013/3ec4e9f1-5590-4700-b165-6577766d3793)

**To Reproduce**
1. Create a Lua mod.
2. Use print().
3. No output.

**Expected behavior**
Output in console/ingame console

**Screenshots**
Please scroll up.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.3803
 - Browser: Firefox
 - Version: 121(?)

**Additional context**

**Comment by Agent-11** [comment]
To print to the in-game console, you need to use the `log_to_console` function. This was carried over from base sm64ex-coop and I think it would be better if that function was deprecated and a replacement for `print` that ALSO prints to the in-game console was made.

Currently, you need to compile the game with WINDOWS_CONSOLE=1 to have the external console, but thanks to your issue, I just made it a launch parameter in the next release (`--console`)

Also, nice de_dust port.

**Comment by expected-ingot** [comment]
Okay, thank you!

PS: Thanks :DD It's my first ever custom map and I'm making a mod/romhack that somehow recreates counter-strike gameplay

**Comment by Agent-11** [comment]
No problem dude :>

v0.1.2 comes out today also

**Comment by expected-ingot** [comment]
> To print to the in-game console, you need to use the `log_to_console` function. This was carried over from base sm64ex-coop and I think it would be better if an override for `print` that ALSO prints to the in-game console was made.
> 
> Currently, you need to compile the game with WINDOWS_CONSOLE=1 to have the external console, but thanks to your issue, I just made it a launch parameter in the next release (`--console`)
> 
> Also, nice de_dust port.

Running  `--console` in the new release (as in `sm64coopdx --console`) still only opens the game and results in no further output in the console. Do I have to run the patcher with `--console`?

**Comment by expected-ingot** [comment]
After further inspection, it fails to download the patch file, Any idea why?
![image](https://github.com/coop-deluxe/sm64coopdx/assets/64779013/52929a2e-ed38-4c27-942c-067311b97e87)

**Comment by expected-ingot** [comment]
You need to update your patcher. :)
