### ISSUE TITLE
Update Checker Function 

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#290]
would check github/coopdx website/discord for new releases of a mod and if your version is not up to date with a mod than itll alert you that your version is outdated. this would be a lua function.

**Comment by AgentXLP** [comment]
This would be a nice feature, but figuring out how it's going to be implemented is the tricky part. I don't want to add some kind of Discord or GitHub integration, and any mod site integration is planned for the future. Lua in coop is meant to be sandboxed anyway and I don't think I wanna implement a function to read data from the internet. Sorry but I think you're gonna have to wait until some kind of mod site integration comes one day and then there can be a field like `-- mod-id: 234` to check for updates maybe.
