### ISSUE TITLE
My fps slowly goes down

### ISSUE THREAD

**Issue by KevinHaak** [coop-deluxe/sm64coopdx#291]
I have a bug (maybe only for me) where my fps literally just drops frame by frame and I can't fix it.
Heres the link: https://www.youtube.com/watch?v=3gqOs8xLZos
the frames obs recorded are not that good so just look in the top right.

Edit: it is now fixed, and I'm using edit cause I don't know how to mark it as solved

**Comment by frog8412** [comment]
Remove extra characters mod, it causes script errors every frame which drops the fps

**Comment by EmeraldLoc** [comment]
This is actually a different bug that is yet to be reported. If script errors are spammed, the game slowly continues to lag. I believe the reason for this is related to logs, however unsure.
