### ISSUE TITLE
Hosting with CoopNet and disconnecting from the internet makes disconnecting not work

### ISSUE THREAD

**Issue by Bloxxel64** [coop-deluxe/sm64coopdx#292]
**Describe the bug**
After I started hosting, I had some internet issues. So naturally I went and power cycled the router, when I returned, attempting to search for the lobby on another device had no luck, so I went to rehost, and that's when the bug in the screenshot occured. I was unable to disconnect, and had to force the game to close.

**To Reproduce**
Simple method:
1. Start a lobby with a password on coopnet
2. Turn off your internet
3. Turn it back on
4. Pause the game, and attempt to disconnect (to no avail)

Accurate Method:
1. Start a lobby with a password on coopnet
Optional step. Create horrible internet
2. Unplug your internet router for 10-12 seconds
3. Pause the game, and attempt to disconnect (to no avail)

**Expected behavior**
Not this lol

**Screenshots**
![image](https://github.com/user-attachments/assets/037f665b-30e8-4d4b-b5e6-b26639a1bab8)

**Desktop (please complete the following information):**
 - OS: Windows 10 2H22
 - Browser Vivaldi
 - Version 1.0.1

**Comment by frog8412** [comment]
When you are not connected to CoopNet, this will happened for some reason
