### ISSUE TITLE
Unnecessary import fails compilation

### ISSUE THREAD

**Issue by Gumbo64** [coop-deluxe/sm64coopdx#297]
**Describe the bug**
Compiling on Debian 12 fails due to the import of <libc.h> in src/pc/mumble/mumble.c

**To Reproduce**
Compile using Debian 12

**Screenshots**
![image](https://github.com/user-attachments/assets/9df46eb5-e443-44bd-96d1-3cbb40f004b0)
![image](https://github.com/user-attachments/assets/fde0eb44-81d2-4fed-a380-45dcb956d705)

**Desktop (please complete the following information):**
 - OS: Debian 12

**Additional context**
It worked before this mumble was put in. Also it works if you just comment it out, so it should be a simple fix. I looked online, and it seems like <libc.h> is some macOS thing.

**Comment by robertkirkman** [comment]
Can reproduce on Gentoo. 

```diff
--- a/src/pc/mumble/mumble.c
+++ b/src/pc/mumble/mumble.c
@@ -18,9 +18,12 @@
 #else
 	#include <sys/mman.h>
 	#include <fcntl.h> /* For O_* constants */
-	#include <libc.h>
 #endif // _WIN32
 
+#ifdef __APPLE__
+	#include <libc.h>
+#endif
+
 struct LinkedMem *lm = NULL;
 
 extern bool gIsDemoActive;
```
bisects to https://github.com/coop-deluxe/sm64coopdx/commit/de47af04618d72a7e8ff7a820660904e59844fb3. @jordanvr  if you change it to something else like this patch, does it still compile for you? That compiles for me.

**Comment by EmeraldLoc** [comment]
https://github.com/coop-deluxe/sm64coopdx/commit/39aaed235bb226ad451317c6de4c55e37ce36485 A commit has already been made to do this
