### ISSUE TITLE
[HD textures] Mario cap logo not replaced

### ISSUE THREAD

**Issue by GhostlyDark** [coop-deluxe/sm64coopdx#298]
**Describe the bug**
The M on Mario's cap doesn't seem to load the HD texture. I expect the textures from current master of the Reloaded repo to load - the files are in there. I am confused as to why it doesn't load.

**To Reproduce**
Using SM64 Reloaded as texture pack:
https://github.com/GhostlyDark/SM64-Reloaded-PC

**Expected behavior**
I want it to look fancy.

**Screenshots**
![image](https://github.com/user-attachments/assets/f4036ce1-4a55-45ac-b2bf-d8cfc2b64431)
![image](https://github.com/user-attachments/assets/90775994-5940-446b-b279-7c03a31fe908)

**Desktop:**
Windows 11
sm64coopdx v1.0.1 (OpenGL)

**Comment by AgentXLP** [comment]
```c
    define_builtin_tex(mario_texture_m_logo, "actors/mario/custom_mario_logo.rgba16.png", 32, 32, 16),
    define_builtin_tex(mario_texture_m_blend, "actors/mario/custom_mario_m_blend.rgba16.png", 32, 32, 16),
    define_builtin_tex(mario_texture_m_cap, "actors/mario/custom_mario_cap.rgba16.png", 32, 32, 16),
```
One of the textures wasn't named properly so I fixed that but here are the current names you need to have to replace the texture properly with DynOS.

**Comment by GhostlyDark** [comment]
I see you changed the name in 8b723b8e850bf6c1cac70622beb80d2514364e6d, but I don't see why. If `dynos_mgr_builtin_tex.cpp` contains the names I need to look for, then I should just rename the file on my end, as you suggested. Not sure where I got the older file name from - maybe some old commit from a GitHub search...I don't remember.

On another note: I forgot to mention that the skyboxes don't load. It looks like the directory for those is set to `textures/skyboxes/`, but sm64ex always puts them inside 'textures/skybox_tiles'. The folder 'skyboxes' is for single image ones, 'skybox_tiles' is for the split images.

**Comment by AgentXLP** [comment]
The filename was changed by FluffaMario at some point
