### ISSUE TITLE
Headless server stuck on saving config

### ISSUE THREAD

**Issue by futurepr0n** [coop-deluxe/sm64coopdx#299]
**Describe the bug**
After extracting assets, changing the Headless ?= to 1 from 0, I was successful in building but when executing the ./sm64coopdx I am getting stuck at the screen:

![Screenshot from 2024-09-04 17-08-56](https://github.com/user-attachments/assets/dc6e381e-fd0a-4728-8801-e86a4f72085a)

**To Reproduce**
build using make,
go to build folder and run the headless executable

**Expected behavior**
I am actually not sure whats supposed to happen next. I opened up a client on another machine and tried to directly connect via IP address it did not work. I tried looking for the public lobby with 0 people joined, that also was not successful. Anyone know how to properly spin up a dedicated server with the headless build that would be greatly appreciated.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 22

**Additional context**

**Comment by futurepr0n** [comment]
I think I figured it out now, I saw another post - using `./sm64coopdx --server 7777 `I was then able to use the client and connect to the ip and port. Is there any other useful server flags? thanks!

**Comment by AgentXLP** [comment]
`./sm64coopdx --help`

**Comment by futurepr0n** [comment]
Those weren't too helpful - 
![Screenshot from 2024-09-04 17-28-38](https://github.com/user-attachments/assets/4719c678-dd31-4682-97b1-6088eab57911)
From the config.txt itself I can see that its got
```
coopnet_ip net.coop64.us
coopnet_port 34197
coopnet_password
coopnet_dest 0
```
But when I tried supplying the password and connecting using the password only it was unsuccessful finding the lobby. It also does not appear to have a config flag for the coopnet server name. If I wanted to supply one how would I go about it?

```
coop_host_port 7777
coop_host_save_slot 1
coop_join_ip
coop_join_port 7777

```
What is the difference from the coop ports and the coopnet port? Would all need to be set to the same port? or all ports open on the router in order for coopnet to see the public server?

**Comment by Cooliokid956** [comment]
the mods enabled in the config are used when hosting with headless

**Comment by Paradox9955** [comment]
> What is the difference from the coop ports and the coopnet port? Would all need to be set to the same port? or all ports open on the router in order for coopnet to see the public server?

`coop_host_port` is the port you use for direct connection
`coopnet_port` is the port that the CoopNet servers use

**Comment by futurepr0n** [comment]
Thanks @Paradox9955  that was pretty much something I was trying to understand and now makes sense. So noone would be able to see the server, just join directly and thats neat. Will not worry about a server name or anything like that.

Are there any customizations that can be done with a headless server that are noteworthy? Is there any server messages you can throw on like a message of the day or a greeting? Any limitations to know about as well?

Great work everyone involved in the project and thanks to the members of the community supporting users and answering questions!
