### ISSUE TITLE
How to add render96 texture pack and vanilla 96 to sm64 ex coop dx

### ISSUE THREAD

**Issue by Ilovevideogamer123** [coop-deluxe/sm64coopdx#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Agent-11** [comment]
For future reference, please actually fill the issue template in. You can create a DynOS Pack for Render96 models and textures, External Data has been removed because it is legacy and conflicts with DynOS.

**Comment by Ilovevideogamer123** [comment]
Thx

**Comment by Ilovevideogamer123** [comment]
Ok sorry

**Comment by Ilovevideogamer123** [comment]
Do you know how i can add vanilla96 i can't find it

**Comment by Ilovevideogamer123** [comment]
I just wanted to be like unreal64

**Comment by Ilovevideogamer123** [comment]
I just thought his looked cool
