### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by SonicTheHedgeHog64** [coop-deluxe/sm64coopdx#301]
**Describe the bug**
I can't host a lobby if i've already been in one, and it just crashes my game
**To Reproduce**
Get [Peaches Fury](https://github.com/ManIsCat2/Peach-Fury-Port)
Join a random lobby, Play around in it
Exit the lobby
Host Peaches Fury

**Expected behavior**
I can host the lobby, Nothing crashes
**Screenshots**
![Screenshot from 2024-09-05 12-09-17](https://github.com/user-attachments/assets/a27b0654-cd0a-4c86-a280-19ecb4a8c013)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
 - Browser Chromium
 - Version: Coop: v1.0.3, Web Browser: 128.0.6613.84 (Official Build) snap (64-bit)

**Additional context**
There's scrolling textures in the romhack

**Comment by ThePerfectMario64** [comment]
(The user was in another lobby)

**Comment by AgentXLP** [comment]
This looks like memory corruption, @Isaac0-dev what do you think

**Comment by Isaac0-dev** [comment]
the link doesn't work, I'd like to test the crash myself if I can.

**Comment by AgentXLP** [comment]
[Peach-Fury-Port.zip](https://github.com/user-attachments/files/16918790/Peach-Fury-Port.zip)

**Comment by ThePerfectMario64** [comment]
Agent sent another link

**Comment by Isaac0-dev** [comment]
I haven't been able to reproduce the bug despite following those instructions given. I also tried other things and no success. Also until I see more information about this crash I don't see any way that this could be related to smlua. It could be memory corruption, but it could also just be a read out of bounds.

**Comment by SonicTheHedgeHog64** [comment]
figured out why it crashed

go into the mod

go into the water

stop the lobby

rehost

see the crash

genuinely my fault.

**Comment by SonicTheHedgeHog64** [comment]
THE WAY I DID IT ALSO EXACTLY MATCHES THE CRASH SCREEN DOWN TO THE READ OOB TO THE STACK TRACE WTF
