### ISSUE TITLE
A way to make mod lua code inaccessible 

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#306]
would be nice to prevent stealing code (from public mods)

**Comment by frog8412** [comment]
if you meant prevent the mod from being in .tmp folder, put [WIP] in the mod's name and thats it

**Comment by frog8412** [comment]
![Uploading Screenshot_2024-09-06-23-12-20-270_com.discord.png…]()

**Comment by TheMan6900** [comment]
No I mean like making code unable to be edited

**Comment by AgentXLP** [comment]
Obfuscate or compile
