### ISSUE TITLE
m.marioObj.header.gfx.animInfo.animFrame doesnt work

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#309]
tried using "m.marioObj.header.gfx.animInfo.animFrame = m.marioObj.header.gfx.animInfo.animFrame + 1" for something Im making yet nothing happened, worked pre-1.0 soooooooooooooooo.

**Comment by AgentXLP** [comment]
I think this is another case of doing something differently and blaming its non functionality on 1.0
If you can, please verify this did indeed work in previous versions

**Comment by TheMan6900** [comment]
Heres me using a faster ground pounds script pre-1.0


https://github.com/user-attachments/assets/0cd4a5ed-2413-4248-9774-062dc0024bc8

**Comment by TheMan6900** [comment]
and here it is after-1.0


https://github.com/user-attachments/assets/60463528-bc67-4f5f-b0cd-5d9ed3142bef

**Comment by EmilyEmmi** [comment]
Oh, I ran into this issue! What I did was I added 2 instead of 1. My guess is that there was some sort of priority change.

**Comment by TheMan6900** [comment]
oh alright thanks.
