### ISSUE TITLE
Proper Mouse Support/Api

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#311]
Would be able set stuff interactable by clicking or hovering the mouse above it, basically everything related to the mouse cursor would be editable

**Comment by EmeraldLoc** [comment]
You can already 99% of this, see `djui_hud_get_mouse_x`, `djui_hud_get_mouse_y`, `djui_hud_set_mouse_locked`, and raw forms of getting the mouse. the only thing you can't do is check if someone "clicked" the mouse button, however if someone has the mouse button binded to say, B, the mod can check for B, making the mod check if someone clicked the mouse button.

**Comment by TheMan6900** [comment]
now thinking about that, yeah this is pretty redundant
