### ISSUE TITLE
Actual Accounts

### ISSUE THREAD

**Issue by Pixelsz64** [coop-deluxe/sm64coopdx#312]
Instead of just a name, you sign in with your coopdx mods site account. You can add friends and have badges maybe even a pfp and/or banner. It's basically the coopdx mod site user system in coopdx.

**Comment by BakerIsVeryHungry** [comment]
If it's only being played between friends, that kinda feels like a forced thing ngl. Maybe as an optional thing for the badges and PFP/banner? I prefer not to make logins for sites I never use personally. Only time I go there is to download mods.

**Comment by DayMario64** [comment]
@BakerIsVeryHungry no i am not meaning that you can only play with friends. just so you can easily join them and yeah it should be optional
