### ISSUE TITLE
Potential Explanation to the "Star Freeze" Bug

### ISSUE THREAD

**Issue by sher-b** [coop-deluxe/sm64coopdx#318]
Bug Description:
At seemingly random times during the star spawn cutscene, your player can freeze within said cutscene until another player grabs the star.

There is no good way to reproduce this bug, as it's believed to be caused by syncing issues.

Here is an explanation from a former contributor of ex-coop:

![image](https://github.com/user-attachments/assets/02d0523e-f2a5-4a33-9cac-3711eee64261)
![image](https://github.com/user-attachments/assets/3da5b9e1-cf17-40f5-be5c-f22b26501606)
![image](https://github.com/user-attachments/assets/001af35c-1161-478a-8a7f-b62b8a0ccf3a)

Given my previous knowledge about the bug, I believed it to be an issue with holding a direction during the cutscene. Hopefully this is the proper fix because this bug is annoying to deal with, especially if no one else can reach the star that had spawned.

**Comment by Sunketchupm** [comment]
This is (probably) fixed now so you can close this

**Comment by Isaac0-dev** [comment]
yeah that's fixed. the issue was players trying to sync the object when they didn't own it
