### ISSUE TITLE
An updated player colour editor

### ISSUE THREAD

**Issue by ExtCan** [coop-deluxe/sm64coopdx#32]
Hello! I hope this is the right place to submit suggestions for future features, if not, I apologize.

If it's possible, adding a colour wheel would be much better than using RGB values, and maybe custom shade colours like in the old Code Generator Suite by YoshiElectron, and finally, maybe adding custom colour slots for Dynos models that have more than just the general materials (Overalls, Face, Gloves, Hair, Cap/Shirt, Shoes)

Thank you for your time

**Comment by Agent-11** [comment]
A color wheel would probably be really cool, I would just need to learn how to program that as a DJUI element.
