### ISSUE TITLE
Version 1.03 not working on my linux computer

### ISSUE THREAD

**Issue by Gabie-Fox** [coop-deluxe/sm64coopdx#325]
It asks for an application to open the executable

It should have opened normally

 - OS: Linux Mint Cinnamon
 - Browser : Downloaded on: Firefox
 - Version : Downloaded the game in version 1.03

It asks for an application to open the executable, even though it  didnt need it in an older version

**Comment by eros71-dev** [comment]
You'll probably need to go to its Properties, Permissions, and check the box for Executable.

**Comment by Gabie-Fox** [comment]
Thanks, it worked for me, ill try to mark this one as fixed
