### ISSUE TITLE
WHite screen?

### ISSUE THREAD

**Issue by EzraLazy** [coop-deluxe/sm64coopdx#329]
**Describe the bug**
When i opened the game, there was a white screen and i cant see the game too, the music is still playing too

**To Reproduce**
i cant because i also cant see the game.

**Expected behavior**
idk 

**Screenshots**
![image](https://github.com/user-attachments/assets/dc130815-1baa-425c-ae02-821494a0217e)
here is the diffrence with direct x:
![image](https://github.com/user-attachments/assets/06ffbe03-a4f1-4669-aa79-94bec28db5ef)

**Desktop (please complete the following information):**
OS: [sm64coopdxv1.0.3 window openGL and directX version)
Browser: [Google Chrome]
Version [sm64coopdx v1.0.3]
 
**Additional context**
Even when i redownloaded the game, it still had the white screen.

**Comment by EmeraldLoc** [comment]
Try a different render api, like direct x, or if you were using that try OpenGL, also you opened 2 issues that were each the same, can you close the other one?

**Comment by EzraLazy** [comment]
here, i used direct x and open gl but both didnt work (btw im so sorry that i responded late i was just in school btw)

**Comment by EzraLazy** [comment]
hope you respond

**Comment by EmeraldLoc** [comment]
Yea so you’re going to want to use direct x, zero clue what’s going on with that other issue, someone else will need to chime in if they know.

**Comment by EzraLazy** [comment]
i still cant see the game when i click it with direct x

**Comment by EzraLazy** [comment]
if i do that it only shows pin taskbar or close or open it again

**Comment by EzraLazy** [comment]
wait IT WORKED THANK YOU THQANK YOU OMG THANK YOU DUDE YWIIJWFWJNNJFBEW YOOO
