### ISSUE TITLE
Recompiling with different RenderAPI

### ISSUE THREAD

**Issue by Spegghy** [coop-deluxe/sm64coopdx#33]
Is there a way I can recompile using a different RenderAPI like in the original sm64coop? OpenGL causes screen glitches for me and makes it unplayable, so I want to switch it to DirectX if I can.

**Comment by Agent-11** [comment]
Yes, you need to use MSYS2, sm64pcbuilder2 or edit coop-compiler, the next update will have OpenGL and DirectX 32-bit and 64-bit patches for sm64coopdx.
