### ISSUE TITLE
The launcher doesn't load

### ISSUE THREAD

**Issue by Herofertix** [coop-deluxe/sm64coopdx#331]
Whenever I open up the .exe a black screen appears, does nothing and 1 sec later it closes itself
![Capture](https://github.com/user-attachments/assets/b3357598-ac24-4976-9a97-2c9f145cc6a6)

**Desktop :**
 - OS: [sm64coopdxv1.0.3 Windows OpenGL & DirectX versions)
 - Browser: [Brave]
 - Version [sm64coopdx v1.0.3]

I've never installed this before, so I don't understand the problem 
(I've tried to launch it as administrator but nothing changes, and nothing changes either if I drop the rom)

**Comment by EzraLazy** [comment]
same like me, but expect after that my game reappears but i cant open it for some reason.
maybe you had a corrupted mod or something.
if you can try to put the mods into a new folder and test the game out again

**Comment by Herofertix** [comment]
I tried taking out the mods folder even I didn't install any, and still isn't working.
And yeah, I have a z64 file of the game in the coopdx directory

**Comment by Herofertix** [comment]
Okay, somehow, I fix it and apparently the problem was because I was launching the game in the (D:) disk instead of the local disk (C:)
