### ISSUE TITLE
Intel Mac Version won't run

### ISSUE THREAD

**Issue by Texzx** [coop-deluxe/sm64coopdx#333]
Version - Intel Mac 10.15.7, Running 64 bit Catalina. 

Error Message: 
sm64coopdx cannot be opened because of a problem. 
Check with the developer to make sure sm64coopdx works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

of course the arm version doesn't work since it's 10.14+ but Catalina should be good enough to open the intel one on an intel machine, unsure if I should homebrew the windows version through wine until a new mac version is implemented or just to wait.

**Comment by EmeraldLoc** [comment]
The prebuilt binary doesn’t support Catalina, so you’re going to have to compile coop manually

**Comment by EmeraldLoc** [comment]
Ok after doing some investigating indeed my glew and sdl2 builds have a minimum macOS version of macOS 14 (Sonoma). It'll take some work to figure out how I can get these dependencies for older macOS versions (probably involves compiling these libs from source), so will take some time.

**Comment by Texzx** [comment]
> Ok after doing some investigating indeed my glew and sdl2 builds have a minimum macOS version of macOS 14 (Sonoma). It'll take some work to figure out how I can get these dependencies for older macOS versions (probably involves compiling these libs from source), so will take some time.
> 
> In the meantime, I'd recommend following the instructions in the [Wiki](https://github.com/coop-deluxe/sm64coopdx/wiki) on how to compile on macOS Intel.

I will give it a try, for now, homebrewing the windows opengl version via wine works perfectly fine!

**Comment by ThePlayerRolo** [comment]
> > Ok after doing some investigating indeed my glew and sdl2 builds have a minimum macOS version of macOS 14 (Sonoma). It'll take some work to figure out how I can get these dependencies for older macOS versions (probably involves compiling these libs from source), so will take some time.
> > In the meantime, I'd recommend following the instructions in the [Wiki](https://github.com/coop-deluxe/sm64coopdx/wiki) on how to compile on macOS Intel.
> 
> I will give it a try, for now, homebrewing the windows opengl version via wine works perfectly fine!

how did you set up wine? I've moved from mac to windows a month ago and compiled SM64 Coopdx on Macos Catalina , but I never could get wine working, it would be nice to know just in case.
