### ISSUE TITLE
Colors messed up when running in Arch

### ISSUE THREAD

**Issue by futurepr0n** [coop-deluxe/sm64coopdx#338]
**Describe the bug**
I installed this on Arch and am getting odd colors for certain textures. Is it something I can fix?

**To Reproduce**
1. Install arch linux,
2. go to sm64coop, download release and install the rom/game.

**Expected behavior**
I would expect normal colors. There seems to be some issue with the palette for me.

**Screenshots**
![Screenshot 2024-09-23 at 11 00 22 AM](https://github.com/user-attachments/assets/fc9aa05a-25a7-4f7f-bea6-d067b091e605)

![Screenshot 2024-09-23 at 11 02 55 AM](https://github.com/user-attachments/assets/58b30b5c-3654-43ef-8195-9a9e86b67fe7)

**Desktop (please complete the following information):**
 - OS: Arch (latest)
 - Version SM64coopDX 1.0.3

**Additional context**
Im not sure what else might be needed in order to run this with better colors. Nothing else on the desktop seems affected

**Comment by Cooliokid956** [comment]
the red and blue color channels seem to have been swapped
