### ISSUE TITLE
it's not 32 bits

### ISSUE THREAD

**Issue by krfyron29** [coop-deluxe/sm64coopdx#339]
it's not 32 bits i see no reason 32 bit won't be powerful enough to run it

**Comment by DoomFunnyYes** [comment]
I'm sorry but you seem to have missed what the game is called. If I... recall correctly... gimme a minute... it's called. Super Mario... 64? You know, in relation to the Nintendo 64? Called as such because it's a 64 bit machine? 32 bits is Playstation level, I'm sorry. N64 just better.

**Comment by krfyron29** [comment]
> I'm sorry but you seem to have missed what the game is called. If I... recall correctly... gimme a minute... it's called. Super Mario... 64? You know, in relation to the Nintendo 64? Called as such because it's a 64 bit machine? 32 bits is Playstation level, I'm sorry. N64 just better.

uhhh sorry but you don't make any sense because not because it's sm"64" does mean the game has to be 64 bits
there WAS a 32 bit compatible version which was on v0.2 (3.14)
but no thank you
plus they said on a twitter post 32 bit will be added but not now because the sound thing doesn't seem to work and that post was way back then

also stop nerding about "erm actually it's mario 64 so basically it's not playstation level which is 32 bit :nerd::nerd::nerd::nerd::nerd::nerd::nerd:"
