### ISSUE TITLE
Include updated instructions on how to compile

### ISSUE THREAD

**Issue by expected-ingot** [coop-deluxe/sm64coopdx#34]
Hello! I know I can use coopdx_patcher, however it would be useful to provide a compilation guide so we can port coopdx to other platforms/architectures (32-bit, ARM for Android+Wine, etc). Thank you!

**Comment by FluffaMario** [comment]
You can compile it the same way you can compile base sm64ex-coop via the public repo actually, so you can probably work from there in terms of making ports to other platforms.

**Comment by expected-ingot** [comment]
Thank you!
