### ISSUE TITLE
Abnormal Aspect Ratio Support

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#341]
Pretty self-explanatory, would make mod ui not go off the screen for em.

**Comment by Cooliokid956** [comment]
coop supports any window size up to 65536x iirc
are you asking for mod creators to better handle abnormal screen sizes?
Who's "em"

**Comment by TheMan6900** [comment]
em is the ratios of screens, was mainly suggesting this cause of this ss my friend sent me, which has the tag menu cut off the screen.
![image](https://github.com/user-attachments/assets/e994d542-e37b-4676-a623-b69eed72719e)

**Comment by Cooliokid956** [comment]
this an issue that may be resolved on either end, by fixing Tag's menu, either adding a scroll bar, paginating, or decreasing size, OR on the user's end, simply by decreasing your DJUI scale

**Comment by TheMan6900** [comment]
oh alright
