### ISSUE TITLE
Increased damage for punch and slide kick

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [coop-deluxe/sm64coopdx#343]
The damage punching deals to other players is upped to 3 and slide kick is upped to 2. I feel this is necessary because it gives people an incentive to try other moves besides the far faster and more spammable moves, normal dive and jumpkick, for the same amount of damage as these attacks currently.

**Comment by TheMan6900** [comment]
Could also make these moves deal more knockback.

**Comment by yoyeet961** [comment]
https://github.com/coop-deluxe/sm64coopdx/issues/344#issuecomment-2385552322
