### ISSUE TITLE
Drift occurs when adjusting the deadzone to a low setting

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#346]
(this is not drift, nor me doing it, its just the game drifting by itself)

https://github.com/user-attachments/assets/0db9869a-0b2e-4c05-95da-b563c2743589

**Comment by Cooliokid956** [comment]
see the thing is you're causing problems for yourself 
the deadzone is supposed to solve this very issue, however by lowering it yourself you're reversing the solution 
Put it back how it was or turn it up until the "drift" disappears

**Comment by TheMan6900** [comment]
> see the thing is you're causing problems for yourself the deadzone is supposed to solve this very issue, however by lowering it yourself you're reversing the solution Put it back how it was or turn it up until the "drift" disappears

Wait that actually supposed to be its use? Didnt know that.
