### ISSUE TITLE
Any of versions don't work when opened

### ISSUE THREAD

**Issue by lehshd** [coop-deluxe/sm64coopdx#350]
So, I wanted to play sm64coopdx, I downloaded the OpenGL version, I opened the application. All it gave me is a 1ms command prompt window, Nothing happened then. I downloaded the DirectX version, IT STILL DIDN'T WORK. Fix the problem 
please!
Device used: PC, Windows 10.

**Comment by frog8412** [comment]
Move the game folder to desktop and try again

**Comment by lehshd** [comment]
> Move the game folder to desktop and try again

I already did that, it didn't work

**Comment by frog8412** [comment]
Delete the sm64coopdx folder from %appdata% then

**Comment by AgentXLP** [comment]
Did you try what frog suggested?
