### ISSUE TITLE
[CS] Paper Partners 64 + TTYD V3.1 skin cause game to crashes 

### ISSUE THREAD

**Issue by je7830** [coop-deluxe/sm64coopdx#366]
whenever i hover over admiral bobbery it causes the game to crash

**Comment by Flower35** [comment]
Please send a screenshot of the crash report, if you can still reproduce the problem. I haven't noticed any errors with this Character Select mod in particular. I suspect the crash might come from other mods or ROM-hacks.

**Comment by AgentXLP** [comment]
You need to be on the latest version with CS v1.9 or higher to get rid of the crashes
