### ISSUE TITLE
[Linux] Which dependencies do i need to run the game?

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [coop-deluxe/sm64coopdx#367]
Before i recompile box64(or fex) i need the .so files for running the game, i can compile manually if i need to.

**Comment by robertkirkman** [comment]
> fex
> box64

You can recompile coopnet, libjuice and liblua for ARM Linux targeting your C library and then write build system code ensuring the game binary is linked with your custom builds of those three libraries and that would allow you to run the game without using fex or box64

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> > fex
> > box64
> 
> You can recompile coopnet, libjuice and liblua for ARM Linux targeting your C library and then write build system code ensuring the game binary is linked with your custom builds of those three libraries and that would allow you to run the game without using fex or box64

Oh okay.
Question, will coopdx get ported to other platforms like android? Because i dont necessarily know coding that well. And writing system code seems like s tough task
