### ISSUE TITLE
A way to detect terrain based on their color

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#368]
Would be really nice for a mod that im making (floor is quicksand)

**Comment by Cooliokid956** [comment]
there is no correlation between visuals and collision

if you want to make the floor quicksand, do 
```lua
hook_event(HOOK_MARIO_UPDATE, function (m) if m.floor then m.floor.type = SURFACE_QUICKSAND end
```

**Comment by TheMan6900** [comment]
Already knew that but alr
