### ISSUE TITLE
Linux build error / Build instructions

### ISSUE THREAD

**Issue by Erotemic** [coop-deluxe/sm64coopdx#369]
**Describe the bug**
I am attempting to build sm64coopdx on Linux and I'm running into a build error. Furthermore, I'm not seeing any obvious install instructions, so if there is something different that needs to be done for this repo (wrt to sm64 or sm64-port), then might be a good idea to document that in the repo itself. I can help build that if I can get it working on my machine. 

**To Reproduce**

* Create a fresh clone of the repo
* Copy the baserom into the repo folder
* run make

```
git clone https://github.com/coop-deluxe/sm64coopdx
cd sm64coopdx
# copy the baserom to ./baserom.us.z64
make
```

**Expected behavior**
I would expect for the code to build and produce an executable, but instead I get an error:

```
Encoding VADPCM: build/us_pc/sound/samples/sfx_water/01_splash.table -> build/us_pc/sound/samples/sfx_water/01_splash.aifc
Encoding VADPCM: build/us_pc/sound/samples/sfx_water/02_swim.table -> build/us_pc/sound/samples/sfx_water/02_swim.aifc
Generating endian-bitwidth 
Generating:  build/us_pc/sound/sound_data.ctl 
Compiling: sound/samples_assets.c -> build/us_pc/sound/samples_assets.o
Compiling: sound/sequences_assets.c -> build/us_pc/sound/sequences_assets.o
sound/sequences_assets.c:4:10: fatal error: sound/sequences_offsets.inc.c: No such file or directory
    4 | #include "sound/sequences_offsets.inc.c"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1406: build/us_pc/sound/sequences_assets.o] Error 1
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04, gcc 13.2.0
 - Version: 4e01841693f2df0c61b7060c5bdf46ec063e1082

**Comment by Erotemic** [comment]
This appears to have been fixed in the dev branch: https://github.com/coop-deluxe/sm64coopdx/pull/314

**Comment by Multi-Volt** [comment]
> This appears to have been fixed in the dev branch: #314 but this issue should probably remain open until it is merged into main.

Seconded, this issue is fixed in dev.
OS: Fedora 40

**Comment by ThePlayerRolo** [comment]
> This appears to have been fixed in the dev branch: #314 but this issue should probably remain open until it is merged into main.

The dev can't connect to Main branch servers last time I checked when I was compiling and having the same error here's my thread and the fix for main branch should be there if you scroll by @Flower35  : https://github.com/coop-deluxe/sm64coopdx/issues/186

**Comment by Erotemic** [comment]
Is there a reason that dev can't be merged into main and released? If so, should any stable fixes be cherry picked onto the main branch? (trying to familiarize myself with the development practices in this repo)

**Comment by Multi-Volt** [comment]
> Is there a reason that dev can't be merged into main and released? If so, should any stable fixes be cherry picked onto the main branch? (trying to familiarize myself with the development practices in this repo)

I think the issue being raised here is not that dev can't be merged into main but rather the current dev build can't properly connect to main branch coop.net servers.

In other words, until main is properly fixed you either need to manually fix the issue pertaining to compilation issues or don't play multiplayer. I personally haven't had issues joining private games on a dev build before.

**Comment by Isaac0-dev** [comment]
As far as I am aware, there is no issue that prevents merging into the main branch.
I do not believe there is an issue with connecting to coopnet, you probably just can't see any lobbies because no one on that build is hosting at the moment.
We just haven't made the release yet, thats it.

**Comment by EmeraldLoc** [comment]
> As far as I am aware, there is no issue that prevents merging into the main branch.

Does the piranha plant hitbox change not cause a desync between players running dev vs players not running dev?

**Comment by Multi-Volt** [comment]
Went ahead and compiled the latest dev changes, and was successfully able to join a public lobby. So there doesn't appear to be any issue on a native Linux build ATM.

OS: Fedora 40
gcc: gcc (GCC) 14.2.1

![Screenshot from 2024-10-14 18-15-57](https://github.com/user-attachments/assets/7ce301e4-2793-4d0d-93e7-387fc41a8d3f)

![Screenshot from 2024-10-14 18-16-44](https://github.com/user-attachments/assets/7cd8753e-d047-452c-a0c9-2d566fe4d572)

**Comment by ThePlayerRolo** [comment]
ah ok, it must've changed since I did it, since a couple months ago you couldn't join main servers on dev.

**Comment by AgentXLP** [comment]
Instructions are on the GitHub wiki btw

**Comment by Erotemic** [comment]
@AgentXLP I recommend adding a link to the wiki in the README with a quick description of the kinds of information it contains (i.e. compiling for different platforms, hosting, and joining). By default, it isn't obvious if a github wiki is maintained o populated with anything useful. Adding a sentence and link in the README will make that much more clear.
