### ISSUE TITLE
Make emblem coloring effect eye color/make a eye coloring option

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#406]
Just simply would be nice for skins.

**Comment by Cooliokid956** [comment]
Consider the following: the emblem color is meant to recolor the emblem

**Comment by Cooliokid956** [comment]
if you're talking about being able to recolor eyes with the color, anybody could've done that long ago
it's a matter of whether the model maker adds the functionality or not, there's a process
