### ISSUE TITLE
unable to compile without discord integration

### ISSUE THREAD

**Issue by MasterEvilAce** [coop-deluxe/sm64coopdx#43]
Trying to compile sm64coopdx v0.2.2 without the discord integration stuff. Tried editing makefile directly to set DISCORD_SDK to 0, as well as with
make DISCORDRPC=0 DISCORD_SDK=0

Both situations fail with the following error:
Linking executable: build/us_pc/sm64coopdx.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: build/us_pc/src/pc/djui/djui_panel_join.o:djui_panel_joi:(.rdata$.refptr.gDiscordInitialized[.refp
tr.gDiscordInitialized]+0x0): undefined reference to `gDiscordInitialized'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:1511: build/us_pc/sm64coopdx.exe] Error 1

Windows 11 64bit
mingw64

**Comment by Agent-11** [comment]
This is genuinely just a mistake I made with that feature, sorry about that.
