### ISSUE TITLE
guys help 😭 

### ISSUE THREAD

**Issue by mono1231** [coop-deluxe/sm64coopdx#44]
![lel translated](https://github.com/coop-deluxe/sm64coopdx/assets/155445879/e3c5eefe-a5ee-482d-95b2-951801f02518)

**Comment by Agent-11** [comment]
Make sure you extracted all of the DLLs, also there looks to be something very wrong with your installation of Windows 7.

**Comment by windows10-gthb** [comment]
> > Make sure you extracted all of the DLLs, also there looks to be something very wrong with your installation of Windows 7.
> 
> yeah it looks like a corrupted installation (some of the text looks weird too)

the text looks weird because most likely their system is not English so they used smth like Yandex Translator to translate the text to English
