### ISSUE TITLE
[Feature Request] DirectX11 support

### ISSUE THREAD

**Issue by Rigerhit047** [coop-deluxe/sm64coopdx#45]
The recent updates brought the ability to choose renderer in the patcher, however, it seems like the "DirectX" option only patches the game with DirectX12, which greatly limits the compatibility for older hardware, since you need a graphic card that supports it, and if OpenGL doesn't work neither will work DirectX12.

So to have more compatibility with older systems, I would suggest replacing/adding DirectX12 with DirectX11, like the coop compiler, so people who can play the original version can play the fork, too, specially since low end hardware greatly takes advantage of not needing to compile the game greatly decreasing literal days work to just some minutes, even if it comes with the tradeoff of mouse controls not working.

**Comment by Agent-11** [comment]
I will compile the patches to use directx 11 next update.
