### ISSUE TITLE
Game crash after idling after exiting stage from collected star

### ISSUE THREAD

**Issue by Dal1ster** [coop-deluxe/sm64coopdx#46]
**Describe the bug**
When trying to idle for a second after exiting a stage via collecting a star, the game seemed to crash with this error screen

**To Reproduce**
1. Go to Bob-Omb Battlefeild
2. Collect a star (for me it was the king bob-omb boss fight
3. Exit to castle and save game, then wait

**Expected behavior**
I expected to just idle in the castle after collecting a star and exiting a level like bob-omb battlefeild

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version (if this means windows version) 22H2

**Additional context**
it just randomly happened with the latest update i dont know why, also the error screen that appeared when it crashed
![Screenshot 2024-01-03 202224](https://github.com/coop-deluxe/sm64coopdx/assets/76823236/8751cebf-13f9-4682-a803-dd0a00458d0e)

**Comment by Agent-11** [comment]
Will look into.

**Comment by Agent-11** [comment]
Were you hosting with leave level on star collection or the other options?

**Comment by Dal1ster** [comment]
I was a client to someone that had that on I think

**Comment by Agent-11** [comment]
Next update will have a fixed crash screen that shows function names properly.

**Comment by Agent-11** [comment]
Can't seem to reproduce this, do you have a video?

**Comment by Dal1ster** [comment]
sadly, it was just a random occurrence, and i wasnt planning to record because i thought it wouldn't happen,. the closest thing that would work is a log file, and i dont know where it is located or if it is flushed out upon every boot of sm64coopdx
