### ISSUE TITLE
Ban Explanation 

### ISSUE THREAD

**Issue by ZelRaccy** [coop-deluxe/sm64coopdx#489]
i was banned for using an external tool i made for me and my friends to just mess around mainly because the game NEVER states to not use any cheat software on the normal build. however the guy running around pretty much doxxing people is just out to get everyone lmao 

unban me pls xd  ID: 1407513892387753273

![image](https://github.com/user-attachments/assets/70b25c9e-94d8-4913-a313-f6b8b83d1d2c)

BTW if you dont want people using cheat tools on your game maybe put "dont use cheat software" in the rules 
I deserve an unban because technically its a false ban until its added to the rules and adding it to the rules now would be too late <3

**Comment by Isaac0-dev** [comment]
you are not banned and never were. your self righteous attitude is not appreciated.

**Comment by ZelRaccy** [comment]
my bad, just got banned from the discord is all an thought it was sorta dumb

**Comment by SonicTheHedgeHog64** [comment]
the gall bro 😭
