### ISSUE TITLE
No such File or Directory

### ISSUE THREAD

**Issue by RedwingandLuca** [coop-deluxe/sm64coopdx#49]
**Describe the bug**
Upon compiling manually the make -j4 part of the command flat out wont detect the directy.

**To Reproduce**
1:Just follow the guide on the manual compile and make -j4 will do this most likely.

**Expected behavior**
It SHOULD compile.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/87355237/45bbe387-2397-466e-ac8e-17392d3aeacd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser OperaGX
 - Version Dunno sorry, should be most recent.

**Additional context**
Sorry if this shoddy ive never used github also hi agent x.

**Comment by Agent-11** [comment]
Did you install the required dependencies? Gonna update the README today with information on compiling btw.

**Comment by RedwingandLuca** [comment]
Yeah, installed the dependencies, just doesnt seem to have the directory part working? And im glad that the readme will be updated later. I cant really ask coop-ex for help compiling it as its dx so i came here.

**Comment by Agent-11** [comment]
Was going to update it yesterday but I caught a fever, will do that tonight.

**Comment by RedwingandLuca** [comment]
Dont worry man! Take your time!

**Comment by Agent-11** [comment]
It's been updated for a few days [here](https://github.com/coop-deluxe/sm64coopdx/blob/dev/README.md), make sure you're compiling with mingw64.exe and have installed the listed dependancies

**Comment by RedwingandLuca** [comment]
Alright after FINALLY getting to test cuz of a broken pc fan, it still has the same error, i dunno what it is.

**Comment by RedwingandLuca** [comment]
Nevermind my last post, i may be stupid and have been using the SHELL to try and build. I got it building right now

**Comment by uuphoria2** [comment]
accidentally mentioned this srry (meant to do #53
