### ISSUE TITLE
Coop just completely freezes randomly

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#492]
Not sure if this has to do with internet or something else.

**Comment by Isaac0-dev** [comment]
please stop opening so many issues. join the discord to discuss these things

**Comment by AgentXLP** [comment]
Issue 493: Coop looked at me the wrong way

**Comment by TheMan6900** [comment]
> please stop opening so many issues. join the discord to discuss these things

What falls under "these things"?
