### ISSUE TITLE
Menu Mouse Problems

### ISSUE THREAD

**Issue by Kirby715** [coop-deluxe/sm64coopdx#496]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Kirby715** [comment]
On the menu the mouse isn't synced with my computer mouse, this may have to do with the fact im using a surface pro 7, but it doesnt allow me to do much on the menu which i hate.

**Comment by AgentXLP** [comment]
Should be fixed in 1.0.4
