### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by JakeHunterTH** [coop-deluxe/sm64coopdx#50]
When I was playing for a first time I noticed something, after getting first star I saved the game (At least i thought so), but when i stopped hosting, savefile just vanished, I didn't paid attention. But after i closed game and opened it again, everything just reseted, including key bindings and other stuff. Fix it please.

**Comment by Agent-11** [comment]
Strange.

**Comment by JakeHunterTH** [comment]
I can send proofs tomorrow or show somehow

**Comment by JakeHunterTH** [comment]
I could show if I could knew where to get a link to DS server of this game.

**Comment by Agent-11** [comment]
I can't seem to reproduce this, this is probably gonna sound weird but is your hard drive full or something?

**Comment by Agent-11** [comment]
Whenever you collect a star, even if you choose not to save coop still saves the game so I'm not sure what to make of this issue.

**Comment by JakeHunterTH** [comment]
145 GB of free space (435 GB in total), idk what could cause this problem, I decided to test if this problem will happen again but on different pc, so I called my friend. Told him to install the game, and get the star to see if progress will save file correctly. But unfortunately this happened again. All saves and entire options reseted. Both of us got confused.

**Comment by JakeHunterTH** [comment]
In case if you'll want to see proofs by yourself on the through stream. Discord: jakehunterth

**Comment by JakeHunterTH** [comment]
This issue must be fixed.

**Comment by JakeHunterTH** [comment]
![image](https://github.com/coop-deluxe/sm64coopdx/assets/143154292/fe6eb7d5-ca03-46cb-8e5a-de04827f67a4)
Every time i re-open game it resets and showing language select (And Russian language here is broken)

**Comment by JakeHunterTH** [comment]
I don't actually know what might cause this kind of stuff, but it must be fixed, I can't play normally without saves, each time re-entering game and configure all again and again.

**Comment by Agent-11** [comment]
It's hard to debug this because it seems to be some kind of issue with your system, do you have sm64coopdx with OpenGL or DirectX?

**Comment by JakeHunterTH** [comment]
When I was during the installation of sm64coopdx I just pressed enter, so Ig I have it with OpenGL.

**Comment by psaulnie** [comment]
A friend of mine has the same issue, when he click on the "Open Appdata" button in Settings, the folder that is opened is the game folder (with the executable & DLLs), the AppData folder is created but he's empty

**Comment by JakeHunterTH** [comment]
Damn, I don't even have AppData folder, bruh

**Comment by psaulnie** [comment]
Also, it does not seem to be a permission issue, we tried running the game with admin permissions if it can help

**Comment by Paradox9955** [comment]
> When I was playing for a first time I noticed something, after getting first star I saved the game (At least i thought so), but when i stopped hosting, savefile just vanished, I didn't paid attention. But after i closed game and opened it again, everything just reseted, including key bindings and other stuff. Fix it please.

This actually happens when you have non-alphanumeric characters in your file path. You'll need to open the game through terminal with `--savepath .` added at the end. This will save all your files into the same folder the exe is in.

**Comment by JakeHunterTH** [comment]
Okay will try, if it'll work, I'll let you know.

**Comment by JakeHunterTH** [comment]
One more question, where's the terminal?

**Comment by JakeHunterTH** [comment]
I just don't get it correctly tbh

**Comment by JakeHunterTH** [comment]
Okay forget abt it, I guess one screenshot will be enough for me to understand exactly what to do.

**Comment by JakeHunterTH** [comment]
I just tried to type a command through windows terminal, nothing happened

**Comment by Paradox9955** [comment]
> I just tried to type a command through windows terminal, nothing happened

I can't get a screenshot, since I don't use windows. But what you can do, is right click on the exe of CoopDX and select "create shortcut". Make sure the shortcut is right next to the exe. Then right click that shortcut and edit the properties, then add `--savepath .` to the end of the target box. It should look something like this 
![unknown-1](https://github.com/coop-deluxe/sm64coopdx/assets/88796228/337e06a5-e23c-4605-991f-2f3fbba4619e)

**Comment by SeaSharkDEV** [comment]
Still doesn't work

**Comment by Paradox9955** [comment]
Yeah, you probably did it wrong.
