### ISSUE TITLE
I regret updating

### ISSUE THREAD

**Issue by SonicTheHedgeHog64** [coop-deluxe/sm64coopdx#503]
**Describe the bug**
After updating from 1.0.3 to 1.0.4 (manually built) here's what happened to the mods / game
Cannot join lobbies
char-select is broken

**To Reproduce**
1st Bug: TRY and join a lobby and you can't join
2nd Bug: Get char select (git clone into the mods folder)

**Expected behavior**
I can join lobbies
Char select doesn't start tweakin

**Screenshots**
https://github.com/user-attachments/assets/caabc2c9-f9a4-4c08-9eac-fbad88f1bdf6

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS (Noble Numbat)
 - Browser: Chromium Version 130.0.6723.116 (Official Build) snap (64-bit)
 - Version: 1.0.4

**Additional context**
I have both mods in the lobby i attempted to join
I was able to join lobbies fast on the last version

**Comment by SonicTheHedgeHog64** [comment]
2nd bug ruled out
the char-select version i was using was indev, what a suprise when you get it from github (i am in mental pain)

**Comment by SonicTheHedgeHog64** [comment]
another 2nd bug
my game just likes to freeze now

**Comment by SonicTheHedgeHog64** [comment]
guess what's back?

**Comment by SonicTheHedgeHog64** [comment]
not being able to join lobbies is back

**Comment by SonicTheHedgeHog64** [comment]
tell a linux friend

**Comment by Isaac0-dev** [comment]
you should be able to join private lobbies fine. for now, the precompiled build works with everything so if you're confortable with using it i'd suggest it
