### ISSUE TITLE
when i open the game the screen is invisible and i can see the game screen and hes open wint the music he opens but the screen do not load

### ISSUE THREAD

**Issue by idkwhatusernameiputherelol** [coop-deluxe/sm64coopdx#509]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by EmilyEmmi** [comment]
Could you be a little more specific? Screenshots, etc. It would also help if you gave your operating system and if you're using DirectX or OpenGL.

**Comment by idkwhatusernameiputherelol** [comment]
the screen of the game is invisible  emilyEmmi

**Comment by AgentXLP** [comment]
Incomprehensible, try again

**Comment by idkwhatusernameiputherelol** [comment]
![Captura de tela 2024-11-23 113732](https://github.com/user-attachments/assets/4a0847ac-2a25-4aaf-9cc0-d2e37eb48faa)
im wint the sm64 coop dx open in him screen in backgorund is discord open to do not work  is look like discord is open but is not is at the screen of the game

**Comment by idkwhatusernameiputherelol** [comment]
> Hold shift and right click on the window on the taskbar and select "maximize"

Thx man
