### ISSUE TITLE
Can't silence sequence using HOOK_ON_SEQ_LOAD

### ISSUE THREAD

**Issue by BryanHaley** [coop-deluxe/sm64coopdx#512]
The docs for HOOK_ON_SEQ_LOAD says the following:
```
Called when a sequence is going to play, return a SEQ_* constant to override the sequence. SEQ_SOUND_PLAYER (0) is silence.
```
Which seems to imply that when SEQ_SOUND_PLAYER (0) is returned from the callback, the sequence will be silenced (which is what I want to do).

However, the actual function looks like this:
```
    smlua_call_event_hooks_on_seq_load(HOOK_ON_SEQ_LOAD, player, seqId, loadAsync, &returnValue);
    if (returnValue != 0) {
        seqId = returnValue;
    }
```
Which ignores the return value if it's zero, thus not silencing the sequence if SEQ_SOUND_PLAYER is returned.

**Comment by BryanHaley** [comment]
A workaround of returning `SEQ_COUNT` seems to work, but I think the docs should be updated to be more clear.

**Comment by AgentXLP** [comment]
I agree
