### ISSUE TITLE
Controller's analog inputs won't bind

### ISSUE THREAD

**Issue by AftDawn** [coop-deluxe/sm64coopdx#517]
When i try to bind any controller i own to sm64coopdx, digital buttons work fine, but analog inputs don't bind, even though the main analog stick still moves mario around and the C buttons (which are mapped as right stick on my 8bitdo n64 controller modkit) still move around the camera. Ground pounds don't work however.

1. Go to Options
2. Go to Controls
3. Select the correct controller
4. Go to N64 Binds
5. Try to Bind something like "Up" to Analog stick up
6. The Game doesn't recognize it

I would expect the input being bound to bind without hassle

 - OS: SteamOS (Arch Linux based)
 - Version v1.0.4

I have tried running the game standalone and through Steam Input, neither option seems to help at all.

**Comment by AgentXLP** [comment]
As of now you can't bind any inputs to the analog sticks, sorry

**Comment by AftDawn** [comment]
That sucks, cause I would of thought that the 8bitdo n64 controller would work 100%, but since the z button is mapped as an analogue input even tho it just goes from min to max when pressed, means that I can't do anything using the z button
