### ISSUE TITLE
Mouse look not working

### ISSUE THREAD

**Issue by pinkosushi** [coop-deluxe/sm64coopdx#53]
My mouse won't lock to the game for some reason. Any help?

Edit: Works on OpenGL but not on DirectX

**Comment by pinkosushi** [comment]
My mouse isn't getting picked up at all. Only works in the menus.

**Comment by SonicDarkYT** [comment]
likely because you're in DirectX, there's nothing really to do there

**Comment by pinkosushi** [comment]
> likely because you're in DirectX, there's nothing really to do there

why doesn't DirectX support mouse look?

**Comment by SonicDarkYT** [comment]
Beats me

**Comment by Agent-11** [comment]
There's not an implementation for DirectX, I can try to make one though.

**Comment by pinkosushi** [comment]
> There's not an implementation for DirectX, I can try to make one though.

that would be lovely

**Comment by uuphoria2** [comment]
I might have a fix for this
