### ISSUE TITLE
Can't connect to coopnet

### ISSUE THREAD

**Issue by govr017** [coop-deluxe/sm64coopdx#54]
When I try to do anything like hosting or joining I can not access it through coopnet. The Error: "Lost Connection to Coopnet"
Here are my attempts to connect to ip:
![image](https://github.com/coop-deluxe/sm64coopdx/assets/69794668/16fa0eb1-a2cd-425f-9e63-a821395c6fe7)
I can connect to the actual address using ping or my browser but I can not do it in game.

Now a list of things I've tried to do in order to fix this:
1. Changing my Firewall settings(including completely disabling it)
2. Changing my DNS
3. Using a VPN

I am on Windows 10
Here's my sm64config.txt:
[sm64config.txt](https://github.com/coop-deluxe/sm64coopdx/files/13894186/sm64config.txt)

Any suggestions on how I could fix this?

**Comment by Agent-11** [comment]
You may be banned?

**Comment by govr017** [comment]
> You may be banned?

Is that really a thing here? I've never heard anyone getting banned. If it is a thing then is there a way to get unbanned or atleast see the reason I was banned?

**Comment by Isaac0-dev** [comment]
coopdx uses regular coop's online servers, so coopnet bans will carry over to coopdx. if you were banned on regular coop, you're banned on coopdx's default public servers as well. without your coopnet id its difficult to tell whether you're actually banned or not

**Comment by govr017** [comment]
> coopdx uses regular coop's online servers, so coopnet bans will carry over to coopdx. if you were banned on regular coop, you're banned on coopdx's default public servers as well. without your coopnet id its difficult to tell whether you're actually banned or not

Hm ok, how do I get the ID and where can I check if I'm banned?

**Comment by uuphoria2** [comment]
> > coopdx uses regular coop's online servers, so coopnet bans will carry over to coopdx. if you were banned on regular coop, you're banned on coopdx's default public servers as well. without your coopnet id its difficult to tell whether you're actually banned or not
> 
> Hm ok, how do I get the ID and where can I check if I'm banned?

In Coopnet make a password protected server host yourself on sm64coopdx press host then in coopnet put a password there no password will put it in public servers it should let you in it if its a private server (To make one just put a password in like i said) 
![image](https://github.com/coop-deluxe/sm64coopdx/assets/155935644/9769b2d4-373a-4694-b977-df8b81b94467)
In chat type this command `/players` look at ur username and the long number string next to `0 -` or some number is your ID I dont know how to copy and paste in the chat so just type it out slowly (look for any mistakes) unless there is a method

**Comment by uuphoria2** [comment]
Tho im not sure if u could still make private servers in coopnet.

**Comment by alejandrorincon3112-del** [comment]
I was banned but with my grandma's Internet it works
