### ISSUE TITLE
mod_storage_load_number/bool behavior when key does not exist

### ISSUE THREAD

**Issue by BryanHaley** [coop-deluxe/sm64coopdx#540]
For mod_storage_load, it's easy to tell if the key already existed as it'll return nil if it did not.

However, mod_storage_load_number returns 0 and mod_storage_load_bool return false if the key does not exist. This is not optimal in situations where 0 or false is a valid value, but **not** the desired default value. There are some ways around this, but they're not super great.

Some potential solutions:
- Add a "mod_storage_key_exists" that simply returns true or false depending on if the key is found.
- Allow supplying a default value to mod_storage_load_number/bool that gets returned if the key is not found.

**Comment by AgentXLP** [comment]
Ill do the 1st solution

**Comment by AgentXLP** [comment]
https://github.com/coop-deluxe/sm64coopdx/commit/856a828229d100339446696bcf66eadd882ee0e9
