### ISSUE TITLE
Port to Wii U, PS3, PS4, Switch

### ISSUE THREAD

**Issue by August988** [coop-deluxe/sm64coopdx#543]
Could/Would sm64coopdx ever be ported to any of these consoles, considering the Wii U and PS3 unofficial ports of Super Mario 64 with the source code all run amazing at 60fps smoothly, and I see no reason why sm64coopdx COULDNT be ported aswell!

**Comment by ValorZard** [comment]
doubt it, the multiplayer stuff alone would be impossible to port

**Comment by syn1ng** [comment]
> doubt it, the multiplayer stuff alone would be impossible to port

It is possible, but I don't see why consoles need this.
Porting to android was already a hard thing to do, and took some time to even happen (approximately like 8 months or more)
I don't see why you think porting this is a good idea, too. Like nobody's gonna be playing this on Wii U or PS3. It's just a too niche concept to have to keep updated. And even if you wanted it, you'd have to use a PC to even compile it.

I don't speak for the devs, but I highly doubt they're doing this, like, ever.

**Comment by SltcYann** [comment]
wiiu and the playstations aren't good ideas, but a switch port would be neat tho
