### ISSUE TITLE
Extra Characters's Peach and Daisy vanish cap issue

### ISSUE THREAD

**Issue by Brob2nd** [coop-deluxe/sm64coopdx#553]
Hi, i wanted to report a bug (half bugs half not) with the Extra Characters mod.

Most imporantly first, Peach and Daisy's low part of the dress (the overall one) looks weird with the Vanish Cap

![Captura de pantalla (1150)](https://github.com/user-attachments/assets/71d8a1e9-a24b-43b1-b5ea-476f20903541)
![Captura de pantalla (1151)](https://github.com/user-attachments/assets/570cc4cc-8823-4cb4-b649-1951a51166cf)
It looks like it was not intended to look like this, thanks for looking at this issue.

Related to Pauline, his hat in the metal state looks, eh, weird
![Captura de pantalla (1153)](https://github.com/user-attachments/assets/50b1d92c-4974-4189-8e01-a7f4b3e6680a)
Not only that, but this
![Captura de pantalla (1244)](https://github.com/user-attachments/assets/0b119237-6afe-4e5f-9ccc-5ff69d184f8c)

lastly and the least important of all, her gloves is recoloreable, but the earrings aren't, even tho it uses the same texture, i think the earrings should use the emblem slot
![Captura de pantalla (1149)](https://github.com/user-attachments/assets/468dbef8-a23c-4d8c-a3b6-8afdee34a5be)
![Captura de pantalla (1148)](https://github.com/user-attachments/assets/0446199d-0a2b-4874-97fd-526df341f988)
Thanks for reading.

**Comment by AgentXLP** [comment]
Should be addressed in the 1.1 coopdx update
