### ISSUE TITLE
Game crashes after changing main menu too many times.

### ISSUE THREAD

**Issue by MiiShroom** [coop-deluxe/sm64coopdx#56]
**Describe the bug**
Turning staff roll off and on multiple times would crash the game.

**To Reproduce**
1. Go to 'Options'
2. Click on 'Misc'
3. Click on 'Menu Options'
4. Click on 'Staff Roll' multiple times until crash
5. See error

**Expected behavior**
Expected to just be able to see the difference between the option being off and on multiple times.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version 22H2

**Additional context**
The bug is a bit inconsistent. Sometimes, the bug would take less than 2 clicks to happen, and other times, it would take forever to happen, or would just require restarting the game to happen again.
Also, the only reason why I found this bug is because I was a moron, and I didn't notice it was changing the background and music.

![image_2024-01-13_225459751](https://github.com/coop-deluxe/sm64coopdx/assets/156559698/4d759a85-56f0-4265-9466-88ad244cb34a)

**Comment by MiiShroom** [comment]
didn't mean to close it lol

**Comment by Agent-11** [comment]
Hmm

**Comment by Agent-11** [comment]
Can you provide a video of this happening possibly?

**Comment by MiiShroom** [comment]
> Can you provide a video of this happening possibly?


https://github.com/coop-deluxe/sm64coopdx/assets/156559698/7efbd52d-9a90-4421-abae-1efcdb2a6b08

I just noticed, I was doing this with capped fps, so, I tried it uncapped, and it didn't work. Maybe it has something to do with that?

**Comment by Agent-11** [comment]
I see

**Comment by Agent-11** [comment]
Fixed in the new update
