### ISSUE TITLE
Some miscellaneous Issues/enhancements for freecam

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#562]
Will add to this if I find anymore, I'm also just grouping these all together, mostly to not flood the repo with issues again (Character Development 👍)

1. Auto locking with freecam doesn't get cancelled when interrupting with a freecam joystick movement (This is me fighting against the autolock in the video)
https://github.com/user-attachments/assets/a1e332cd-eec5-455f-8975-c6823fa46fd8
2. Freecam conflicts against manual inputs while agro when shelling (That semi-turn is me fighting against the agro in the video)
https://github.com/user-attachments/assets/d83b78c1-77c3-43b3-bece-df86350e9c06
3. Freecam mirrors when looking at a top wards angle (also does the same to the controls)
https://github.com/user-attachments/assets/64f10728-4a8a-4833-9dab-3f98fd370909
4. Freecam stutters when trying to argo while mario is going at a negative velocity
https://github.com/user-attachments/assets/4a19b3cd-7456-426a-8ff4-718b04558514

**Comment by AgentXLP** [comment]
Will address
