### ISSUE TITLE
Mouse and window issues with a >100% display scale/high-DPI monitor

### ISSUE THREAD

**Issue by hf02** [coop-deluxe/sm64coopdx#568]
**Describe the bug**
When using something other than a 100% scale in display settings, the mouse is incorrectly positioned and the window opens bigger than expected.

**To Reproduce**
1. Set a scale higher than 100% in Windows display settings
2. Launch the game

**Expected behavior**
The mouse should be correctly positioned, and the window shouldn't be excessively large.

**Screenshots**

Starting window size exceeding monitor resolution:

![image](https://github.com/user-attachments/assets/b5e0854a-9ae3-4362-b687-5d5a2642939a)

Mouse incorrectly positioned:

![image](https://github.com/user-attachments/assets/5a3e772b-c8ba-467e-ab9e-03afa38cdde6)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Firefox...?
 - Version: v1.0.4

**Additional context**

This issue can be seemingly fixed while keeping the resolution by using Windows compatibility settings.

1. Right click the .exe
2. Click "Properties"
3. Go to the "Compatibility" tab
4. Click "Change high DPI settings"
5. Check "Override high DPI scaling behavior"
6. Set "Scaling performed by:" to "Application"

I'm not sure why this fixes it. I just fiddled with the settings until it appeared to work.

**Comment by AgentXLP** [comment]
What is your screen resolution

**Comment by AgentXLP** [comment]
Should be fixed
