### ISSUE TITLE
My game crashes when I use custom voices with Character Select, and I'm in PC.

### ISSUE THREAD

**Issue by KitCatlol** [coop-deluxe/sm64coopdx#573]
When I or a friend in the server has custom voices on, my game crashes on the 3th or 4th custom sound, then we can't play.

Please Fix

**Comment by AgentXLP** [comment]
* Are you on 1.0.4?
* Are you on CS v1.9.1 or higher?
* What characters are you using?

**Comment by KitCatlol** [comment]
I'm on the latest version of sm64coop dx, Character select, and I have 179 characters

**Comment by AgentXLP** [comment]
There is likely something wrong with multiple or more of the **179** characters mods themselves.
