### ISSUE TITLE
Cannot Connect to Coop Network

### ISSUE THREAD

**Issue by McManners** [coop-deluxe/sm64coopdx#58]
I have a friend who has never installed Mario 64 PC or has played any co-op related mods for it. I wanted him to finally play 64 Deluxe, but, for some odd reason he loses connection to coop network every time he joins a server, publicly or my private lobby. We did everything we could to troubleshoot it on Windows 11 and nothing has worked. Was wondering if the devs have seen this issue appear?

**Comment by Agent-11** [comment]
This is an issue with dj's CoopNet servers, unfortunately I can't really do anything about it.
