### ISSUE TITLE
How to put the mods and dynos in Permanently in sm64 ex coop dx?

### ISSUE THREAD

**Issue by Ilovevideogamer123** [coop-deluxe/sm64coopdx#59]
How do you put the mods mods and dynos in permanently in sm64excoop dx?

**Comment by Agent-11** [comment]
Please do not use the GitHub issues for questions. Just drag a Lua or ZIP file onto the game and it will import the file to your user path (`%AppData%\sm64ex-coop` on Windows)

**Comment by Ilovevideogamer123** [comment]
I am sorry will you forgive me?

**Comment by Ilovevideogamer123** [comment]
Great. Love your mods I'm subscribed to you on youtube see ya :D
