### ISSUE TITLE
unban request

### ISSUE THREAD

**Issue by SMG964** [coop-deluxe/sm64coopdx#599]
i am no longer racist, toxic or underaged so plz unban me and i learnt my lesson
configuration thing for unban
fullscreen true
window_x 0
window_y 29
window_w 1920
window_h 991
vsync false
msaa 16
texture_filtering 2
show_fps true
uncapped_framerate true
frame_limit 60
interpolation_mode 1
coop_draw_distance 5
master_volume 80
music_volume 127
sfx_volume 127
env_volume 127
fade_distant_sounds false
mute_focus_loss false
key_a 0026 1000 ffff 
key_b 0033 1001 ffff 
key_x 0017 1002 ffff 
key_y 0032 1003 ffff 
key_start 0039 1006 ffff 
key_l 002a 1009 ffff 
key_r 0036 100a ffff 
key_z 0025 101a ffff 
key_cup 0148 ffff ffff 
key_cdown 0150 ffff ffff 
key_cleft 014b ffff ffff 
key_cright 014d ffff ffff 
key_stickup 0011 ffff ffff 
key_stickdown 001f ffff ffff 
key_stickleft 001e ffff ffff 
key_stickright 0020 ffff ffff 
key_chat 001c 1007 ffff 
key_playerlist 000f 1004 ffff 
key_dup 0147 100b ffff 
key_ddown 014f 100c ffff 
key_dleft 0153 100d ffff 
key_dright 0151 100e ffff 
key_console 0029 003b ffff 
key_prev 0016 ffff ffff 
key_next 0018 ffff ffff 
key_disconnect ffff ffff ffff 
stick_deadzone 16
rumble_strength 100
gamepad_number 0
background_gamepad 1677721601
disable_gamepads false
use_standard_key_bindings_chat true
bettercam_enable true
bettercam_analog true
bettercam_mouse_look false
bettercam_invertx false
bettercam_inverty true
bettercam_xsens 50
bettercam_ysens 50
bettercam_aggression 0
bettercam_pan_level 0
bettercam_degrade 100
debug_offset 0
debug_tags 0
lua_profiler false
debug_print false
debug_info false
debug_error false
coop_player_name \#8100ff\SuperMario\#00b500\Glitchy964\#ff6700\DaPaniniRayz!
coop_player_model 0
coop_player_palette_pants 81 00 ff
coop_player_palette_shirt 00 b5 00
coop_player_palette_gloves fe ff ff
coop_player_palette_shoes 00 00 00
coop_player_palette_hair 73 06 00
coop_player_palette_skin fe c1 79
coop_player_palette_cap ff 67 00
coop_player_palette_emblem ff 00 ff
amount_of_players 16
bubble_death true
coop_host_port 7777
coop_host_save_slot 1
coop_join_ip localhost
coop_join_port 7777
coop_network_system 0
coop_player_interaction 1
coop_player_knockback_strength 25
coop_stay_in_level_after_star 0
coop_nametags true
coop_bouncy_bounds 0
skip_intro false
pause_anywhere false
coop_menu_staff_roll false
coop_menu_level 0
coop_menu_sound 1
coop_menu_random false
disable_popups false
language English
dynos_local_player_model_only false
coopnet_ip net.coop64.us
coopnet_port 34196
coopnet_password 
coopnet_dest 0
djui_theme 3
djui_theme_center false
djui_theme_font 1
djui_scale 0
rules_version 1
compress_on_startup false
enable-mod: roles_list_v1.3.lua
enable-mod: troopa-emotes.lua
enable-mod: clickthestar.lua
enable-mod: DM64 SERVER.lua
enable-mod: fixed-thirdies.lua
enable-mod: SM64Coop-GrabPlayer
enable-mod: N64 Luigi and Wario Voice Pack
enable-mod: no-head-rotation.lua
enable-mod: omm-cap-state.lua
enable-mod: omm-coop
enable-mod: painting_overlay.lua
enable-mod: roblox-chat-bubbles.lua
enable-mod: Romhacks Plugins (All in One)
enable-mod: sonic-char-rebooted
enable-mod: StarDisplay.lua
enable-mod: super-forms
enable-mod: SMG Luigi Voice
enable-mod: SMG Mario Voice
enable-mod: super.lua
enable-mod: SMBW powerup animation
enable-mod: courses.lua
enable-mod: dialogs.lua
enable-mod: f_bell-castle-grounds
enable-mod: Automatic-doors.lua
enable-mod: moving_textures.lua
enable-mod: tweaks.lua
dynos-pack: Coop Cafe Pipe
dynos-pack: Fixed Smoke
dynos-pack: Galaxy Goomba
dynos-pack: gfx
dynos-pack: Outline Cap Color
dynos-pack: sonic icon
save-name: 0 SM64
save-name: 1 SM64
save-name: 2 SM64
save-name: 3 SM64

**Comment by logimac1520Git** [comment]
Sorry man I didn’t know you got banned that’s so sad :(

**Comment by Random64Guy** [comment]
I can't forgive you

**Comment by BobberyTheSailor** [comment]
Yikes get a real life and get some friends instead of wasting thousand years to get unbanned, Mr. IFindLoopholesToGetUnbanned

**Comment by SMG964** [comment]
i only got unbanned for 1 day and i want unban again

**Comment by ExtCan** [comment]
Jesus fucking Christ, stop begging to be unbanned using GitHub issues. If you got banned, too fucking bad.
