### ISSUE TITLE
Crash upon joining a game

### ISSUE THREAD

**Issue by kenan238** [coop-deluxe/sm64coopdx#60]
**Describe the bug**
It crashes my game, I suppose it's because I'm using the incorrect version, but I should quit gracefully, not crash.

**To Reproduce**
1. Join a newer lobby

**Expected behavior**
Gracefully quit

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/73741117/50785c0f-92ac-40fa-82bd-7e25ddc47a29)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave (Chromium-based)
 - Version v0.1.2

**Additional context**
Nothing else to add

**Comment by Agent-11** [comment]
Just so you know, you're on an older version and this crash might already be fixed. I will be fixing the crash screen in the version coming out today though.
