### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by joshua-holmes** [coop-deluxe/sm64coopdx#600]
**Describe the bug**
I keep getting a seg fault when playing. I only have 2 mods enabled: day/night cycle (comes with the sm64ex-coop deluxe) and [gore/hard mode](https://mods.sm64coopdx.com/mods/gore-hard-mode.422/). I play for no more than 15 minutes (as few as 2) and it crashes. It always crashes in a level, but never the first time I enter a level on a new save. Always second time I enter a level or later. Not consistent which level. 3 times it was in bob-omb battlefield  and once in whomps.

**To Reproduce**
Try hosting a gore/hard mode game on linux and go to bob-omb battlefield like 3 or 4 times on a new save file. Dying by the first sign you see is fine because it makes re-entering the level faster.

**Expected behavior**
The game should crash completely

**Screenshots**
![image](https://github.com/user-attachments/assets/a845f60d-9d07-4fc9-aeec-859814d214a5)

**Desktop (please complete the following information):**
 - OS: Arch Linux, kernel 6.12.7-arch1-1
 - sm64excoopdx version: 1.0.4

**Comment by AgentXLP** [comment]
Fixed in 1.1

**Comment by joshua-holmes** [comment]
Wonderful, thanks so much
