### ISSUE TITLE
Where Get Help with lua

### ISSUE THREAD

**Issue by UnknownSkid** [coop-deluxe/sm64coopdx#61]
Where are you supposed to get help with lua stuff if not in the discord server that is friend invite only, i cant join the sm64ex-coop server for some reason, also how does friend invite even work, do i have to know a moderator

**Comment by uuphoria2** [comment]
2 modding tutorials
part 1 sm64excoop modding (which also works on coopdx by agent-11)
https://www.youtube.com/watch?v=5o2szSCpq34

(also by agent-11)
Part 2:
https://www.youtube.com/watch?v=XBx01loCmjY
