### ISSUE TITLE
Cant Jump without opening chat (xbox one s controller)

### ISSUE THREAD

**Issue by shifturret** [coop-deluxe/sm64coopdx#63]
**Describe the bug**
Everytime i jump the chat opens, even after changing the keybinds
**To Reproduce**
1. Turn on controller
2. Jump

**Expected behavior**
Jump normally, chat function stays assigned to the enter key
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera GX
 - Version 0.1.3

**Additional context**

**Comment by Agent-11** [comment]
Sounds like you need to rebind your controls.

**Comment by shifturret** [comment]
"Everytime i jump the chat opens, even after changing the keybinds"

Tried that already, doesn't change anything. I've even tried unbinding the chat keybind and it still opens the chatbox
