### ISSUE TITLE
You cant grab Bowsers tail in the air like you can in vanilla 64/CoopEX

### ISSUE THREAD

**Issue by RedwingandLuca** [coop-deluxe/sm64coopdx#65]
**Describe the bug**
You know that trick to grab bowsers tail while hes on the rebound from a bomb? CoopDX wont let you do that, instead making you take damage.

**To Reproduce**
1. Go to Bowser 3
2. Throw Bowser into a bomb
3. While hes being sent back, attempt to sideflip and grab his tail out of the air
4. Instead of grabbing, you take damage.

**Expected behavior**
Whats MEANT To happen, is you are meant to grab his tail and be able to throw him again, its a common speedrunner technique.

**Screenshots**
Dont need.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser OperaGX
 - Version Most recent CoopDX version as of 2/6/2024, however this bug was in the release version as well.

**Additional context**
There are other bugs such as i THINK tail storage but i havent tested that, if it is a bug, just run through bowser, get hit, run through him and then a couple inches away, Sideflip and dive, you SHOULD be able to grab Bowsers tail while not being near it.

**Comment by Agent-11** [comment]
This is incredibly strange, I'll have to look into this.

**Comment by AgentXLP** [comment]
I was able to grab his tail, I think you just weren't skilled enough.
