### ISSUE TITLE
Toadette's textures getting bugged in romhacks

### ISSUE THREAD

**Issue by ER1CKS** [coop-deluxe/sm64coopdx#66]
This bug makes toadette's face or metal texture appear over the entire level, can also start flashing over your eyes, this could possibly cause seizures. this issue only happens in romhacks.

To reproduce this, you can go to the creepy cap cave in star road, or play pretty much any level in star revenge 2, many other romhacks as well

![Screenshot_182](https://github.com/coop-deluxe/sm64coopdx/assets/159642401/8afc9fcd-757f-4aa3-adbb-fa9877174986)
![Screenshot_183](https://github.com/coop-deluxe/sm64coopdx/assets/159642401/51ba5d51-f41a-4003-b749-493f36ee000e)
![Screenshot_184](https://github.com/coop-deluxe/sm64coopdx/assets/159642401/e69ebe99-43b9-43d4-b6ef-cd4a365446d9)
![Screenshot_185](https://github.com/coop-deluxe/sm64coopdx/assets/159642401/1895717c-070d-4f7c-b6c0-6fefb435128f)

**Comment by Agent-11** [comment]
@FluffaMario @AngelicMiracles
