### ISSUE TITLE
how do i fix this...

### ISSUE THREAD

**Issue by KodiHasIssues** [coop-deluxe/sm64coopdx#70]
*i am on direct x version
windows 10 pro
4 gb ram
intel hd graphics
intel cpu 2.13 ghz
 opera gx browser*

i just run the game and just got this
![image](https://github.com/coop-deluxe/sm64coopdx/assets/160290785/db1d572f-0f8c-46a1-a6ad-0cd076f9da6c)

**Comment by Agent-11** [comment]
This will be fixed in the new version coming out today, I will be compiling with DirectX 11 instead of 12.
