### ISSUE TITLE
Latest release flagging as Virus

### ISSUE THREAD

**Issue by Sophilautia** [coop-deluxe/sm64coopdx#71]
**Describe the bug**
Downloading the latest 0.2.3 release causes firefox to flag it as a potential virus, and then Windows 11 won't allow the patcher to be unzipped because it claims it's a virus.

**Screenshots**
![pPmlMDq0PJ](https://github.com/coop-deluxe/sm64coopdx/assets/10488699/682c6760-8ab1-4fed-93db-802dc7e5cc94)
![vQPqUPn82T](https://github.com/coop-deluxe/sm64coopdx/assets/10488699/6884fa1e-22d4-426e-81f4-37f8845fad79)
![explorer_7h1xCbvHcG](https://github.com/coop-deluxe/sm64coopdx/assets/10488699/4dea33a1-371f-4aa3-ae3f-343f4dac68a9)

**Desktop**
 - OS: Windows 11 Home 10.0.22621
 - Browser: Firefox 123.0

**Comment by Agent-11** [comment]
I hate this problem so much. Things were cooling down with Windows Defender being on the patcher for no reason and now it's back on full force screwing things over. I have submitted the patcher to Microsoft Security Intelligence in hopes they fix their dumbass antivirus.

**Comment by uuphoria2** [comment]
> I hate this problem so much. Things were cooling down with Windows Defender being on the patcher for no reason and now it's back on full force screwing things over. I have submitted the patcher to Microsoft Security Intelligence in hopes they fix their dumbass antivirus.

Windows defender has always sucked. Almost every program gets detected as a "virus" (false positive)
