### ISSUE TITLE
Controller is not detected by game

### ISSUE THREAD

**Issue by Nylilsa** [coop-deluxe/sm64coopdx#72]
**Describe the bug**
The game does not consider my USB controller to be connected to the game. When trying to rebind my keys using the controller, the game considers it as if there is no input being detected. Additionally, the option "gamepad" is always at 0 and cannot be changed.

**Expected behavior**
The game detects my controller

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/101948046/bb33478b-0dc5-4e57-8b15-2da9c45af5b0)

**Desktop**
 - OS: Windows 10
 - Version: https://github.com/coop-deluxe/sm64coopdx/releases/tag/patcher-v0.2.3
 - Tested on both OpenGL and DirectX

**Additional context**
Other emulators/games do detect the controller so it is connected. Rebinding my controller to keyboard controls does not work either (e.g. rebinding my L1 controller button to the Left Shift button, then pressing my L1 controller button in-game does not do anything even though if I press the Left Shift button the game does detect it)

**Comment by Agent-11** [comment]
Is your controller DirectInput or XInput?

**Comment by Nylilsa** [comment]
The controller is DirectInput.

**Comment by Agent-11** [comment]
Ah, that explains it. I suppose the controller library only supports XInput devices meaning you'll have to use something like [DS4](https://ds4-windows.com/) or possibly [XOutput](https://github.com/csutorasa/XOutput).
