### ISSUE TITLE
Game crash by an attempt to personalize GUI.

### ISSUE THREAD

**Issue by Extendooooo** [coop-deluxe/sm64coopdx#74]
### **Bug description:**
Checking off "Staff Roll" in the Menu Options would crash the game entirely.
It happened to me the first time I accidentally produced this issue. Reopening the application and reproducing the problem does nothing.

### **To produce behavior:**
1. On the title screen menu, navigate to "Options".
2. Then you click on "Misc".
3. Go to "Menu Options".
4. Check off "Staff Roll".
5. See image posted above.

### **Expected behavior:**
There was nothing specific I was expecting, but I was just playing around with settings to see how much I could personalize the DJUI.

### **Screenshots:**
![afbeelding](https://github.com/coop-deluxe/sm64coopdx/assets/91732391/51e72db0-587f-4336-b011-201a40afae70)

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 123.0 (64-bit)

**Comment by Agent-11** [comment]
Please update to v0.1.4
