### ISSUE TITLE
No lobbies found glitch

### ISSUE THREAD

**Issue by TheogfloppaYT** [coop-deluxe/sm64coopdx#76]
when i type a password it does not work (0.1.4)
sm64ex-coop compatibility is turned on

**Comment by uuphoria2** [comment]
I tried private server support with coop compatibilty it worked for me.
Check the spelling of the password you were given to join or is there even a server(s) running on that password?

**Comment by uuphoria2** [comment]
@Agent-11 come take a look at this please :D

**Comment by Agent-11** [comment]
> I tried private server support with coop compatibilty it worked for me.
> Check the spelling of the password you were given to join or is there even a server(s) running on that password?

Yeah I doubt there's any problem other than not typing the password correctly or mismatching coop compatibility options
