### ISSUE TITLE
Free-Cam C-Up softlock

### ISSUE THREAD

**Issue by RedwingandLuca** [coop-deluxe/sm64coopdx#78]
**Describe the bug**
If the camera is in the V arrow state, mario will get softlocked and the camera will never zoom in to allow C-Up to happen.

**To Reproduce**
1. Start the game.
2. Click on "Free Camera" and "Free Cam C-up"
3. easist way is to C-up once or enter a bubble and zoom the camera out, (Sometimes outside of this itll enter the V arrow state)
4. Next time you C-up the game will softlock.

**Expected behavior**
Whats expected is to actually be able to use C-Up

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/87355237/498172c8-5672-408e-8858-4d1dd5d00cc7)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/87355237/b701b44c-02f4-4f6b-9730-3a1d14820d1c)
(While im in Er1cks server, it still happens in nonromhacks/mods.)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version Most recent version as of 2/28/2024

**Additional context**

**Comment by uuphoria2** [comment]
I reproduced the behavior and what i did was i changed my c-up (in my controls) from `up` to `1` then changed it back to `up` I barely use free cam tho

**Comment by uuphoria2** [comment]
Tho normally this is indeed a bug
