### ISSUE TITLE
Unable to download roms

### ISSUE THREAD

**Issue by IAmNewToGitHub12** [coop-deluxe/sm64coopdx#79]
I wanted to see if I could download the rom "SM64 The Green Stars", I tried zip files and .z64 files, but It failed to import. I tried a different rom, but that also failed. My brother has I think downloaded the b3313 rom before, but I am having trouble downloading different roms

**Comment by Agent-11** [comment]
You can't import ROMs into the game. A playable coop rom hack requires a manual port into the form of a mod.

**Comment by IAmNewToGitHub12** [comment]
I think I was also using the coopdx from the sm64coopdx.com website, I am not sure if it is different than this github one

**Comment by Isaac0-dev** [comment]
You can get green stars here:
https://github.com/Isaac0-dev/coop-mods/archive/refs/heads/green-stars.zip

**Comment by Isaac0-dev** [comment]
> I think I was also using the coopdx from the sm64coopdx.com website, I am not sure if it is different than this github one

they're the same versions, don't worry
