### ISSUE TITLE
Can't move in First person

### ISSUE THREAD

**Issue by Dacatzgoescodin5267** [coop-deluxe/sm64coopdx#80]
Description.
When ever selecting the Gun mod or Quake movement, the movement controls will not work and it seems to cause a softlock since disables the pause botton. The only way to fix it is to close the game.

1. Enable either mod
2. Host a game.

Expected behavior
To have the movement controls to work and not being softlocked.

**Comment by Agent-11** [comment]
This is strange, I haven't heard about this before.

**Comment by Dacatzgoescodin5267** [comment]
> This is strange, I haven't heard about this before.

You tested the thing or is their something i did wrong that something got messed up? Since I did nothing wrong and i didint mess with nothing

**Comment by Agent-11** [comment]
Could you provide a video of this happening?

**Comment by smallrobuxman** [comment]
did you ever figure out how to fix this?

**Comment by smallrobuxman** [comment]
heres a video if you still need it :
https://github.com/coop-deluxe/sm64coopdx/assets/80533565/ae156de4-1fcd-442a-9863-90e073ad4cc4

**Comment by AgentXLP** [comment]
Did you patch using DirectX?

**Comment by smallrobuxman** [comment]
I tried both OpenGL and DirectX and they both yield the same result but I was using opengl in the video if it matters.
