### ISSUE TITLE
"warpbug" when skipping the star select animation

### ISSUE THREAD

**Issue by GreenTurtle598** [coop-deluxe/sm64coopdx#83]
**Describe the bug**
At the moment of entering a painting, something which I've called a "warpbug" happens.

**To Reproduce**
1. Go to any Castle Floor.
2. Choose any painting that. (won't work on warps like the one on the slide or something like that)
3. Try to do the Stage Select Animation Skip strat, maybe try doing it quick (?).

**Expected behavior**
You'll always get warped into a random zone and always get a superspeed effect. The zone you get teleported to, depends on the Castle Floor. It's not very stable, there'll be times you won't be able to do it, because the chances are low or it needs a timing (?) [NOT COMPLETELY SURE ABOUT THIS]. The discord video explains it better. 

**Attachments**
[(https://cdn.discordapp.com/attachments/752821559508467862/1214101586582966312/thewarpbugexp.mp4?ex=65f7e337&is=65e56e37&hm=331f14ef992e6702937b931e64e0acd59a81809d846bd595a79192e0d0b1c088&](url)

**Desktop**
 - OS: Windows 10 Professional Edition
 - Browser: Microsoft Edge
 - Version: sm64coopdx 0.1.4 [tried on a previous version, and a previous to the previous and still happens.]

**Additional context**
It only happens on sm64coopDX, I've tried several times on sm64excoop and emulators, but it's not working. (btw, this is one of the greatest bugs and the first one I've ever discovered on a Mario game)

**Comment by Agent-11** [comment]
Fixed in the next update
