### ISSUE TITLE
Can't Use Controller

### ISSUE THREAD

**Issue by BroganArm** [coop-deluxe/sm64coopdx#84]
Every time I try to bind a Controller the Buttons work but I can't bind the thumbstick. Also, the Gamepad Setting is stuck on just "0" Am I missing something? The controllers I try to use are a Generic Gamepad (Which is a Unofficial N64 USB Controller), DualSense, and Nintendo Switch JoyCons.

**Comment by Agent-11** [comment]
The 0 is the gamepad index, you can change it when you have multiple controllers connected and want a specific instance to use a specific controller.
DirectInput controllers don't work, you will need something like BetterJoy to make the game read it as an XInput controller which is what it supports. I will try and see if adding DirectInput support is doable or not with how the controller code is setup.

**Comment by BroganArm** [comment]
Well, the Joycons worked (cuz I'm a newbie, and I think the Dualsense works as well) but the Generic Gamepad doesn't

**Comment by BroganArm** [comment]
(Just for Info I'm a newbie with your software) So, I found that JoyCons works, I'm guessing probably the dual sense will work as well, but the Generic Gamepad doesn't I'm gonna try a software that makes Generic Gamepads work. Anyways, will there be a Clear Bind Button and/or a Reset Binds to Default feature?
