### ISSUE TITLE
macOS native arm compilation fails

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#87]
First error:

<img width="565" alt="Screenshot 2024-03-14 at 8 24 24 PM" src="https://github.com/coop-deluxe/sm64coopdx/assets/86802223/379cda61-7938-422b-a631-f098ab7de898">

Moving `s32 index = gLevelValues.useGlobalStarIds ? starByte : courseIndex;` out of the switch statement fixes it (for whatever reason).

The lua library is also invalid for whatever reason, and refuses to link. Simply using the one in the coop repo fixes it (although idk if you updated lua or not :/). The exact error for that is `ld: archive member invalid control bits in '/Users/calebelm/sm64coopdx/lib/lua/mac_arm/liblua53.a'`.

Also, the discord libs just didn't exist ¯\\_(ツ)_/¯ . You can get the `aarch64` folder from the coop dev repo, and put that in `lib/discordsdk` (the libs are not in the normal coop repo).

**Comment by Agent-11** [comment]
Will look into

**Comment by Agent-11** [comment]
Alright calebelm, I have pushed fixes.

**Comment by EmeraldLoc** [comment]
Sorry! I missed something. Libjuice isn't signed for some reason, so it refuses to launch. This can be fixed by just using the lib found in the coop repo (as that is signed fine)
