### ISSUE TITLE
macOS Arm Compilation Fails (reopened)

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#88]
Can't reopen prs, so ill just resent what I sent in there.

Sorry! I missed something. Libjuice isn't signed for some reason, so it refuses to launch (gotta love apple). This can be fixed by just using the lib found in the coop repo (as that is signed fine, and is the same libjuice version)

Also, you missed `libdiscordsdk` and `discord_game_sdk.dylib` (the bundle is the wrong file and shouldn't even exist lol (it compiles fine without it)) so it still doesn't compile.

**Comment by Agent-11** [comment]
I just got in bed :agony:

**Comment by Agent-11** [comment]
Alright hopefully I don't have to do anything else.

**Comment by EmeraldLoc** [comment]
Alr ill test that, sorry

**Comment by EmeraldLoc** [comment]
The discord libs still aren't added 😬.

**Comment by Agent-11** [comment]
I did though
Sigh, let me do this again.

**Comment by Agent-11** [comment]
Yeah the only thing different with the dev repo is that it has a .bundle file.

**Comment by EmeraldLoc** [comment]
[aarch64.zip](https://github.com/coop-deluxe/sm64coopdx/files/14610097/aarch64.zip)

Dont know what your seeing, there's the aarch64 folder i have

**Comment by Agent-11** [comment]
Oh what the hell, I see the problem, Git is ignoring the aarch64 folder For Some Reason Beyond My Comprehension!

**Comment by Agent-11** [comment]
It was an issue with my Git locally, fixed and pushed.

**Comment by EmeraldLoc** [comment]
Alr testing

**Comment by EmeraldLoc** [comment]
Still isn't added :/

**Comment by Agent-11** [comment]
But I literally committed the files and I added them and they were there what???????????????
Emerald I can't express my hatred for Git in any human dialect.

**Comment by Agent-11** [comment]
![image](https://github.com/coop-deluxe/sm64coopdx/assets/44549182/72d35503-ff53-4837-81e4-027f2df16b8f)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/44549182/a2aeaa10-8108-47ae-bb30-fc3d2bf3154f)

**Comment by EmeraldLoc** [comment]
Lol. yea idk, only thing I can think of is git add, but you've already done that, so I got nothing :/. Maybe try tomorrow when your well rested :).

**Comment by Agent-11** [comment]
Alright, thanks.

**Comment by EmeraldLoc** [comment]
Whenever your ready to get back to this, just wanted to let you know I found these lines in the `.gitignore` file in the root dir:

```
!/lib/discordsdk/*.*
!/lib/discordsdk/x86/*.*
```

Assuming `!` means to not ignore them, maybe adding the `aarch64` folder fixes it?

```
!/lib/discordsdk/aarch64/*.*
```

Then run `git add ./lib/discordsdk/aarch64/*.*`, and try to commit it, hope that works lol

**Comment by Agent-11** [comment]
I think this finally fixed it.

**Comment by Agent-11** [comment]
Pushed, let me know if you can compile now so I can finally close this for good.

**Comment by EmeraldLoc** [comment]
Looks like the files were added, gonna compile it rn

**Comment by EmeraldLoc** [comment]
Worked :D! Thank's for your time, fully launches and all!
