### ISSUE TITLE
[Feature Request] Add sm64ex-coop compatibility button to host menu

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#89]
Pretty much the title, would be really handy. Here's a mockup

![Untitled](https://github.com/coop-deluxe/sm64coopdx/assets/86802223/95e3dc8f-891c-4b9c-845f-11475484f4c1)

**Comment by xLuigiGamerx** [comment]
confirmed by agent x that next major update will fully remove ex coop compatibility

**Comment by EmeraldLoc** [comment]
Oh, dang, uh, i'll close this then...
