### ISSUE TITLE
Navigation skips over "Enable sm64ex-coop compatibility"

### ISSUE THREAD

**Issue by EmeraldLoc** [coop-deluxe/sm64coopdx#90]
The title. Here's a video of it 

https://github.com/coop-deluxe/sm64coopdx/assets/86802223/3c0cd843-6cd6-4d0a-8cd3-1700859d6274

**Comment by Agent-11** [comment]
The next major release will remove sm64ex-coop compatibility, which will by proxy remove this bug.

**Comment by EmeraldLoc** [comment]
Oh yea, I should probably close this lol
