### ISSUE TITLE
"Failed to connect to player 'unknown'"

### ISSUE THREAD

**Issue by Rainbowderpz** [coop-deluxe/sm64coopdx#91]
This has not been a problem before, but one of my friends cannot join when I host a game (and I can't join their game). 
Every time we try, it shows a "..." where it usually installs mods, then it kicks us out after a minute with the error:

"Server closed; Failed to connect to player 'unknown'" 

This has not happened before, nor does it happen with anyone else I play with.

![Screenshot 2024-03-15 184511](https://github.com/coop-deluxe/sm64coopdx/assets/45805910/44afc137-dfe8-4175-9c67-9f030e739a5c)
![Screenshot 2024-03-15 184552](https://github.com/coop-deluxe/sm64coopdx/assets/45805910/6b3aea12-beef-48ce-9b2b-b75be3f0892b)

**Comment by Agent-11** [comment]
It looks like you're trying to join an sm64ex-coop lobby, if you are make sure you have sm64ex-coop compatibility enabled.

**Comment by Rainbowderpz** [comment]
> It looks like you're trying to join an sm64ex-coop lobby, if you are make sure you have sm64ex-coop compatibility enabled.

Both of us were using sm64coopdx (v0.2), how would it be an sm64ex-coop lobby (I don't exactly know how servers work on here yet)? Also, I am pretty sure that I had compatibility on, do we both need it on for it to work?

**Comment by Agent-11** [comment]
![image](https://github.com/coop-deluxe/sm64coopdx/assets/44549182/dd5aa705-c50a-4545-ba15-14f1de7173b1)
I noticed this on your join screen screenshot. Make sure both of you guys have sm64ex-coop compatibility off and it should work fine.

**Comment by Rainbowderpz** [comment]
> ![image](https://private-user-images.githubusercontent.com/44549182/313410874-dd5aa705-c50a-4545-ba15-14f1de7173b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDYzNjUsIm5iZiI6MTcxMDYwNjA2NSwicGF0aCI6Ii80NDU0OTE4Mi8zMTM0MTA4NzQtZGQ1YWE3MDUtYzUwYS00NTQ1LWJhMTUtMTRmMWRlNzE3M2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE2MjEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NmFmYmFhZDM1NzhiMjk4N2IzMzhkNTZlMzIwYzI1MDI3MDljMjY3NWM3ZjkxMmZlMDgyMGFkNzEzMTIyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r2rZl21VTS1iXdRFCHf_hCulFzRypQ3ghh4x1Xc0St8) I noticed this on your join screen screenshot. Make sure both of you guys have sm64ex-coop compatibility off and it should work fine.

We tried the first few times with the setting off, but it happened just like that. I'll try it again just to make sure, though.

**Comment by Rainbowderpz** [comment]
> ![image](https://private-user-images.githubusercontent.com/44549182/313410874-dd5aa705-c50a-4545-ba15-14f1de7173b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MTM2NzQsIm5iZiI6MTcxMDcxMzM3NCwicGF0aCI6Ii80NDU0OTE4Mi8zMTM0MTA4NzQtZGQ1YWE3MDUtYzUwYS00NTQ1LWJhMTUtMTRmMWRlNzE3M2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDIyMDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NmViOTFiYmRlOTBkNzJiZTZhMmJiNDFkMTNhZmNjZjA5ZDkxMTI0NjNmM2FmYWZjMTgzMDg3NjhkOGZhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NxjF5VH2DXfMBW6LNzEeTqAMS_7QeBObAWzvxtWQJ-M) I noticed this on your join screen screenshot. Make sure both of you guys have sm64ex-coop compatibility off and it should work fine.

After turning it off, it said "v0.2", but it still does not work. Everything is the same as the other attempts.

**Comment by windows10-gthb** [comment]
idk about you, but reconnecting like 10 times or more works for me

**Comment by marioandluigisuperstarsaga** [comment]
i'm having the same issue, but on all servers

**Comment by ra4107187-prog** [comment]
AgentXLP me pasa lo mismo en ex coop no me deja entrar a partidas y me aparece ese error (soy de android)
