### ISSUE TITLE
Audio crackle when specifically Discord is opened

### ISSUE THREAD

**Issue by KindOfASpork** [coop-deluxe/sm64coopdx#94]
**Describe the bug**
Game audio works fine normally, but once Discord is opened, game audio begins to crackle. Game audio will only return to normal after a system reboot or a change in audio device.

**To Reproduce**
1. Open sm64coopdx
2. Open Discord
These steps can be done interchangeably, such as opening Discord first, closing it, and opening sm64coopdx.

**Expected behavior**
Game audio should continue to behave normally.

**Screenshots**
No screenshots available, as this is an audio bug.

**Desktop**
 - OS: Windows 10

**Additional context**
I have [VoiceMeeter](https://vb-audio.com/Voicemeeter/index.htm) setup on my PC. This may be related to the issue.

**Comment by MlopsFunny** [comment]
It might have to do with specs or wich version you built, as I personally have not ran into such a issue.

**Comment by eros71-dev** [comment]
Hmm that's strange, I haven't ran into that issue so far. Have you tried running the game and discord without VoiceMeeter? Sound like the kind of issue you'd run into when the audio buffer is set too low, maybe check VoiceMeeter's settings for that if it has something like it.

**Comment by KindOfASpork** [comment]
> Hmm that's strange, I haven't ran into that issue so far. Have you tried running the game and discord without VoiceMeeter? Sound like the kind of issue you'd run into when the audio buffer is set too low, maybe check VoiceMeeter's settings for that if it has something like it.

I have actually run it without VoiceMeeter and it doesn't crackle without fail.
I'll have to see if messing with audio buffer settings can fix that.

**Comment by KindOfASpork** [comment]
Audio issue seems to be fixed for now? I followed this comment's setup and it worked. - https://www.reddit.com/r/VoiceMeeter/comments/spynfv/comment/hwkior9/

Might need further testing, but I'll close the issue for the time being.
