### ISSUE TITLE
English language may be sometimes in capitals

### ISSUE THREAD

**Issue by windows10-gthb** [coop-deluxe/sm64coopdx#96]
**Describe the bug**
Every text would be in capitals

**To Reproduce**
1. Open the game
2. See error

**Expected behavior**
The text would be displayed correctly.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/160930327/d45f54ef-09db-4d20-a5aa-2a232d57fe6e)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Chrome
 - Version 122.0.6261.112

**Additional context**
Changing the language to any other would fix the bug, but it may appear again after reopening the game

**Comment by Chilly-roll** [comment]
this isn't text being in all caps, these are the localization keys used for language swapping. are you using another language that isn't english?

**Comment by Agent-11** [comment]
I will check if the patcher is properly downloading the language files.

**Comment by Agent-11** [comment]
It is, make sure you didn't delete a folder called `lang`.
If not, try repatching and seeing if the lang files are there for you now.

**Comment by windows10-gthb** [comment]
> It is, make sure you didn't delete a folder called `lang`. If not, try repatching and seeing if the lang files are there for you now.

it's not deleted, works quite good right now, it just sometimes did this

> this isn't text being in all caps, these are the localization keys used for language swapping. are you using another language that isn't english?

no, I'm not, it's english

**Comment by Agent-11** [comment]
Huh, odd?

**Comment by windows10-gthb** [comment]
now it doesn't appear. im closing this
