### ISSUE TITLE
[Suggestion] Preventing game crashes during texture loading

### ISSUE THREAD

**Issue by Flower35** [coop-deluxe/sm64coopdx#99]
Hello sm64coopdx team.

I was creating a small mod for the game and I checked any crashes that appeared during gameplay.

I have pinpointed two places in code where a game crash could be avoided in favor of a simple error-check.

---

### 1. Corrupted `"*.png"` / `"*.tex"` files

The **`stbi_load_from_memory()`** library call from `DynOS_Tex_Get()` returns a packed-byte-array of pixels on success, but a **`NULL`** pointer on failure.

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/data/dynos_mgr_tex.cpp#L464

Normally it is expected that all mod assets have correct file formats.

However, back in version `0.1.2` there was a `"grandma.tex"` file, which (possibly while packing the mods) was incorrectly treated as a `text` file (instead of `binary`), and all instances of `<CR> <LF>` bytes were changed to `<LF>`.

This in term corrupted the file, so that image loading failed and the game crashed at `memove()` function called in `template Array::Remove`.

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/data/dynos.cpp.h#L249

---

A `nullptr` check could be added in **`DynOS_Tex_Get()`** to prevent game crashing, and showing a warning about a corrupted `"*.png"` / `"*.tex"` file.

---

### 2. NPOT (Non-Power-Of-Two) texture dimensions

Another issue I noticed is that any texture file (PNG file) with dimensions not being powers-of-two (so for example, `640x480`, `160x160`) would make the game crash on the **`djui_hud_render_texture()`** function call (from a Lua script).

The crash occurs on the **`glTexImage2D()`** call, which surprised me, because the color format is `GL_RGBA`, so the default stride of `4` bytes per line width should not be an issue, however something made the `"ig9icd64.dll"` library crash on my hardware anyways...

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/gfx/gfx_opengl.c#L590

I circumvented this crashing by resizing the image to standard powers-of-two texture dimensions (like `32`, `64`, `128`, `256`, `512`, `1024`) and so the OpenGL does no longer complain.

---

I would suggest that texture **`width`** and **`height`** are checked in `DynOS_Tex` and a warning is issued in **`get_texture_info()`** to prevent an avoidable game crash.

---

**Comment by Agent-11** [comment]
Wow, you are really helpful and create very straightforward and detailed issue reports. It really means a lot to us, thank you.

**Comment by Agent-11** [comment]
Alright, I pushed my changes. It's not on the `dev` branch for now, though.
